### ISSUE TITLE
plural for column and row

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1097]
To make it clear that we facet into not by.

**Comment by kanitw** [comment]
As I explained in slack,  __I'll stick with singular for now__.  

> Hmm.  For Vega-Lite 1.0,  if `row` is an encoding channel,  we are mapping each value of the field to a row.  So singular might make more sense.  For `facet` composition syntax we discuss today, it seems like both singular and plural work depending on how you interpret it.

> Faceting into “rows” -> plural.  

> Faceting by mapping each value of the field to a row -> singular.


> So now I’m thinking that we should actually stick with singular “row”/“column” ?  

> By this I mean, encoding = mapping between a data value and an encoding channel. 
For each value in the `x` field, you map the value to an `x` value. 
For each value in the `color`’ field, you map the value to a `color`. 
For each value in the `shape`’ field, you map the value to a `shape`. 
For each value in the `row`’ field, you map the value to a `row`.    (And thus produces multiple rows.)
(Otherwise, `color`/`shape` channel has to be `colors`, `shapes` too?)

Also we mostly use singular most of the stuff in VL.  


If you strong disagree and think we should do plural, please protest now before we release 1.0 :)
