### ISSUE TITLE
[BUG] incorrect x-axis range(date) in stacked area plot

### ISSUE THREAD

**Issue by xiaohan2012** [vega/vega-lite#1277]
Simply, I am counting the number of items against time intervals.

Code:

```
{
  "data": {
    "url": "https://www.cs.helsinki.fi/u/hxiao/event_html/data/ukraine/vega/data.json"
  },
  "mark": "area",
  "encoding": {
    "x": {
      "timeUnit": "yearmonthdayhours",
      "field": "datetime",
      "type": "temporal",
      "scale": {
        "nice": "hour"
      },
      "axis": {
        "axisWidth": 0,
        "format": "%m-%d %H:00",
        "labelAngle": 15
      }
    },
    "y": {
      "aggregate": "count",
      "field": "*"
    },
    "color": {
      "field": "series",
      "type": "nominal",
      "scale": {
        "range": "category20"
      }
    }
  },
  "config": {
    "cell": {
      "width": 800,
      "height": 400
    }
  }
}
```

The bug is on range of x-axis:

- **Actual**: Feb 8 to Mar, 1.
- **Expected**: Feb-27 to Mar-03(min and max of the datetime in all items)

Or the web app: https://www.cs.helsinki.fi/u/hxiao/event_html/vega.html

**Comment by domoritz** [comment]
The issue is that you need to use date (day of the month) instead of day (day of the week). It's very confusing and I will add documentation to https://vega.github.io/vega-lite/docs/timeunit.html

```json
{
  "data": {
    "url": "https://dl.dropboxusercontent.com/u/12770094/data.json"
  },
  "mark": "area",
  "encoding": {
    "x": {
      "timeUnit": "yearmonthdatehours",
      "field": "datetime",
      "type": "temporal"
    },
    "y": {
      "aggregate": "count",
      "field": "*"
    },
    "color": {
      "field": "series",
      "type": "nominal"
    }
  }
}
```

<img width="352" alt="screen shot 2016-04-04 at 11 43 53" src="https://cloud.githubusercontent.com/assets/589034/14259170/885f469a-fa5a-11e5-9156-99a571a3c30f.png">

I'll add the time units that vega-lite supports from https://github.com/vega/vega/wiki/Expressions#datetime-functions to our docs.
