### ISSUE TITLE
Ticks with size channel are too large

### ISSUE THREAD

**Issue by mprudhom** [vega/vega-lite#1298]
When a `tick` mark has a size encoding, the default scaling makes them too big for the chart.

It might be nice if there was a mark config preference for size `magnitude` which would be a percentage multiple to apply to the size for `point`, `bar`, `tick`, `text`, `circle`, and `square` mark types. That way the size could be adjusted by the user after the default size scaling has been applied.

![unknown](https://cloud.githubusercontent.com/assets/659086/14502442/42f5cd6a-0179-11e6-8531-2d9ce1e58916.png)

```json
{
  "mark": "tick",
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "encoding": {
    "y": {"field": "a", "type": "ordinal"},
    "x": {"field": "b", "type": "quantitative"},
    "size": {"field": "b", "type": "quantitative"}
  }
}
```

**Comment by kanitw** [comment]
I think we will just let user specify range.  Specifying percentage actually makes the API more complicated (need both baseline value and percentage range), which is better done at a higher-level GUI tool if desired.  

The real problem here is we forgot to add default range for tick size.  

Do you want to help add `scaleConfig.tickSizeRange` to [this part of the code](https://github.com/vega/vega-lite/blob/master/src/compile/scale.ts#L384)?
