### ISSUE TITLE
Always fill symbol with transparent fill

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1316]
We should fill all marks so that we can always interact with the whole mark. If we don't have a fill color, it should be filled with a transparent fill. This is useful for tooltips as well as our interactions based on selections.

**Comment by kanitw** [comment]
I doubt if this is always a good idea.  At least, we have to come up with an idea to override default with `undefined` first.

**Comment by domoritz** [comment]
Why do you think it is bad sometimes? I think at least for shapes it always makes sense.

**Comment by ZeningQu** [comment]
I guess one example where always fill marks would be less than ideal is when shape overlaps with each other:

![insideout](https://cloud.githubusercontent.com/assets/822034/14908626/578c0ac0-0d8e-11e6-9507-cb222fac162e.png)

If we implement "always fill mark", it is possible that a mark is visible behind another mark but not selectable due to the transparent fill.

Please also consider the discussion here: https://github.com/vega/vega-lite-tooltip/issues/32

**Comment by domoritz** [comment]
I'd say that this is a bad visualization anyway and there is no way that you can hover over a sepcific mark anyway.

**Comment by ZeningQu** [comment]
Hovering over a hollow mark seems no harder than hovering over a line. If we let user select / hover over a line, why don't we let them select / hover over hollow marks too? Yes, hollow marks are a bit harder to pick up, but you can still pick them up if you try... If we fill the hollow marks, it will be like "I can see it... I just can't pick it up..."

> I'd say that this is a bad visualization anyway 

I agree with you that `point` + `size` encoding is not ideal in may cases. But I don't think they are uncommon. I am looking at the new vega-lite paper Fig 2(b). It uses `point` + `size` encoding because `color` is being used to encode something else. (Please forgive me for not including a screenshot. I don't think you guys want to see it in the public domain)

**Comment by domoritz** [comment]
<img width="741" alt="screen shot 2016-05-03 at 11 03 17" src="https://cloud.githubusercontent.com/assets/589034/14987719/a9fc8cce-111e-11e6-8fb7-af5c93eec64f.png">

Hmm, this one is a good example but I think in general you want to be able to hover even over the empty region. Probably the best solution would be a 3px border around all lines that catches hovers. Anyway, I still think that the better default is to always fill.

**Comment by kanitw** [comment]
I think this example is a strawman one.  A more typical example is normal scatter plot.

**Comment by kanitw** [comment]
I don't think this behavior is always better and also introduce a huge breaking change, so I would like to close it.

**Comment by domoritz** [comment]
What's breaking? We don't support interactions yet so I think the behavior
would be the same.

**Comment by kanitw** [comment]
Breaking visual design of scatterplot.

**Comment by domoritz** [comment]
Oh wait. We're talking about different things then. I mean fill with
something transparent so that the tooltips can be triggered on the full
mark not just the edge.

**Comment by kanitw** [comment]
If you wanna do that, #1285 becomes a higher priority.  

That said, I don't know we should do this becuase people might expect this hidden fill and found them confusing.

**Comment by domoritz** [comment]
I think the auto value could be a transparent fill just to make interactions work better.

**Comment by kanitw** [comment]
ok, thinking more about it we should still do this.

**Comment by domoritz** [comment]
Cool. @ZeningQu do you want to take a stab at this?

**Comment by kanitw** [comment]
We need to be careful.  For example, line should not get transparent fill.

**Comment by domoritz** [comment]
Good point. I changed the title to symbol instead of mark.

**Comment by ZeningQu** [comment]
Can I just fill `point` with its stroke color? Filled points are visually simpler and more friendly to interactions than hollow points?

**Comment by kanitw** [comment]
Let's not do that.  It does not always work well when there are occlusion.  
Plus, it will break a lot of existing visualizations.

**Comment by ZeningQu** [comment]
ok

**Comment by kanitw** [comment]
Any update on this one?  (Fine if you haven't it, just checking if we just haven't merged finished code or something)

**Comment by kanitw** [comment]
Nvm. I took just 5 minutes to fix it, so I just fixed it.
