### ISSUE TITLE
Draw bar charts with binning without gaps

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1337]
One could argue that we are binning a continuous domain and there should be no gaps. 

<img width="271" alt="screen shot 2016-05-03 at 12 55 12" src="https://cloud.githubusercontent.com/assets/589034/14991223/5445e716-112e-11e6-8816-ef18cd30739b.png">

We still want the gaps for categorical data

<img width="260" alt="screen shot 2016-05-03 at 12 58 40" src="https://cloud.githubusercontent.com/assets/589034/14991322/c64c0908-112e-11e6-9284-0b3eea6e09c5.png">

What would be a bit annoying is that we have to offset the ticks by .5px so it is between the bars.

**Comment by kanitw** [comment]
I agree that one should be able to customize the histogram to have to no gaps between bars; however, I wonder if it should be the default since it looks slightly uglier:

<img width="263" alt="vega_editor" src="https://cloud.githubusercontent.com/assets/111269/15095926/caa716da-1496-11e6-804d-a960fe659afd.png">

Mike Bostock's historgram design typically have gaps between bars in the histograms:

- https://bl.ocks.org/mbostock/3048450
- http://bl.ocks.org/mbostock/1933560
- http://square.github.io/crossfilter/.

**Comment by kanitw** [comment]
Fixed in #1618
