### ISSUE TITLE
Can row/column have aggregation?

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1398]
The schema currently allows it but I think that's wrong because we can only use an effectively categorical field (N, O, or Q + bin) and aggregation always produces an effectively qualitative field. 

If this is the case, then we should adjust the schema accordingly.

**Comment by kanitw** [comment]
It's certainly a stupid thing to do. I have this constraint in CompassQL and we might implement validator based on constraints in CompassQL.  

However, splitting `FieldDef` into `Aggregable|FacetFieldDef` might make the codebase much more complex?  (We have to check whether which `FieldDef` they are even more)  

So I'd say, we can try refactoring and if it's not causing too much change, we can do it.  
If it's making type checking horrible, then I don't think we have to prevent it from schema because no one is really gonna put `aggregate` in facet except when we're testing the tool ourselves. 

I wouldn't do this in the PR you're working on though -- already super complicated.

**Comment by domoritz** [comment]
Okay. I just came across it when I was thinking about merging up in faceting. I was thinking whether a facet model can have a `nullFilter` and came to the conclusion no since the col/row fields cannot have an aggregate.

**Comment by kanitw** [comment]
> facet model can have a `nullFilter`

Our `nullFilter` can be turned on for `ordinal` / `nominal` (but it's only on for `Q` by default) right?   
Or are we changing that?

**Comment by domoritz** [comment]
I'm not changing anything. Couldn't find anything in the docs. But you're right. I have to merge then but that's easy.

**Comment by kanitw** [comment]
I guess we can throw warning for this case and that's it?

**Comment by kanitw** [comment]
I think warning would be nice but we have so many things to do and this is really unnecessary.
