### ISSUE TITLE
Make `sort.op` optional

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1489]
Maybe with `min` or `mean` as default op.

**Comment by kanitw** [comment]
I think it's unclear what's the best default so maybe let's not do it.

**Comment by kanitw** [comment]
People are asking for this in https://github.com/altair-viz/altair/issues/884. 

Any of min, median, mean work ok for the simple case.  However, determining a good default requires thinking about more general case.  For example,  if sort is specified for y-encoding of [a strip plot](https://vega.github.io/editor/#/examples/vega-lite/tick_strip), it is unclear what is the reasonable default `op`.

**Comment by domoritz** [comment]
I think @palewire is right. If the chart is not aggregated, the user shouldn't have to specify an aggregation. Unfortunately, Vega requires it so we have to set something and we definitely don't want to set a default when the chart is aggregated.

**Comment by kanitw** [comment]
>  Unfortunately, Vega requires it

Well it's not entirely Vega's fault.  Semantically, it only _always_ work if there is an aggregate operation applied.  (You never know if the field you sort by always have 1:1 correspondence with the axis's field.) 

> we definitely don't want to set a default when the chart is aggregated.

If we have good rationale for the default, I'm open to set it.  But we haven't arrive at a conclusion for a good rationale yet.

**Comment by domoritz** [comment]
Could we set a default (anything really, let's use `max`) for non-aggregated charts?

**Comment by kanitw** [comment]
Given that you prefer max, I'd guess you'd prefer min to mean/median?  **

**Comment by palewire** [comment]
Am I crazy to think that a sensible default would be that if no aggregation function is provided Vega should assume there in a 1:1 relationship between the axis and the sort, raising an error if there isn't?

**Comment by domoritz** [comment]
That would be an enhancement to Vega. Unfortunately, we can't do anything about this in Vega-Lite as we don't have access to the data. Adding @jheer to see what he thinks.

**Comment by iliatimofeev** [comment]
I think `mean` is the best solution. In most of the time you just try to sort bar chart, reordering other types of chart will need very special reason. 

As new user I felt a enlightenment when I come up with understanding that sorting field in fact do not match ordering axis and that is reason behind so complex definition of sorting.

**Comment by iliatimofeev** [comment]
More than, I think would be helpful to have some simple syntax to sort items over second axis values without defining which field to use. I believe that is really default use case that cover most of all. 


```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal", "sort": "descending"},// "sort":{"field":"b","op":"mean","order":"descending"}
    "y": {"field": "b", "type": "quantitative"}
  }
}
```
![export 8](https://user-images.githubusercontent.com/11561581/41204896-4bf1dc50-6cf3-11e8-8300-382bbd151b39.png)

**Comment by kanitw** [comment]
> I think mean is the best solution.

It would be good to hear why do you think mean is the best solution. 


> I think would be helpful to have some simple syntax to sort items over second axis values without defining which field to use. I believe that is really default use case that cover most of all.

That might be helpful, but specifying that you want to sort by the y-axis's field should be simple enough. Thus, we would rather keep the required syntax minimal, esp. if we make `op` optional, that should be sufficient. 

> "y": {"field": "b", "type": "quantitative", "sort": "descending"}

This already has other meaning (sorting by "natural" descending order of the field b).  So we definitely wouldn't introduce a breaking change.

**Comment by iliatimofeev** [comment]
>So we definitely wouldn't introduce a breaking change.

Sure, good point.
Let me try once again: `"sort": "descending_by_other_axis" or "desc_boa" `.  In my opinion (not backed by a research)  sorting by value of another axis improves readability of a bar chart with visual aid of comparing items as opposed to alphabetical sorting categorical names which is neutral in terms of visual expression.

>It would be good to hear why do you think mean is the best solution.

That is a good question which I have no answer except: I put `mean` when I don't know what to put, because is not dependent on the number of items as sum and neutral to outliers unlike `min` and `max`. From this point of view, probably median will be even better, but it has more letters to write :) , it is not clear for me it is expensive in terms of calculations.

But thinking responsibly, I couldn't remember a single example where it was really important, more than I could not synthesize one with test dataset, so I think I'll withdraw my opinion because it is not backed up by practical experience.
![export 9](https://user-images.githubusercontent.com/11561581/41241990-0e125ffe-6da7-11e8-92c5-71899d5d5dad.png)

**Comment by palewire** [comment]
It's unclear to me why mean would be a better default than sum or count. I'm open to hearing from others, but I'm still of the view that there shouldn't be default because anything you'd choose would be arbitrary and, as we say in Python, "magic." For the reasons I stated above, an optional argument is my preference.

**Comment by kanitw** [comment]
> "sort": "descending_by_other_axis" or "desc_boa"

sort is a property of all encoding channels including non-position channel. Thus the "other axis" doesn't always make sense.  Plus, as I said, specifying that you want to sort by the y-axis's field should be simple enough.

-----

@palewire This must be handled at the Vega level.  If you strongly thing the sort op should be optional (for scale with unique value case), could you help file a feature request in Vega?

**Comment by kanitw** [comment]
FWIW, another user on Slack just got confused with the lack of default sort op today.

**Comment by kanitw** [comment]
I might be worth picking either mean or median as the default (mainly to resolve "the simple table with one nominal value and one quantitative value per row" use case).

**Comment by kanitw** [comment]
I'll make "mean" the default sort op in Vega-Lite in https://github.com/vega/vega-lite/pull/4475.
