### ISSUE TITLE
Schema doesn't allow for legend=false

### ISSUE THREAD

**Issue by aishfenton** [vega/vega-lite#1563]
The vega-lite-schema.json file specifies that encoding.legend must be a Legend object, but I see in the doc (and examples) that legend can be set to false too.

```json
ChannelDefWithLegend: { 
  type: "object", 
  properties: {
    legend: {
      $ref: "#/definitions/Legend"
    },
   ...
```

Axis has the same feature (i.e. can be boolean or Axis), but in this case the schema specifies that axis can be Axis | Boolean. 

Looking at the code, I see:

```typescript
export interface PositionChannelDef extends ChannelDefWithScale {
  axis?: boolean | Axis;
}
export interface ChannelDefWithLegend extends ChannelDefWithScale {
  legend?: Legend;
}
```

Can legend be changed to be ```legend?: boolean | Legend;```? As it currently stands third-parties that are generating code using the json-schema aren't able to support legend=false until this is changed. 

PS. Digging a little I see that the boolean feature of legend is supported by custom parsing logic in UnitModel.

**Comment by kanitw** [comment]
Thanks for the reporting.

We added boolean support for axis and legend back then because TypeScript 1 did not have support for null type.  Now that TS 2 is released and support null type, we plan to deprecate using `false` with axis/legend (with backward compatibility) and use `null` as the main way to disable them.  (See the pending #1384.
