### ISSUE TITLE
Stepped Area Chart

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1579]
e.g., https://developers.google.com/chart/interactive/docs/gallery/steppedareachart

**Comment by jheer** [comment]
I think in Vega that is just a (stacked) area chart with a 'step-after' line interpolation option. I think all you need to support this in Vega-Lite is make sure expose line interpolation options...

**Comment by kanitw** [comment]
@YuhanLu  I believe we have `interpolate` config so let's make an example.

**Comment by g3o2** [comment]
`interpolate` will probably provide only a partial solution to this. This is because either `step-after`or `step-before` always leave one extreme data point without a full stair step. For example, with `step-after`, the first data point will only appear as a small point with a vertical line, instead of a starting rule with a vertical line, and vice versa for `step-before`. A workaround is to add the missing horizontal rule manually.

**Comment by kanitw** [comment]
Part of https://github.com/vega/vega-lite/issues/1486
