### ISSUE TITLE
While using log scale the color bars are not shown

### ISSUE THREAD

**Issue by chananelp** [vega/vega-lite#1582]
While trying this: 
```
{
  "description": "A bar chart showing the US population distribution of age groups and gender in 2000.",
  "data": { "url": "data/population.json"},
  
  "mark": "bar",
  "encoding": {
    "y": {
      "aggregate": "sum", "field": "people", "type": "quantitative",
      "axis": {"title": "population"},
      "scale": {"type": "log"}
    },
    "x": {
      "field": "age", "type": "ordinal",
      "scale": {"bandSize": 17}
    },
    "color": {
      "field": "age", "type": "nominal"
    }
  }
}
```

I see no graph.
(May be related to [1518](https://github.com/vega/vega-lite/issues/1518))

If you change the `log` with `linear` all is OK - a colorful bar chart:
![image](https://cloud.githubusercontent.com/assets/16744321/19348336/155e4f54-9156-11e6-8eb7-9946a94add62.png)

**Comment by kanitw** [comment]
Hi, Thanks for reporting. 

First of all, `bar` mark [should be avoided]( http://www.graphpad.com/support/faqid/1477/) if you wish to use log scale,
since there is no zero value on the log scale to the bar's start value.

It's better to use `point` mark like the following:

<img width="913" alt="vega_editor" src="https://cloud.githubusercontent.com/assets/111269/19370830/292bb44c-9163-11e6-8498-00bc0bd600b2.png">

That said, I'll keep this issue open as I think we should throw error and possibly change the default behavior for this case. 

@domoritz @arvind – I think I'll always disable stacking for log scale so at least something is rendered.
