### ISSUE TITLE
Consider a way to deploy multiple versions of docs?

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1663]
This is probably not the top priority right now, but if it's easy maybe we could do it. 

(Inspiration = tensor flow docs)

![tutorials](https://cloud.githubusercontent.com/assets/111269/19976184/f551257c-a1ab-11e6-978f-9a2847e5a8b9.png)

**Comment by domoritz** [comment]
This would be nice but I don't think it's realistically going to happen anytime soon. I'm going to close this as we haven't done this in more than a year and no one has asked for it so far.

**Comment by flash1293** [comment]
Maybe we can give this another thought - Kibana is always a bit trailing in terms of vega/vega lite releases plus a lot of users are running older versions so they don't have access to the latest and greatest. I can imagine other setups having the same problem.

Would be happy to help if there is a way for me to do so (not familiar with the setup).

**Comment by davidgilbertson** [comment]
I'm finding it quite difficult to learn Altair because they use the V4 schema and the Vega-Lite docs are for the V5 schema (and the Altair documentation leaves a lot to the imagination).

Is there an option other than going through the GitHub readmes for the appropriate branch like https://github.com/vega/vega-lite/blob/v4.17.0/site/docs/selection/selection.md (where lots of the links don't work)

**Comment by domoritz** [comment]
We have previous major versions online. See https://vega.github.io/vega-lite-v4/docs/ for v4.

**Comment by davidgilbertson** [comment]
Excellent, thank you very much @domoritz !
