### ISSUE TITLE
Allow specifications without data

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1745]
The idea is that we would still generate a `source` data source but users would need to use the vega view api to set the values. This change would help external tools that want to use Vega programmatically or inject data. One application would be to facilitate https://github.com/frictionlessdata/specs/issues/77

I see data is already optional in https://github.com/vega/vega-lite/blob/master/src/spec.ts#L30. Maybe all we need is to write a test. 

thoughts @kanitw?

**Comment by kanitw** [comment]
> Allow specifications without data

This is fine for a standalone unit specification.  However, as mentioned in #1392, we still need an explicit property to signify that a particular part of a composite spec produces a placeholder data source for binding at runtime.

>  users would need to use the vega view api to set the values

This part we should have a vega-lite wrapper that allow users to refer to the name of a sub-specification rather than having to know what's the compiled data source name.

**Comment by domoritz** [comment]
As a solution for the first issue, we could introduce empty datasources that just set a name. Let's deal with this when we redo the composition.

**Comment by kanitw** [comment]
Let's call this `PlaceHolderData`

**Comment by kanitw** [comment]
Closing as now we have #1392 and #1831
