### ISSUE TITLE
Name map

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#1760]
There seems to be a lot of confusion about having to set domain and range explicitly. See e.g. https://github.com/altair-viz/altair/issues/278. Would it be easier if users could specify a map (key, value) that does the renaming?

**Comment by kanitw** [comment]
I disagree. 

1) That issue is asking for a way for replacing short labels with long labels, which should be done by 
adding a generic `replace` transform https://github.com/vega/vega-lite/issues/1761.  

2) This will introduce two ways of doing the same which you're against most of the time.  
Instead of committing to that early.  I would like to note that we haven't documented how to set custom domain and range very well.  Thus, I suggest that we do that, close this issue, and we can still consider doing this in the future if there are more people complaining.

**Comment by domoritz** [comment]
I think what I'm asking for is a replace transform. The reason why a map is better than two arrays is that it can be partial and is order independent. I do not want two ways to do the same things but would rather replace one.
