### ISSUE TITLE
Bar should not always use opacity

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2027]
```json
{
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative", "aggregate": "mean"},
    "color": {"field": "b", "type": "quantitative", "aggregate": "mean"}
  }
}
```

Since y is aggregated, the bars should not use opacity. 

<img width="304" alt="screen shot 2017-03-08 at 18 54 38" src="https://cloud.githubusercontent.com/assets/589034/23733958/b47ff996-0430-11e7-86dd-c322ae4957d4.png">

**Comment by kanitw** [comment]
> Since y is aggregated, the bars should not use opacity.

The right reasoning would since "color is aggregated" and thus there is no level of detail channels (detail/color/size/...).  

If y is aggregated but color is not, it can produce layered bar in many cases (depending on the data distribution).   


Note that since we don't have access to the data in Vega-Lite, we can't be always correct with opacity in the latter case.   

One possible alternative is that we can always make opacity = 1 for bar but instead order the `z-index` by its value so that we use z-index to mitigate the occlusion instead.  However, z-index would be inferior to opacity as it's hard to notice that it's a layered bar.  (Consider http://vega.github.io/vega-editor/?mode=vega-lite&spec=bar_layered_transparent, for example.)

**Comment by domoritz** [comment]
I understand that we have to consider that users may not notice errors in their visualizations. However, I am concerned that adding opacity changes the perception of colors, which is bad. 

I think we should just throw a warning instead of adding opacity to bars.

**Comment by kanitw** [comment]
First, I'll fix the condition to be more correct.  That should be done for sure. 

> However, I am concerned that adding opacity changes the perception of colors, which is bad.
> I think we should just throw a warning instead of adding opacity to bars.

But I'd say it makes it more noticeable.  (Warning is useful, but less noticeable)

I think we should keep the opacity, but add the warning (layered bar chart is generally a bad idea anyway.)

**Comment by kanitw** [comment]
To clarify, layered bar chart is not great, but still better than occluded bar chart (opaque layered bar chart).
