### ISSUE TITLE
Inline data is modified, and not idempotent.

### ISSUE THREAD

**Issue by mbostock** [vega/vega-lite#2131]
Say I have some inline data like this:

```js
var data = [
  {date: "24-Apr-07", close: "93.24"},
  {date: "25-Apr-07", close: "95.35"},
  {date: "26-Apr-07", close: "98.84"},
  {date: "27-Apr-07", close: "99.92"},
  {date: "30-Apr-07", close: "99.80"},
  {date: "1-May-07", close: "99.47"},
  {date: "2-May-07", close: "100.39"},
  …
];
```

Now say I pass it to Vega Lite, like this:

```js
{
  data: {values: data},
  mark: "line",
  encoding: {
    x: {field: "date", type: "temporal"},
    y: {field: "close", type: "quantitative"}
  }
}
```

This looks fine:

![image](https://cloud.githubusercontent.com/assets/230541/25012747/481b6472-2026-11e7-8662-9a8db5985734.png)

However, Vega Lite silently modified the contents of the `data` array so it now looks like this:

```js
var data = [
  {date: 1177398000000, close: 93.24, _id: 765},
  {date: 1177484400000, close: 95.35, _id: 766},
  {date: 1177570800000, close: 98.84, _id: 767},
  {date: 1177657200000, close: 99.92, _id: 768},
  {date: 1177916400000, close: 99.8, _id: 769},
  {date: 1178002800000, close: 99.47, _id: 770},
  {date: 1178089200000, close: 100.39, _id: 771},
  …
];
```

I did not expect that Vega Lite would modify the input array; at least, it does not [appear to be documented](https://vega.github.io/vega-lite/docs/data.html#inline). But what’s especially damaging here is that by overwriting the *d*.date field, it’s no longer idempotent: you can’t pass that same `data` to Vega Lite again to create a new chart.

You get this:

![image](https://cloud.githubusercontent.com/assets/230541/25012768/54c15164-2026-11e7-8a51-9ead6678b11f.png)

My preference would be for Vega Lite to make a copy of the input data before modifying it, so that the input data is unaffected. I believe it does not need to make a deep clone of the input—presumably it could just populate the fields defined in the specification (here `date` and `close`).

**Comment by kanitw** [comment]
Thank you @mbostock. 

Your comment is very timely. We actually discussed earlier this week that we will make the output Vega specification from Vega-Lite copy of the input inline data or bound data to prevent this kind of problems. :) 

cc: @jheer @domoritz

**Comment by jheer** [comment]
A couple thoughts here:
- Vega-Lite could clone data (or create derived objects, for example via `Object.create`) as part of the compilation process. Browsers are always evolving, but FWIW the last time we did significant benchmarking around this, object cloning (i.e., create a new object and bulk copy the properties over) was notably faster than `Object.create` in Chrome. In Safari we did not see a big difference.
- If instead it is acceptable to add an `_id` property to input data (but no other modifications!), Vega-Lite can simply set up a derived data source in the output Vega to separate input tuples from downstream tuples used in the visualization. Vega will then perform defensive copying if any property modifications occur, but will optimize the dataflow to avoid data duplication if no modifications occur. Adding an `_id` (and only an `_id`) property will otherwise be idempotent across Vega-Lite invocations.

**Comment by imlucas** [comment]
@jheer Along with #2371, this issue is currently blocking our upgrade from `1.x` ➡️ `2.x` :/  Neither option above will work for us sadly: 

1. We're looking at data sources with potentially 100k+ records so a clone would just be way too much overhead in the long run.
2. All of records in our data sources are MongoDB documents so the `_id` property is already in use :) 

Happy to work on a PR for to fix this issue if you wouldn't mind pointing me to the `vega-*` module these changes need to happen in. My hunch is `vega-expression`, `vega-parser`, or `vega-dataflow` but not sure. Apologies in advance if there is some existing documentation I'm missing.

cc @Danulf

**Comment by domoritz** [comment]
This is going to be addressed in https://github.com/vega/vega-lite/issues/2462. If I understood @jheer correctly, if you already have an `_id` field, as long as the values are unique, it shouldn't be a problem.

**Comment by imlucas** [comment]
@domoritz great!  thanks for the update!
