### ISSUE TITLE
Broken Query Widgets Example

### ISSUE THREAD

**Issue by jhoffswell** [vega/vega-lite#2145]
The Interactive "Query Widgets" example from the website seems to have the opposite interaction from what it claims: selecting points updates the sliders, but updating the sliders does not change the points.
![brokenslider](https://cloud.githubusercontent.com/assets/3392218/25051518/e3f4265a-2101-11e7-8484-de776db48be7.gif)

**Comment by arvind** [comment]
The [`cars.json`](https://vega.github.io/new-editor/data/cars.json) being used by the new editor is out of sync with the one found in [vega-datasets](https://github.com/vega/vega-datasets/blob/gh-pages/data/cars.json) which is what this example was built for. If we update the editor's pull of the datasets, this should be resolved.

**Comment by mathisonian** [comment]
This was fixed in vega/vega-editor#a84ebf60462d78511e8025a50bed2981cf11e0e2 and deployed. 

The datasets feel a little brittle right now, given that the specs (both vg and vl) expect data in a folder like `data/<dataset>.json`. This leads to weirdness when the vega example data (currently pulling from here https://github.com/vega/vega/tree/master/docs/data) differ from vega lite example data (currently pulled from vega-datasets) in a dataset of the same name.

**Comment by domoritz** [comment]
vega-datasets should be the single source of truth, imho. Can Vega pull from vega-datasets @jheer?
