### ISSUE TITLE
Eliminate _id reference from the Vega output

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2221]
From discussion with Jeff today, this sounds like something we have to do before the final 2.0 release.  (This is okay for beta though.)

**Comment by arvind** [comment]
As I wasn't able to participate in the discussion, some additional guidance as to why we need to eliminate `_id` and what a good alternative default could be would help me think through things.

**Comment by jheer** [comment]
The issue has to do with saving/restoring Vega dataflow state.
- `_id` is volatile: if you parse a Vega spec at a different time, you can end up with otherwise identical tuples having different _id values. If you snapshot the Vega state (signals and triggered-populated data sources, such as selections!) and try to restore it later (possibly on a different invocation of the same spec), the `_id` values may not match and the dataflow state is now corrupted.
- One possibility is to add a unique id expression function (or similar) for assigning primary key values explicitly. One could then use those values rather than Vega's **internal** `_id` values.

This is not a high priority at the moment, but down the road it would be handy for a number of reasons to have accurate state management: time-travel debugging, collaborative view sharing, etc.

**Comment by arvind** [comment]
Aah yes, I remember now. Thanks!
