### ISSUE TITLE
Revise Transform Docs

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2279]
- [ ] example spec that uses filter

**Comment by domoritz** [comment]
We already have examples at https://vega.github.io/vega-lite/docs/transform.html. Or do you mean example specs?

**Comment by kanitw** [comment]
That's true.  I wonder if example specs would be more practical

**Comment by domoritz** [comment]
Both are needed. We want many examples for the filters, and one or two specs just to show how to integrate filters.

**Comment by kanitw** [comment]
For filter, we only have short syntax examples at the end of the section, which is hard to read and a bit far from each part of the table.  

Better add examples within sub-section.  (For example, within "Equal Filter", better add an example spec with equal filter.)

**Comment by kanitw** [comment]
- For aggregate/timeunit/bin.md  
    - [ ] add examples to compare the two approaches
    - [ ] add example that bin, timeUnit, summarize transform are useful if you want to apply filtering or do additional calculation after summarizing

**Comment by kanitw** [comment]
- TimeUnit
  - [ ] Explain about default time format

**Comment by kanitw** [comment]
- [ ] Clarify what aggregate / summarize does (as compared to window).   See https://github.com/vega/vega-lite/issues/2910#issuecomment-323938460

**Comment by kanitw** [comment]
- [ ] Need to explain that filter is a logical operand structure.  Adding it to types page (https://github.com/vega/vega-lite/issues/2901) would help a bit.

**Comment by kanitw** [comment]
- [ ] Need to revise context for bin and timeUnit with ordinal type

(There is bin ordinal section already but it totally comes out of nowhere and definitely need more context. I think it should be a part of "bin in encoding" section.)

**Comment by biji-padhy** [comment]
Hey Guys, I have a vega tree structure. The values in the leaf nodes are incorrect. Please have a look at the tree:

![image](https://user-images.githubusercontent.com/46964414/55794585-37b20380-5ae3-11e9-8ee5-c139d58aa817.png)

As you see I have similar terms (Model 1, Model 2, platform etc) are quite common at the leaf node level for every parent. But when I do the calculation instead of considering only its parent node, the tree calculates on every parent wherever the particular term is available. How can I restrict the calculation to the actual parent level? I don't want the data to be mixed up!! I am using join-aggregate transform for this. Please help me with the correct approach.

{
      type: "joinaggregate",
      ops: ["average"], 
      fields: ["percentage.value"], as: ["total"],
      groupby: ["key.model_name"]
    }

Can I add any filter to find its actual parent node and take the average of that?

**Comment by kanitw** [comment]
@biji-padhy please do not ask vega questions in issues.  
1) This is a Vega-Lite repository, not Vega. 
2) Questions should be asked on Slack, Stackoverflow, or the mailing list, not in github issues.

**Comment by kanitw** [comment]
All the important stuffs are done at this point.
