### ISSUE TITLE
Push timeUnit calculations to source dataset?

### ISSUE THREAD

**Issue by arvind** [vega/vega-lite#2448]
Surfacing a Slack conversation for us to dig into further. 

Currently, point (single/multi) selections projected over binned and timeUnit fields do not work across multiview displays (#2320). @domoritz and I came up with the following strategy to deal with binned fields:
* Capture the `bin_start` and `bin_end` during the interaction.
* The `vlPoint` expression function should treat those as a range over the raw field.

A similar strategy could make sense with `timeUnit` (where `vlPoint` recalculates a `timeUnit` during the test) but has a couple of drawbacks: (1) duplicating (or at a minimum referencing) `timeUnit` logic in vega-parser; (2) performance of these recalculations.

We didn't want to push bin operations up the transform pipeline because filters could affect the binning strategy. However, I don't think such concerns affect `timeUnit`. So, would it be possible to push `timeUnit` calculations to the source dataset? I believe this would make them accessible globally, with the only danger being a user manually overriding them (something that could potentially be error-checked).

**Comment by arvind** [comment]
One option that was suggested in Slack that I forgot to describe above: generating additional `timeUnit` calculations for each view a selection is used in. This could potentially work provided: (1) we ensure these additional calculations occur before selection filters; (2) they're generated if secondary views simply use selections to drive Vega production rules and not selection filters.

**Comment by jheer** [comment]
If workable, I prefer the strategy of converting point selections in reasonable queries rather duplicating binning/timeUnit calculations across various views.

**Comment by domoritz** [comment]
As discussed on slack, @domoritz will add a method `DataFlowNode.insertBefore(node: DataFlowNode)`. @arvind will use this method when parsing selections to add a time unit node into the dataflow. Moreover, he will add a time unit node when we are parsing selection filters.

**Comment by domoritz** [comment]
Added method to add node in https://github.com/vega/vega-lite/pull/2549

**Comment by kanitw** [comment]
> If workable, I prefer the strategy of converting point selections into reasonable queries rather than duplicating binning/timeUnit calculations across various views.

It seems like the solution that @domoritz and @arvind are pursuing actually duplicates binning/timeUnit calculations across various views.

@jheer  -- when you say reasonable queries -- do you mean having a predicate that calculates timeUnit on the fly and check? 

To respond to the same thread on slack:

> Arvind: Oh ok, so it’d have to be separate code paths for selection filters and conditional encodings?
> Dom: Yes, I think so. But hopefully, you can extract the common logic into a function that gets called from two different places. I don’t think we can really avoid this since conditional encodings and transforms are parsed in different locations.

I guess if we choose to produce a predicate instead we could use a shared code path?

If I remember correctly, you guys prefer adding timeUnit node because it's better for performance right?  (Just wanna make sure if I understand the rationale correctly.)  
Also, wanna jot down here that timeUnit can be extracted up there because filtering doesn't change output of timeUnit (like filter does for bin).  

A bit tangential but somewhat related comment -- it seems like in longer term we have to track dependencies between transform to throw warning for invalid state.  
For example, if we have a `transform` array that first `summarize` data and the apply selection filter that is based on a selection that  projects on a field with timeUnit.  Suppose the summarize does not group by the timeUnit field, then we will produce an invalid state.   (This is a rare case though so I don't think it's critical to include warning in 2.0)

**Comment by domoritz** [comment]
The reason to add a node is that we can optimize it later by deduping dataflow nodes.

**Comment by kanitw** [comment]
Ok.  I'm fine either way.

**Comment by domoritz** [comment]
@arvind Can we close this?

**Comment by arvind** [comment]
Once #2591 is merged, yes!
