### ISSUE TITLE
Check occurences of isBinScale

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2493]
Since the rationale for https://github.com/vega/vega-lite/pull/2492 is that bin scale does not work with selection, we should revise `isBinScale` calls inside `src/compiler/selections`.  (There are still some references.)

**Comment by domoritz** [comment]
I looked over them and it seemed like they were there to prevent selections over bin scales. So it all seems correct.

However, I wonder whether those checks are necessary since we will never have bin scales for x and y.

**Comment by arvind** [comment]
Yes! Thanks to #2492, interval selections now work when x/y is binned. However, I would prefer to leave the `isBinScale` checks in place because the conditions they test for still hold -- our strategy for panning, zooming, and reacting to scale changes will not work with binned scales. Keeping the checks in place seems more future proof to me -- e.g., if we enable brushing a binned color legend in the future.

**Comment by kanitw** [comment]
Sounds good.  (I only filed this issue to make sure they are still correct :))

**Comment by arvind** [comment]
Agreed, it was good to re-check those assumptions. And as a result, I found two bugs: I inadvertently deleted a ternary branch for the `isBinScale` condition and, more problematically, #2492 broke the cross filter example revealing that it is currently possible to specify an infinite loop with our selections. Need to think on how to resolve that.

**Comment by kanitw** [comment]
Ok i'll re-open this for now then.
