### ISSUE TITLE
Facet labels are mismatched.

### ISSUE THREAD

**Issue by yhoonkim** [vega/vega-lite#2553]
![image](https://user-images.githubusercontent.com/6269456/27410285-7ce73c8e-569b-11e7-9595-65977736eda3.png)

```json
{
    "data":{
        "values": [
            {"f1":"LL","f2":"A","f3":"L","f4":"++"},
            {"f1":"HM","f2":"C","f3":"H","f4":"-"},
            {"f1":"ML","f2":"C","f3":"L","f4":"-"},
            {"f1":"LM","f2":"B","f3":"X","f4":"-"}
        ]
    },
    "mark": "point",
    "encoding": {
        "x":{"field": "f1", "type": "nominal"},
        "y":{"field": "f4", "type": "nominal"},
        "row":{"field": "f3", "type": "nominal"},
        "column":{"field": "f2", "type": "nominal"},
        "size":{"field": "*", "aggregate":"count", "type": "quantitative"}
    }
}
```
As you can see, labels on `row` and `column` are incorrect. C should be swapped with B, and  H should be swapped with L.

**Comment by kanitw** [comment]
Thanks for reporting, I believe the root cause is that mark group's `sort` is only generated for the main "cell", but not to row/column header & footer, which is generated [here](https://github.com/vega/vega-lite/blob/master/src/compile/layout/header.ts#L121).  

@yhoonkim  Do you want to give a shot fixing this?  (Maybe start from producing a correct Vega spec first -- modifying VL code for this shouldn't involve to many lines.)
