### ISSUE TITLE
LaTeX text

### ISSUE THREAD

**Issue by nipunbatra** [vega/vega-lite#2640]
Hi,
I was wondering if it would be possible to include LaTeX text for the charts. Maybe, can leverage MathJax for the rendering?
I'm happy to help if pointed in the right direction.

**Comment by domoritz** [comment]
Vega-Lite compiles to Vega so we would need to support this in Vega. However, since Vega supports different renderers, including canvas, we would need to implement a method for displaying Latex in canvas. Is there an easy way to do that?

Please file an issue in the Vega repository directly, if you think this is feasible.
