### ISSUE TITLE
Multiple selection intervals has inconsistent behavior on initial interactions

### ISSUE THREAD

**Issue by leibatt** [vega/vega-lite#2696]
From the [Composing Multiple Selections](https://vega.github.io/vega-lite/docs/selection.html#composing-multiple-selections) in the Selection doc.

When I first start interacting with the visualization, the "and" behaves like "or" when only one interval is first drawn.

```
{
  "data": {"url": "data/cars.json"},
  "selection": {
    "alex": {
      "type": "interval",
      "on": "[mousedown[!event.shiftKey], mouseup] > mousemove"
    },
    "morgan": {
      "type": "interval",
      "on": "[mousedown[event.shiftKey], mouseup] > mousemove",
      "mark": {"fill": "#fdbb84", "fillOpacity": 0.5, "stroke": "#e34a33"}
    }
  },
  "mark": "rect",
  "encoding": {
    "y": {"field": "Origin", "type": "ordinal"},
    "x": {"field": "Cylinders", "type": "ordinal"},
    "color": {
      "condition": {
        "selection": {"and": ["alex", "morgan"]},
        "aggregate": "count", "field": "*", "type": "quantitative"
      },
      "value": "grey"
    }
  }
}
```

When I first start interacting with the visualization, "or" doesn't highlight anything when only one interval is first drawn.

```
{
  "data": {"url": "data/cars.json"},
  "selection": {
    "alex": {
      "type": "interval",
      "on": "[mousedown[!event.shiftKey], mouseup] > mousemove"
    },
    "morgan": {
      "type": "interval",
      "on": "[mousedown[event.shiftKey], mouseup] > mousemove",
      "mark": {"fill": "#fdbb84", "fillOpacity": 0.5, "stroke": "#e34a33"}
    }
  },
  "mark": "rect",
  "encoding": {
    "y": {"field": "Origin", "type": "ordinal"},
    "x": {"field": "Cylinders", "type": "ordinal"},
    "color": {
      "condition": {
        "selection": {"or": ["alex", "morgan"]},
        "aggregate": "count", "field": "*", "type": "quantitative"
      },
      "value": "grey"
    }
  }
}
```

**Comment by arvind** [comment]
Thanks @leibatt. This seeming inconsistency is occurring is because, currently, all data values are considered part of an empty selection (#2321). I'm working to introduce a new property to toggle this behaviour. With this new property, if the two selections above are marked `"empty": false` (i.e., empty selections contain _no_ values rather than _all_ values), the behaviour is as follows:
* Rectangles remain grey until both brushes are drawn for the `and` case.
* Rectangles immediately highlight with the first brush for the `or` case.

One open question, however: when selections are composed, should we _always_ treat empty selections as containing no points? 

Pros: 
* The behavior is more consistent on first interaction. 

Cons: 
* Rectangles are grey on first render (rather than colored, as would be with just one/uncomposed selection).
* The `empty` property would essentially be ignored. 

Thoughts? /cc @jheer, @kanitw, @domoritz.

**Comment by kanitw** [comment]
> should we always treat empty selections as containing no points?

> The new `empty` property would essentially be ignored.

I wonder if we should frame the question to be what should be the default value for `empty`.
This way we can still make `empty`  customizable?  

For example, we could say `empty`  is `true` by default but users can override and make it `false`.   (We could even add `config.selection.empty` to determine the default `empty` property, just in case users want to customize "empty" for the whole plot.)

Btw, I feel that `empty: true/false` is not very clear that it defines the underlying data for the selection.  I wonder if `empty: 'all' | 'none'` or something along this line would be clearer.

**Comment by arvind** [comment]
Sure, a customizable `empty` property is what I described above. My question, however, was specifically about when selections are _composed_. I agree that `empty` should be `true` (or whatever equivalent we decide on, because I agree `true` and `false` are unclear). However, when selections are composed, this default value leads back to the source of the consistency that generated this issue. 

Ergo, should predicate functions that are composed together default to `empty: false`? If so, are we ok with the pros/cons listed above (with a third that I just added)?

**Comment by jheer** [comment]
If it is possible to resolve the issue without increasing the surface area of the language with a potentially hard-to-understand configuration option that would be nice. For the sake of comprehensiveness, here is one potential alternative:

1. Selections are not configurable. Empty selections are treated as null sets and follow standard set logic (empty _and_ non-empty -> null, empty _or_ non-empty -> non-empty).
2. To avoid the aforementioned issues we instead focus on how selections are initialized. For example, an interval selection may start with the full scale domain selected. The initial range can also be explicitly set by spec authors.

(I'm not necessarily advocating for this, but am trying to think broadly first!)

Here's another possible setup (I think this is similar to what @arvind proposes, but not identical):

1. An empty selection is treated as "select all" if and only if *all* participating selections are empty. Consider operations over two selections. In the case of _and_, all data may start selected, but would be unselected as soon as one defines one selection but not yet the other. In the case of _or_, the selection would consist of just the interactively selected data as one defines one selection but not yet the other.

**Comment by gampleman** [comment]
I'm working on a crossfiltering sort of dashboard containing several plots each with its own brush. When I make a brush selection in one of the plots, I want all the other plots filtered by the intersection of the brushes. For this `and` works well. But if there is not a brush selection, I don't want to filter the dataset by that dimension at all. If I understand correctly, that was the previous behavior?

Is there a workaround I can employ?
