### ISSUE TITLE
remove cell's default gray border

### ISSUE THREAD

**Issue by g3o2** [vega/vega-lite#2781]
Since recent vl builds, the cell's surrounded by a gray border, which one has to remove via `config.cell.strokeWidth`. I'm not sure it is considered best practice to surround any plot by a border.

**Comment by kanitw** [comment]
Since we enable grid by default, I add the frame border by default too so that the plots look balanced when the grids do not have close ends.  

Otherwise, we get something like these:

![vega_editor](https://user-images.githubusercontent.com/111269/28900000-d6b85496-77a2-11e7-9bce-176aab047d55.png)

![vega_editor](https://user-images.githubusercontent.com/111269/28900010-f049c9b2-77a2-11e7-8ff7-3eea99d4a397.png)

which look pretty imbalanced IMHO.

Tableau, for example, also adds similar border.  

![image](https://user-images.githubusercontent.com/111269/28997966-e6c1f664-79d5-11e7-8a39-7f6b61837f66.png)

**Comment by g3o2** [comment]
Regarding grids, let me quote [Edward Tufte](https://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=00040Z):

> The grid should usually be muted or completely suppressed so that its presence is only implicit - lest it competes with the data. Grids are mostly for the initial plotting at home or at office rather than for putting into print.

Tufte uses lightgray frame borders for small multiples (`facet`, `concat`) but for `layers` and stand-alone graphs such borders carry no esthetic function.

**Comment by kanitw** [comment]
Thanks for your comment.  However, I don't think we are completely conflicting with Tufte. 

> that its presence is only implicit - lest it competes with the data

Our grid are pretty muted.

> Grids are mostly for the initial plotting at home or at office rather than for putting into print.

We are designing for analysis (by default) more than for print and users can still customize for print. 

---

More importantly, here we design a system that users can compose composite plots from a single unit plot.  We can't design a system where when users compose plots with `facet` / `concat` and grids then suddenly appear although it does not appear for single view plot.  That will confuse a lot of users.

**Comment by g3o2** [comment]
Thanks for the discussion. I fully agree with your argumentation. Plus, I can always remove the frame border myself.

**Comment by kanitw** [comment]
@g3o2   Thanks for your comment too :)
