### ISSUE TITLE
example `Repeat and layer to show different weather measures` does not work in editor

### ISSUE THREAD

**Issue by g3o2** [vega/vega-lite#2844]
link to example [Repeat and layer to show different weather measures](https://vega.github.io/editor/#/examples/vega-lite/repeat_layer)

**Comment by domoritz** [comment]
It renders fine for me. Please reopen with specific instructions and a description of what doesn't work. Thanks!

Maybe this was a transient error because we recently updated the editor. 

<img width="1051" alt="screen shot 2017-08-12 at 10 43 42" src="https://user-images.githubusercontent.com/589034/29243057-34d92992-7f4b-11e7-9203-dface5f72892.png">

**Comment by g3o2** [comment]
Please take a look here (screenshot taken from within Safari browser):

![screenshot](https://user-images.githubusercontent.com/12123506/29249314-4e6371be-802d-11e7-871e-b7984b96f57a.png)
