### ISSUE TITLE
Is autosize really in config?

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3025]
https://vega.github.io/vega-lite/docs/config.html#top-level-config

cc @znation

**Comment by kanitw** [comment]
You can either remove it from config or make compile.ts read it?

**Comment by domoritz** [comment]
Okay, I'm trying to understand why we have top level properties and config. I vote that we either only have top level configs or only have the properties in config. My vote is for moving them to config. 

Currently, we have `padding`, `autosize`, and `background`. `width` and `height` should stay top level properties because they can be used in children as well.

**Comment by kanitw** [comment]
I think they _definitely_ should stay as top-level properties as config should be really for theming.  

The reason they are in both because these properties can be considered as a theme as well.  
(Users should be able to customize them directly at the top-level, but they should be able to provide a `config` object for many of their visualizations.)  Note that I just notice that we didn't have `config` as a parameter of the `compile` method anymore.  We should change that.

**Comment by domoritz** [comment]
> Note that I just notice

Noted

**Comment by domoritz** [comment]
In #3028
