### ISSUE TITLE
Support multiple conditions in an encoding (if/else/else...)

### ISSUE THREAD

**Issue by pelotom** [vega/vega-lite#3040]
Correct me if I'm wrong, but it seems like currently an encoding can only take one of at most two branches, based on a single condition:

```json
{
  "color": {
    "condition": { "selection": "focused", "value": "red" },
    "value": "blue"
  }
}
```

but it would be nice if one could check multiple conditions until one succeeds, e.g. something like

```json
{
  "color": [
    { "condition": { "selection": "focused", "value": "red" } },
    { "condition": { "selection": "pinned", "value": "green" } },
    { "value": "blue" }
  ]
}
```

**Comment by kanitw** [comment]
You're right, currently we intentionally support only two branches, so that we can limit that one encoding channel can have only one `field`.  

That said, it is possible to extend the design to have multiple branches with different `value`s -- as long as there is only one `field` for each encoding channel (relaxing the latter constraint introduce way more complexity to the system and is definitely not worth supporting).   

I could see it work with the following syntax: 
```
{
  "color": {
    "condition": [
       { "selection": "sel1", "value": "red" },
       { "selection": "sel2", "value": "green" },
    ],
    "value": "blue"
  }
}
```
where the `condition` array can only be a [ConditionValueDef](https://vega.github.io/vega-lite/docs/condition.html#value). 

However, we haven't prioritized it since we have not found an example visualization that would really need this.  If you have a convincing use case, please feel free to submit one. 

For example, If you have a clear use case to have "pinned" data and "focused" data, please feel free to describe.

**Comment by pelotom** [comment]
That syntax looks good to me.

Ok, let me describe my use case. I want the user to be able to hover the mouse over various elements in the chart, whereupon they will acquire a "focused" effect... maybe in a scatterplot they become slightly larger than the other points, for example. Then if the user clicks on an element it becomes "pinned", at which point it becomes even more emphasized... maybe in addition to being larger than the other points it acquires a red color, for example. Now as the user hovers over other items they acquire the focus effect, _but not the pinned effect_, so that it's clear that the old element is still pinned, whereas the things they are hovering over are only transiently focused and _potentially_ pinnable. This chart might be accompanied by an external details view which listens only for "pin" events and shows details about the pinned element, so it needs to be clear which element that view is referring to.

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/3146 (pending review)
