### ISSUE TITLE
Selections don't like signal references as their event stream

### ISSUE THREAD

**Issue by djahandarie** [vega/vega-lite#3090]
If you have a selection like follows...

```javascript
"selection": {
	"current": {
		"type": "single",
		"on": {"signal": "newCurrent"},
		"fields": ["index"]
	}
}
```

the following vega spec gets generated:

```javascript
signals: [
// ...
   {
      "name":"current",
      "update":"data(\"current_store\").length && {index: data(\"current_store\")[0].values[0]}"
   },
   {
      "name":"current_tuple",
      "value":{},
      "on":[
         {
            "events":{
               "signal":"newCurrent"
            },
            "update":"datum && item().mark.marktype !== 'group' ? {unit: \"layer_0\", encodings: [], fields: [\"index\"], values: [datum[\"index\"]]} : null",
            "force":true
         }
      ]
   },
   {
      "name":"current_modify",
      "on":[
         {
            "events":{
               "signal":"current_tuple"
            },
            "update":"modify(\"current_store\", current_tuple, true)"
         }
      ]
   },
   {
      "name":"newCurrent",
      "value":0
   }
]
```

The `update` expression for `current_tuple` expects `datum` to be set (which it isn't, it's undefined), and `item()` to work (which it doesn't), and for the value to be stored in `datum[field_name]` (which it doesn't).

If I manually hack in the following `update` expression, it works as I would expect:
```javascript
newCurrent ? {unit: "layer_0", encodings: [], fields: ["index"], values: [newCurrent]} : null
```

I'm not sure if I'm just "doing it wrong" and there's some other way I'm suppose to be using the signal in as an event stream, but I think this is probably a bug?

**Comment by arvind** [comment]
Thanks for the question @djahandarie! Signals are a Vega (not Vega-Lite) construct -- i.e., you cannot define a signal within a Vega-Lite specification and thus, a signal reference in Vega-Lite is undefined/invalid. The majority of selection event handling logic is driven by the context set by actual DOM events. For these reasons, I do not think we will support referencing Vega signals within Vega-Lite selections in the near term. 

Were we to introduce signals within Vega-Lite, we may want to consider their impact on selections. But I would be strongly against such a change since it would be breaking the Vega/Vega-Lite abstraction barrier.

**Comment by mstone** [comment]
@arvind,

Thanks for this helpful reply; I also share(d) @djahandarie’s confusion due to https://vega.github.io/vega-lite/docs/selection.html indicating that a selection’s “on” property is a “Vega Event Stream”, and linking to https://vega.github.io/vega/docs/event-streams/ (which further suggests that event streams can be defined via Vega signal references).

As a result, I have two followup documentation questions (which i ask only because the rest of the Vega-Lite documentation is so good):

a) is there something I could have read in order to know that signals are a part of the Vega model that is intentionally not a part of the Vega-Lite model (given that many other Vega-Lite concepts seem to be abstracting parallel concepts in Vega, like marks)?

b) more tactically, is there some way to clarify the documentation of the Vega-Lite selection’s “on” property to better communicate what is settings are supported (perhaps, e.g., by adding the word “**only**” to the parenthetical about what kinds of event stream descriptors are allowed)?

Thanks again!

Michael
