### ISSUE TITLE
Better support for re-using inline data in a complex composite plot

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3116]
(Conversation from Altair Hackathon)

**Comment by domoritz** [comment]
The result from that conversation was that we could add a top-level `storage` property that is a dict from name -> values. When we assemble named data sources, we can look up the values and add them. Since we always have each named data source only once, we will never put duplicates in the generated vega. 

The last question is whether large Vega specs are ever a problem.

**Comment by kanitw** [comment]
I think the idea of having named data sources at the top-level sounds reasonable. 

That said, I don't like `storage` as the name of the key yet as it is not clear it is "storage of data". 

I wonder if other keys such as `datasets` or `dataSources` are actually clearer.

**Comment by domoritz** [comment]
I like `datasets`.

**Comment by kanitw** [comment]
Actually, most of our top-level keys are not plural though (`selection` is singular).  So maybe just `dataset`?
