### ISSUE TITLE
Transformation in Horizon chart example is redundant

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#3184]
In the Horizon Chart example, the transformation for the first layer (the 'far' horizon) is not used so can be eliminated from the spec:

    "transform": [
      {
        "calculate": "if(datum.y <= 50, datum.y, 50)",
        "as": "ny"
      }
    ]

Indeed, if it were to be applied (using `ny` rather than `y` in the y-position encoding) it would incorrectly round rather than truncate the far horizon.

**Comment by jwoLondon** [comment]
You may also wish to add

     "orient": "vertical"

to the `area` spec in `config` in order to stop the warning about not being able to determine the orientation for area (even though the default is vertical anyway).

**Comment by domoritz** [comment]
The warning about the orientation is there because the rules we have added to the compiler cannot determine what the orientation of the area mark is and so it uses the default. I think we should figure out why this warning is shown and make sure that the compiler can determine the orientation correctly.

**Comment by kanitw** [comment]
@domoritz It's a QxQ plot, so the warning totally makes sense

@jwoLondon Good catches.  Thanks for commenting! This will be fixed in #3188. 
Feel free to submit a PR to help us fix in the future. :D
