### ISSUE TITLE
Sudden drop at the end of the year in wikipedia chart

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3298]
See https://bl.ocks.org/domoritz/bef687de0e2dba1f522f674c260ac17f

<img width="76" alt="screen shot 2018-01-23 at 20 39 50" src="https://user-images.githubusercontent.com/589034/35314842-a802f174-007d-11e8-8c8a-5709a5935e44.png">

This is not a Vega-Lite issue but an interesting debugging exercise to get familiar with Vega-Lite and Vega. (e.g. use `VEGA_DEBUG.view.data('source_0')` to look at the data)

**Comment by kanitw** [comment]
I think people won't understand what's the problem with this.  (I don't.)

**Comment by domoritz** [comment]
If you switch to point, you can see that there are data points with low values at the end although it's supposed to to be a running sum.

**Comment by kanitw** [comment]
So what's the actionable item here?

**Comment by domoritz** [comment]
Investigate why this is broken. Is it the data or something in Vega-Lite about time handling (UTC etc).

**Comment by dbautistav** [comment]
At first I didn't understand what was the issue here but after reading the conversation twice and playing a little bit with [the code](https://bl.ocks.org/domoritz/bef687de0e2dba1f522f674c260ac17f) in the [vega editor](https://vega.github.io/editor), I did.


### The issue

I removed the line `"$schema": "https://vega.github.io/schema/vega-lite/v2.json",` and also changed `"mark": "line",` to `"mark": "tick",` then I clearly saw the issue: December values for some years appeared so close to zero which led to the impression that the values suddenly dropped at the end of the year.

Then following @domoritz's hint, I searched for `VEGA_DEBUG.view.data('source_0')` on Internet and found this useful article: ["Debugging Vega Graphs"](https://www.elastic.co/guide/en/kibana/current/vega-debugging.html) (clearly I didn't know then about [debugging Vega visualizations at runtime](https://vega.github.io/vega/docs/api/debugging)). So after opening the debug console for the online editor tab and executing `VEGA_DEBUG.view.data('source_0')` on it I was able to inspect the main dataset and found that its first entry had these values:

```
    ...
    max_ytdsum: 250,
    monthdate_date: Sun Dec 30 1900 00:00:00 GMT-0600 (Central Standard Time),
    year_date: Mon Jan 01 2007 00:00:00 GMT-0600 (Central Standard Time)
    ...
```

It came to my attention that `monthdate_date` was located back in 1900 while `year_date` appeared located in 2007. So I [downloaded the original data source](https://frdata.wikimedia.org/donationdata-vs-day.csv) (the CSV file defined at `data.url` in the specification) and opened it in my local text editor. Then I found that the corresponding entry was:

```
    date,ytdsum,donations,ytdloss,refunds,max,sum,avg,refund_sum
    2007-12-31,250.0,1,0.0,0,250.0,250.0,250.0,0.0
```

So I went to the [Vega-Lite docs](https://vega.github.io/vega-lite/docs) to know more about the date/time syntax (specially formatting) and I found that as the `date` field [values were strings without time then they were interpreted as UTC](https://vega.github.io/vega-lite/docs/timeunit.html#utc).


### The solution

Specification changes:

```diff
  {
-      "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
      "data": {
          "url": "https://frdata.wikimedia.org/donationdata-vs-day.csv",
          "format": {"type": "csv"}
      },
      "width": 600,
      "height": 300,
      "mark": "tick",
      "encoding": {
          "x": {
              "field": "date",
              "type": "temporal",
-              "timeUnit": "monthdate",
+              "timeUnit": "utcmonthdate",
              "axis": {"format": "%B", "title": "Month"}
          },
          "y": {
              "field": "ytdsum",
              "type": "quantitative",
              "aggregate": "max",
              "stack": null,
              "axis": {"title": "Donations Till the Beginning of the Year"}
          },
          "color": {
              "field": "date",
              "type": "ordinal",
-              "timeUnit": "year",
+              "timeUnit": "utcyear",
              "legend": {"title": "Year"}
          },
          "order": {"field": "date", "type": "ordinal", "timeUnit": "year"}
      },
      "config": {}
  }
```

The solution was changing `encoding.x.timeUnit` value from `monthdate` to `utcmonthdate` and `encoding.color.timeUnit` from `year` to `utcyear` so Vega-Lite could properly parse and format `date` values for all dataset entries.

The **final result now** is:

<img width="680" alt="vega editor" src="https://user-images.githubusercontent.com/8743976/44616619-b38f6200-a818-11e8-8235-1d4048d8d174.png">


And that's it.

**Comment by domoritz** [comment]
Thank you for debugging it and writing up the path you took. I'll correct the example accordingly.

**Comment by domoritz** [comment]
@dbautistav I fixed the example and credited you for fixing the date parsing.
