### ISSUE TITLE
Document & unhide stack transform

### ISSUE THREAD

**Issue by g3o2** [vega/vega-lite#3311]
- [ ] improve diverging stack bar example

Recently, I wanted to reuse this [example](https://vega.github.io/vega-lite/examples/bar_diverging_stacked.html) only to realize that its dataset appears to have undergone some preprocessing outside of vega-lite, thus rendering the example theoretical in a pure vega-lite context. 

The fields in question are `percentage_start` and `percentage_end`. I can see how to calculate those two fields in vega using the `stack` transform. 

But is it currently feasible at all to calculate the said fields using only vega-lite? Alternatively, would it be possible to showcase this example using vega-lite's `layer` and `stack` instead?

```javascript
{
        "question": "Question 1",
        "type": "Strongly disagree",
        "value": 24,
        "percentage": 0.7,
        "percentage_start": -19.1,
        "percentage_end": -18.4
}
```

**Comment by kanitw** [comment]
> is it currently feasible at all to calculate the said fields using only vega-lite?

Not yet but we're working on supporting [`window`](https://github.com/vega/vega-lite/pull/3199) transform and [offset](https://github.com/vega/vega-lite/issues/396) so we can do it. 

> Alternatively, would it be possible to showcase this example using vega-lite's `layer` and `stack` instead?

I don't think `layer` would help as you still have to offset the position anyway.

**Comment by kanitw** [comment]
Actually, depending on how we implement scales for offset channels, it might lead to [a problem with scale](https://github.com/vega/vega-lite/issues/396#issuecomment-335976164).

Adding an explicit `stack` transform and window is sufficient as we can just `calculate` the offset.  (We don't really need offset for this example.)

**Comment by g3o2** [comment]
I've thought more about layering the way you would with an age pyramid. One column would have to be multiplied by -1. Hmm, I'll give it a try ...

**Comment by g3o2** [comment]
Just realized that I've already gone that road with #396 ...

**Comment by kanitw** [comment]
I'm updating this issue to be "Add stack transform and update diverging stack bar example"

**Comment by kanitw** [comment]
- [ ] Actually besides diverging stack bar example, we could try to use stack transform to replicate stack labels as in https://vega.github.io/vega/examples/job-voyager/.

**Comment by kanitw** [comment]
Another good example to add once we have a is a [mosaic plot](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&uact=8&ved=0ahUKEwjU0bSp6o3bAhUq6IMKHbI6BkoQFggxMAI&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FMosaic_plot&usg=AOvVaw3CqkSB7GLkBlMJVN3eMwf1).  

Basically, we can stack one direction first, and then stack by another direction within each group.  
Then we can use rect mark for each plot. 

Here is another [similar example](http://data-illustrator.com/example.php?v=gender-job-level).

**Comment by kanitw** [comment]
We got some questions about motivation and other alternatives for this issue on Slack.  Here are some more details. 

For stack, it is the only transform in encoding that does not have an explicit version of the syntax available so it is inconsistent with the rest of the language. (I just found out that I noted about it in https://github.com/vega/vega-lite/issues/3264, not here -- sorry!)  

> re: alternative approaches such as augmenting our existing stacking, etc.

I don't think augmenting existing stacking with offset is a good idea, as that will be complecting the design (stacking and offset are two distinct operations). 

Another good alternative is to offer `offset` as discussed in https://github.com/vega/vega-lite/issues/3047 (Too bad we have duplicate issues, so some of you might not notice it). But adding offset doesn't solve the inconsistency problem anyway.  It also doesn't allow multi-direction nested stack like in Mosaic plot. 

While I don't think this issue is critical, implementing it is a great exercise for @invokesus  to understand how transform codebase works in VL as there is already a StackNode in the data component. With this knowledge, he can continue implement other more important data transform for his GSOC project like fold, flatten, density, sample, etc.

(Please comment what you think are worth implementing in https://github.com/vega/vega-lite/issues/3264. -- We can also talk about in person once we resume our regular VL meetings.) 

Given this rationale, what we have explored alternatives is the syntax for it.  @invokesus actually has created [a design document for the syntax](https://docs.google.com/document/d/1ShhB_BiS3QReBLHhoStPBuN60M0rqUey5VG0AD0pT_M/edit.  ). (Yeah, I forgot to tell him to add this link here.) 

> Stack bridges data/visual space, and so exposing it as a transform feels like we are overusing transforms as an escape hatch

This point is interesting.  So today I think and read more about other “visual layout” transform.  

One important distinction between `stack` and visual layout transform is that `stack` only operates in the data domain.  It does not takes width/height as input and does not output x/y pixel values. 

In contrast, visual layout transforms (e.g., treemap, wordcloud, etc.) take width & height as input and output x/y pixel values.  

Thus, while stack feels “visual”, I wouldn’t categorize it as a visual layout transform (or at least, it is not the same kind of transform as treemap/wordcloud).
