### ISSUE TITLE
Signals in Vega-Lite

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3338]
It would be great to have basic support for signals in Vega-Lite. This could be used to implement a rotating earth as in https://beta.observablehq.com/@domoritz/rotating-earth. Another example would be to define the colors of marks via a signal.

To implement this, we need to add signal support to the types and fix resulting bugs. Also, as we parse the spec, we need to collect signals and create definitions at the top. 

While this is exciting, we want to be very careful about the design. We don't want to break abstractions or introduce multiple ways to do the same thing. @arvind suggest that we look into how we can extend single selections to support this use case.

**Comment by kanitw** [comment]
I would like note my opinion that we should definitely have a way to define the underlying `signals` in Vega, but whether we call it – I'm not sure yet.

**Comment by metasoarous** [comment]
I'd motion for sticking with the vega precedent on this one, FWIW. The notion of signal in the FRP world is connected, so it resonates with me.

**Comment by domoritz** [comment]
> The notion of signal in the FRP world is connected, so it resonates with me.

Could you elaborate? I'm not sure I understand.

**Comment by kanitw** [comment]
I'm not sure if we will have full-blown signal support throughout the language.  (like that they can be used via expression like in Vega.) 

A simpler and more common use cases to implement is for binding a property to a signal that can be bound.   But if only support a subset, it's unclear if we want to name it similarly.

**Comment by metasoarous** [comment]
> But if only support a subset, it's unclear if we want to name it similarly.

That makes sense. In general I support vega-lite encapsulating as much of the power of vega as it reasonably can without sacrificing simplicity, but I also recognize it's a challenging optimization problem, and commend you on your success. On that, I'd like to share that I've been a long time ggplot user, and had never found anything that matched it at its sweet spot, but vega-lite 2 now blows it out of the water as far as I'm concerned, so thank you for all your great work!

> Could you elaborate? I'm not sure I understand.

In the Reactive Functional Programming world writ large, there is a pattern emerging around the notion of reactive signals. In Elm they're literally called signals, and I think Redux calls them signals as well. In Reagent (ClojureScript) they're called reactions, but we sometimes talk about them as signals abstractly. To the best of my understanding (as someone who is really just starting to dig in deeply) Vega's notion of a signal at least somewhat corresponds to that of FRP.

**Comment by domoritz** [comment]
> Vega's notion of a signal at least somewhat corresponds to that of FRP.

Absolutely! In fact, we wrote a paper about the reactive architecture behind Vega: https://idl.cs.washington.edu/files/2015-ReactiveVega-InfoVis.pdf.

**Comment by jheer** [comment]
Thanks @metasoarous! And yes, the use of signals in Vega (both the name and the semantics) was directly influenced by FRP!

**Comment by king612** [comment]
+1 on signal support in vega-lite.  that would be awesome.

Forgive the noob question, but in the meanwhile, couldn't I do my own poor man's implementation and  just render my own signal controls, catch their events, and manually tweak the spec appropriately and then just re-parse?  Could get ugly, I realize, but for simple stuff like hide/show a line on a multiline chart, this should be doable, right?

**Comment by domoritz** [comment]
Yes, you could probably hack this. If you only want to switch between a few states, it probably makes sense to cache them. 

Another option is to post-process the generated Vega with some code that changes the JSON spec.

**Comment by mattijn** [comment]
This issue also counts for setting another field for coloring?
Like here: https://vega.github.io/vega-lite/docs/bind.html#input-element-binding
I can select the type within a field, but how to change the field (for example from `Cylinder` to `Year`) using a `bind input select`?

**Comment by kanitw** [comment]
Following the thread on Slack, here are some more thoughts about this: 

Signals are simply reactive variables.  They are commonly used to (a) declare parameters and calculate dependent parameters and (b) capture input events to trigger selections. 

For the latter case, the `selection` abstraction serves the purpose quite well without requiring users to declare so many underlying signals. 

However, `selection` is more than just reactive variables as it's dealing with an underlying data query (rather than just a simple scalar value that a parameter typically needs). Thus, `selection` is beyond what signal is for in the use case (a).  

As discussed [above](https://github.com/vega/vega-lite/issues/3338#issuecomment-373798447), I didn't know if we want full-blown signals support and wondered if we need a higher-level primitives. However, introducing new primitives would also require a different wrapper APIs (like we need with selection).  If we were to support this at all, I think we should just keep the name consistent. 

Note that I'm not sure if (a) and (b) are the only two common use cases of signals.
Please feel free to comment on this thread if you have other use cases.

**Comment by ijlyttle** [comment]
To build off of the two use-cases, I see @domoritz' rotating-globe as being part of (a); there is some parameter that we want to make reactive - I would like to be able to do this more easily and robustly.

For case (b), I would like to be able to provide my own html inputs (such as the [ones provided by Shiny](http://shiny.rstudio.com/gallery/widget-gallery.html)) and bind them to selections, instead of Vega providing the input-element. I would like to be able to provide default values in the spec for such selections, so that I can design the chart without the input present. 

Could it be possible to define a selection with a "bring your own input"? To push the question further, could we define a range selection where an input provides both the lower and upper end of a range? 

In both scenarios, I assume that I would be responsible for accessing the view to update the signals (which is fine by me).

**Comment by king612** [comment]
This is similar to a feature I've been requesting where a selection signal
could simply be declared with a default starting value.  That would seem to
be a fairly easy lift and require no more manual manipulation of the signal
by the spec.

My use case is simply this:  on the timeline overview-detail pattern, where
a timeline at the bottom has a brush selection interaction that allows the
detail chart at the top to be zoomed and panned, there is no way to set a
starting range for the brush selection.

John K.

**Comment by kanitw** [comment]
@king612 - your use case will be supported once #4139 is merged and released.

**Comment by kanitw** [comment]
Expanding the conversation above:

> Signals are simply reactive variables. They are commonly used to (a) declare parameters and calculate dependent parameters and (b) capture input events to trigger selections.

From #4423, another use case (c) is to use `signal` to define custom expression.
We may not really care about reactive signals in this case, but in Vega we use `signal` to define arbitrary expression as well.

**Comment by volkanunsal** [comment]
I need to bind an event handler to an interaction in Vega Lite. Is there another way besides signals that I can do this? Or do I need to throw out Vega Lite and just use Vega?

**Comment by domoritz** [comment]
@volkanunsal You can always connect to the signals that are created in the generated Vega. You can still use Vega-Lite!

**Comment by mpickering** [comment]
Am I understanding correctly that this is the necessary feature to toggle dynamically between the three different `stack` options? All that is needed to change between the three different stacked area charts is to modify the `stack` attribute to either `zero`, `normalize` or `center` but it doesn't appear possible to easily implement this given the current API.

**Comment by domoritz** [comment]
Yes, but you can use the `patch` property of Vega-Embed to add a signal for your specific purpose. We hope to have a cleaner API in the future.

**Comment by mattijn** [comment]
@domoritz, I tried using this `patch` method in veg-embed and setting signals into vega-lite compiled vega for `transform` and `init` options, but I can't get (n?)either of them to work. 

See observable notebook https://observablehq.com/@mattijn/vega-lite-experiment-signal-patch-and-external-inputs for some use-cases that hopefully one day will be supported. Or even better, my approach is wrong and it already works.

(btw `vega-embed@4` doesn't work in observable?)

**Comment by domoritz** [comment]
In the end, you just have Vega so if it works in Vega, you can achieve it with patching.

**Comment by mattijn** [comment]
The patching part works as expected, but the part before where you put the signal in the Vega-Lite spec, which compiles to Vega doesn't always. 

In some places in the Vega-Lite spec the definitions will be escaped during compiling and so does the injected signal. 

This Vega-Lite specification with injected signal in a `transform`:
```json
"transform": [
  {"filter": {"field": "Origin", "oneOf": [{"signal": "signal_origin_value"}]}}
]
```
compiles to this Vega definition:
```json
"transform": [
  {
    "type": "filter",
    "expr": "indexof([{\"signal\":\"signal_origin_value\"}], datum[\"Origin\"]) !== -1"
  }
]
```

So a patch like
```javascript
{patch: {signals: [{
  "name": "signal_origin_value",
  "value": "Japan"
}]}}
```
Can't be resolved.

So now we compile the Vega-Lite to Vega manually in the editor and fix the signals in Vega to make it dynamic, but every change in the Vega-Lite spec needs manual compiling and manually defining the signals again.

**Comment by domoritz** [comment]
If Vega-Lite does not pass signals through (we make no guarantees), you have to patch the generated Vega manually.

**Comment by mattijn** [comment]
Fair enough. If there is a certain character that force not escaping, while removing that character during compiling it could be possible. Thanks for the prompt responses!

**Comment by domoritz** [comment]
Not that I know.

**Comment by tmori3y2** [comment]
I would like to use signals in vega-lite to change the parameters of the formula, or to update the parameters with the rule marks.

For example, such an example can be realized with vega, but I hope it can also be realized with vega-lite.

https://gist.github.com/tmori3y2/6606686d9087a4b10d61d5e20d5a86b4

Of course, with vega-lite, you can add a constant value field to every data item with a calculate transform and use it in a formula, but it's a less clever implementation than a signal.

And selection cannot be bound to rule mark.

The rule marks bound to signals can be used for filters, so I think they are particularly useful.

Even if you can just bind the selection to the rule mark before implementing the signal, it will be a big improvement !

**Comment by domoritz** [comment]
In the meantime, you can use the `patch` method in Eega-Embed as I've done in https://observablehq.com/@domoritz/rotating-earth.

**Comment by tmori3y2** [comment]
What I want to do is achieved with the vega spec (pure json).

What I wanted to say is not about patching compiled vega, but about the vega-lite spec extension.

**Comment by tmori3y2** [comment]
I want the following functions as a spec of vega-lite.

- Use symbol and rule marks placed on the chart layer as a data picker

- Allow that value to be used instead of 'field' or 'value'

For symbol mark, there are the following vega examples.

https://vega.github.io/vega/examples/budget-forecasts/

See my vega example for rule marks.

[Open Link](https://vega.github.io/editor/?#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KABNkCAE6NCeHnJyQA4ulaxYjdDLAAFADbc8YAO7NEYdaxvIwGdQGtYANxgAGYAFHgAlGAAvGDoqNysMg6kYLAAjup4oQBMYISMaYzUGAB6OVHIAB6EoQC04WB13qwR5WCpuUUl6OUREQpKkOzo8L7U6okyythQjojMyIMQkIToysqMMtSzooorzsosuwAMJ-u4yMX4swDMZxeQsHgAnp6zkPDINjbLUGbUGToGywWYAbSUEGAkCBqCW+mc024jgA+lUXiiEjJmNx1AooLJwdDkFRkqCEVtlMisAkTGhuFR8ZBWIRlOg8PCoOjQgMAL4AXV5FyhMPinMgOjhmK2TIowNYnLqOROQshYGhsPFkuQmPQVVl8s5AEZ7qqICLNR8thyZGZXtK5PIoHKbArZnUjXQVcL1aK4VbkshbcwMRh9U7IC63TgjScvWbzRqxR94lM8CitsxzL8I1HjWcExbk-ptSjCMh0L4M9idMCDa7OQA2b1qpP+-QAjDVrN13OG3aF9VqlaW-SppJ4JkstkclO05Ld2s54cEvRgCHmzdDrdbyAkoN4clQMEAAXHC-cnhpiVgyCpjhkTsR9+vdJZ-LAAD4nJTqbTbwkVAAIR-DuKzTuy4rwDY8S1FsVBZKEADkLxIU6Lw8lEABUaSZNkeQ4Z26AEdYACSEROrhiEkURJFWORYA4daQZ2qGeodI2AAsToZNRjHdBgdEMUxgbBvaYYDCuECDpuxKkoeHzPtSyjsDY0GMGMU6spBc5pou2aQLyK78mqg6gDufpaowUrlpWWkzlZNkVlWmZLqB5qQISOAbmB5lgSs+5kh8p6lrZVaXsgr63vej4-kijhRcg75fnFL7-vSwHuRZEGzvo0GwaE8HIIhSFVGhYBVJhTqlmG-FxkaOR7GANV6pJ-kyYme7yUekBKQlKlqTYGm+PZOkltZOphfpdZGTuJmbmZK6WR8RGjbl-zFF2rkGT6KxeeuUnbv5UCBQp+ghRNKJESiLLluoKIRYlMVPr+CXpcl359YlgHICBu27jlUEwagcEyAh2SleVlX9E0zWXWFPGbeg002HVdCNU64SXbVzShc52FgHGAAcbVgR1IqnT1X0DepmkRoDK1IyjhnGaZPpto5OrXbdxVrZzZbOWAADUAmYGZy0dkjOR8x8hDIqERFOhUhnsxLUBTSg1yTvT2nrZA54pFR+H8bR-H0XySj8o8M6YN5rZLaO-yJOoXwoicWVQHg6gWLAwS4qg4KHX5-kSi85Yrcg6QKjIXwe5uTx4OgWTuqIDyHSszzcIQsyxmcdBGv98fPMg2c4PVhceegPXapAh3k76rzh-owSMDYHJ4hG1SEHi+hbN72zIKEM6sKgYIADoShNE9W+uNVbNV2N6vyfIV9Cjfin76ioB4mCdzUPcqOyI90DXEZVx82pGirQfp57Ycb-7O9xx5XcH6szkopr1D4PxXf1Pk8th6oBPhNI0sM8aViVlEVItEBgVxWOfZueAr511ZgtS2jwfD+EDrJB2xYoAwReMVN2uo-Cgn+qHJuBCthLAoepUuzV3DIAoc8N4nIwSQCGjIJYVslrSGTjgaELdvgzH0EA8ek84RGmntfCywRJgB0EZAG2K1nau3dh1PcMduCqFmMHAGutOT6Iss8SYvgjGRn7PoAAxJxeAAB2Im6AiayOOpAfUSiEDAnFOGKAwibCiM9qA1xIcXh6KePAbxHwwkRn8YEyAwRkEhLAso5ALduGBOMSkgEQJfi91gAANWBIwZQQ8j6jwnpfaeUQABkNSwCMFgAAMVcoPIW4jKmgOqWAOpDTCnFNKR0hJyDum9MaS0msbShmJOkZAZetdjpgFmmTFcyzpLszwe2IJTlKwPQ8LQpa68PgRQ9gnNh4JIAnN4RZIM8AdFGMOsyQxejb4JzMRYvMjMbAIWSSYr23BzEAHUSnHCUZ8nAnF64Z3+eYgA8mseAIZwngsJnQW4UKuThK8e8fQvinjFFyRfeGzlfm7jCUouJ4SJiJAYZAL+NxeQYsgC8aWYKrGEzWVueudKGS8yUfAVg6h+HIvZZ8bgNg6jqDUIwAAXksRlqy2b2wso7SRXMmY83uicihRz9Dar4a8HF65Ln7LmRQ259yXkhwZoI15piAUfNFWYb5vMmX2qBSCxAIqGyzEhfA-4MLkDwtGEitlPqy5oqZR4302KfFMhyXWcaUpuaEDuqS+O5LfSUqUdSlkHx6WTkZf65lrLfQopVHXCuPKfn8sFcKsN0YoB3IlVKswcrDKcukkq3BKr8H63nOmfVFldVQCHbuVhRqOFXPNdo3RtrrXPPnW491jrw0bRdXiN1gbgVHC9Q2zkfq7WBuDYi143rG1xnRcW6N0Jy1RtLUIxgIiqWTDzRSXdHbi2ZuhLG6J8aCWJvVh-AtLN2pVsQLyg+0IBVCtxOe8UkxHCSule2hVO5OXLOuf8SJngjw+ShJsuNOr74fC4RWDuS0qQYBlJ4gDeTjxz1ii1Ko-JSWXIsNQdh5wY10cUp6wyWH47YljjgYIwJbwULlZMWYXsFTdsTIRv9xGqGcJoUnU5VH0A0Z44CQDkAwTMTEqGeeDTRKsV1Cxtj-dONEnxbp+jdKrjf0LU6E4gmPLCc5GJkEzClpSe4DJphpkMFDD1GoHBCmTE4aI0tXET7kgfHYPYPA3AA46uGgAYTTDnRsFCJglIAMrRaU0tfLgTZO+Yspp7T3mJNLRguwb4R5auVd3GGAAolUG0k4y4UNQFsTr3XZjnEOcNZr4nWvxxlZSaow35MEai1E-QMTYuaAPKRtJ2tRtjCyxOHOOQ8uaGUEVpbmLDslMCwqCh1W1wtYoQ1prsw7tLQ6119bvWXsDbewlj7w6xtPYm5Jmb0aTjzaOkXYruLTlxfe1AJLBBUunLKwDnz6W8BGsgAAFQmqcnQO3ssxly-V9AjWbBNNdLAPdjCrvE9J7ChCMEGEVaB9MWbZcwdZIiad5l0O1s-YIZtpHR2Ud1b++j8URgTBmAsNYEl6X8d7ZjAd2n3x6fFUZ5dybHlpus5B8FiAWGxUyBbjsJRIwxi5umIpBYs4jJGSAA)

The rule mark image is close to the binding of the selection slider, but it does not match my request..

Also, the slider is not cool and cannot be operated intuitively.

Better if signal can be used with vega-lite, but extension of selection is also acceptable

**Comment by kanitw** [comment]
We mostly have signals as experimental features in VL.  
I'm opening https://github.com/vega/vega-lite/issues/6189 to discuss whether we want this to be an official feature, so we no longer need this issue.
