### ISSUE TITLE
Better way to specify latitude/longtitude mapping?

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3353]
@jwoLondon has pointed out that an geographic encoding of the form:

```
"projection": ...
“encoding" : {
  "x": { "field": "lng", "type": “longitude" },
  "y": { "field": "lat", "type": “latitude" }
} 
```

is slightly misleading in implying two independent mappings while in fact both x and y are functions of longtitude and latitude values.  

Note that the design was in part motivated by the fact that for a basic projection like mercator, x predominantly represents longtitude and y predominantly represents latitude so this should be easy for most people to understand. (Tableau's UI for similar uses the same approach to represent mapping between lat/long to "row"/"column" shelves.) 

Another related note is that distinguishing between longitude and latitude types represents a level of
semantic detail that is at odds with quantitative , ordinal etc.

## Possible Proposal

If we want to make this strictly accurate for all projection (which I personally think we should), one possible change is making latitude and longitude (and latitude2/longitude2 for ranged marks) encoding channels that are only used for projections.  Given a field lng and lat in a data table, you can do:

```
"projection": ...,
“encoding" : {
  "longitude": {"field": "lng", "type": “quantitative" },
  "latitude": {"field": "lat", "type": “quantitative" }
} 
```

Thus, this should read naturally as  'encode the field “lat” as “latitude"' instead of 'encode the field “lat” as “y”' in the current approach we have.  Note that both fields are simply quantitative types -- no longer need special lat/long type anymore.   I think this proposal will actually address @jwoLondon's another concern that type `latitude` and `longitude` are not necessary too. 

However, one drawback of this approach that other members in the team are concerning with is that lat and long are not direct properties of the marks so it might be hard for users to understand.

I personally don't think this is an issue for a few reasons.
1. In my interpretation, encoding channel are target properties that users can map data fields (or constant values) to.  Most of the time, they should be mark properties but they don't have to.  We actually have a precedence for this like the "detail" channel.  "lat" and "long" could be target properties for encoding marks with projections.
2. I think it actually makes it easier to teach people that having projection means that we have input locations in lat/long.  The projection then converts lat/long into output x, y positions on the visualization.   This is a very critical concept to teach people when we explain about projection. 

However, we don't have a consensus that this proposal is a clear win over existing approach, especially regarding the concern that "lat" and "long" are not direct properties of the marks" so I would post it here for further discussion that we can revisit later.  

Should we reach agreement for this approach (or other better approach) in the future, 
we will introduce the new way as a new "preferred" approach while maintaining backward compatibility support for the approach introduced in 2.1.  So this won't be a breaking change.

**Comment by g3o2** [comment]
Why not have type `geographic` as suggested in the book "Making Data Visual"? `x` and `y` should be sufficient - personally, I don't see why one needs to specify the types `longitude` and `latitude`, as they are already fields.

**Comment by jwoLondon** [comment]
Thank you for sharing this issue. Personally, I share the desire to make the specification as simple and understandable as possible while granting the necessary degree of expressiveness.

It was the need to have a clear specification that led me to propose keeping `type:quantitative` for geo coordinates. I like the proposal you make in this issue in that it is a compromise between semantic correctness (spherical coordinates are quantitative types) and backward compatibility ((longitude,latitude) can be mapped back to (x,y)).

I recognise that unlike x and y positions on the graphics plane, longitude and latitude are not direct properties of a visually expressed mark. However, it is also the case that if a spec encodes x with longitude and y with latitude, that encoding is incorrectly expressed. So the question becomes, which of the two approaches is less confusing to the user?

I would argue your proposed longitude and latitude encoding raised here is the less confusing for the following reasons:

- encoding longitude with some field or constant is the more declarative approach. It simply declares the data that will be regarded as representing longitude. Encoding to x instead hides the fact that that property has to be generated by passing it through the projection mapping after combining it with latitude. I think that is more difficult to understand. It also sets an undesirable  precedent in that the encoding declaration is no longer 'pure', being dependent also on another encoding declaration.

- My experience teaching students about measurement types (in the Stevens sense) for visualization is that they can often be confused between types (nominal, ordinal, quantitative), dimensions (e.g. length, dollar value, velocity) and data instances (3 metres, $4.99, 20 km/h). I think creating new Vega-Lite types `latitude` and `longitude` is going to confuse things further by labelling two concepts with the same term `type`.

- Encoding is simpler because no new types need be created.

- If you require longitude and latitude to always be encoded to x and y, it will make hybrid geographic/cartesian projections more difficult or impossible to achieve. For example imagine point locations across the US using an Albers projection. Suppose in addition to the geographically project points you wanted to drop leader lines for each down to bottom of the map along the x-axis. Here the y position of the leader line would be a constant, but to calculate its x-position you would need its latitude as well as longitude. If latitude was mapped to y, this would be impossible as y would be encoded as two different values simultaneously. Using your modified approach you could do this though by encoding longitude, latitude and y independently.

**Comment by kanitw** [comment]
@jwoLondon  I totally agree with you.  I also like the example you give in the last bullet.  Let's see what others think.  :)

**Comment by domoritz** [comment]
>  Here the y position of the leader line would be a constant, but to calculate its x-position you would need its latitude as well as longitude. If latitude was mapped to y, this would be impossible as y would be encoded as two different values simultaneously. Using your modified approach you could do this though by encoding longitude, latitude and y independently.

This is a good example of why latitude and longitude channels make sense. In our discussions, we decided that this can be addressed with a projection transform. 

Another point that I want to add to @kanitw's description is that in addition to `latitude` and `longitude` types, we need `latitude2` and `longitude2`, which overall increases the surface of Vega-Lite. Also, Tableau uses x and y (or column and row).

**Comment by kanitw** [comment]
>  in addition to latitude and longitude types, we need latitude2 and longitude2, which overall increases the surface of Vega-Lite. 

Yeah, but I think it's very minor increase and it's a better increase than making "latitude" and "longitude" new data "type"s, which gonna make it quite hard to teach about what type mean.

**Comment by g3o2** [comment]
Is it meaningful to have both Cartesian and geographic projections in one graph or view? Or in other words wouldn't the leader lines also have to be projected as geographic?

What would be Wilkinson's grammar of graphics take on this issue?

**Comment by kanitw** [comment]
> Is it meaningful to have both Cartesian and geographic projections in one graph or view? 

Another example would be if you want to add text to annotate top/bottom-left/right corner of a map.  You probably don't want to specify lat/long of the top-left/bottom-right of the screen.

> What would be Wilkinson's grammar of graphics take on this issue?

Wilkinson's GoG does not make position mappings explicit, but rather use a parameter order convention. 

```
ELEMENT: position(__a__*__b__)  
```
means x = a, y=b.

If coordinate is a mercator projection

```
COORD: project.mercator()
ELEMENT: position(__a__*__b__)  
```

then long=a, lat=b

**Comment by g3o2** [comment]
You could use the `layer` operator to use two different projection systems at the time, right?

**Comment by jwoLondon** [comment]
Was there any conclusion as to whether the 

    “encoding" : {
      "longitude": {"field": "lng", "type": “quantitative" },
      "latitude": {"field": "lat", "type": “quantitative" }
    } 

proposal is likely to be adopted (and if so, any approximate timescale)?

Just one more example of why I think it is necessary to separate cartesian _x_ and _y_ from spherical _longitude_ and _latitude_:

Below is a vega-lite map of the July 2018 lunar eclipse (reproduced from [this](http://www.skyandtelescope.com/astronomy-news/observing-news/solar-and-lunar-eclipses-in-2018))

<img width="718" alt="eclipseexample" src="https://user-images.githubusercontent.com/1846999/36403979-152a8bc8-15e0-11e8-85ce-164199663040.png">

Unlike the example of labelling the corner of a map, the labels here cannot use cartesian coordinates entirely without some tedious trial and error name placement. While they could (and do in this case) use both longitude and latitude to place them, this may not always give the desired effect of keeping  a vertical alignment depending on the projection.

For example, if the projection is rotated 10 degrees to the north, the labels lose their vertical alignment:

<img width="736" alt="eclipserotated" src="https://user-images.githubusercontent.com/1846999/36404294-c06636b2-15e1-11e8-95c0-738e627e0238.png">

What is needed is the ability to specify both longitude and latitude to map the x coordinate and a cartesian _y_ to map the y coordinate of the labels.

**Comment by willium** [comment]
Couldn’t you just as easily accomplish the labeling desired by layering on top text marks?

**Comment by jwoLondon** [comment]
That exactly what that example does. But if one is forced to use cartesian coordinates to position the labels in that layer, how do you know where they should be placed without trial and error?

Sometimes, as with this case, part of the positioning is determined by geographical position.

**Comment by willium** [comment]
Perhaps I’m misunderstanding—why not use lat/lng to position the text in a new layer with a non-rotated projection

**Comment by willium** [comment]
what would a proposed spec look like?
```
encoding:
   latitude: field
   longitude: field:
   y: value
```
and it would always override the Cartesian over the lat/long?

**Comment by willium** [comment]
though I understand your use case, labels aren't really a supported concept in Vega-lite yet. As such, they're not the first thing considered when developing the spec. I know @kanitw advocates for introducing new encoding channels as you suggest, but I think we had decided against it (I might be wrong). I know in Vega, with some amount of reactive geometry, your labeling could be more trivially supported in the cartesian plane.

**Comment by kanitw** [comment]
@willium -- we haven't reach any conclusion yet.   That said, @domoritz seems a bit more convinced of this approach last time I chat to him.  (Also, see https://github.com/vega/vega-lite/issues/3353#issuecomment-362933588, he kinda vaguely becomes more ok with it.)    
I also strongly think we should separate the two like @jwoLondon suggested. 

That said, I'm on a job market right now and Dom is busy with a paper deadline so I don't think we will get to change within the next month-ish.

**Comment by domoritz** [comment]
@jwoLondon Expect that this change is not coming soon and build examples and Eve against the existing API.

**Comment by kanitw** [comment]
Btw, if we got with lat/long channels, I think x and y should override lat/long like @willium mention [above](https://github.com/vega/vega-lite/issues/3353#issuecomment-366852376).

**Comment by jwoLondon** [comment]
Thanks for the info in timescales, which is very helpful. 

My example of the eclipse map may have been distracting in using labels as examples of hybrid geographic/cartesian placement. I don't think this is an issue about text placement specifically, but rather a more general one about maps. I would argue it is common when mapping to have combinations of geographic and cartesian placement of features of all kinds. For example the eclipse map could have circular symbols at the penumbra/umbra label locations (p4, u4, u3 etc) instead of text.

And more fundamentally, I think equating x with latitude and y with longitude has the danger of encouraging a flawed mental model of geographic referencing. A longitude, latitude pair is not a location, but rather it represents a vector of infinite length from some origin near the centre of the earth. Only when some model of the shape of the earth (e.g. WGS84) can that vector be used to intersect with the surface to provide a 3d location. And then it needs to be projected onto a plane to reduce it to 2 dimensions.

Having VL reflect the fact that longitude/latitude represent one set of properties of geographic data and that x,y represents another set of properties of its positional encoding that may be fully or partially dependent or entirely independent seems like a good thing to me.

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/3498
