### ISSUE TITLE
Inconsistent boxplot config

### ISSUE THREAD

**Issue by starry97** [vega/vega-lite#3398]
Why is size the only thing in boxplot config, and its other properties (like extent) are not in the config?

**Comment by mattwchun** [comment]
@starry97 I'm a little confused by the question. Size is the only new property needed for the boxplot and it has all the other properties because it extends MarkConfig. I'm currently working on changing the default boxplot to be a tukey plot (#3262) which will add the extent property to BoxPlotConfig.

**Comment by kanitw** [comment]
Why isn't `size` a part of `BoxPlotDef` ?

**Comment by kanitw** [comment]
Also right now we rely on `config.box`, `config.boxMid`, and `config.boxWhisker` for customizing parts of the mark `box-plot`.    This is in fact inconsistent with other marks where you can do `config[markType]`.  


In a way, a better config design would be `config["box-plot"].box/mid/whisker`

- [ ] change the config structure
- [ ] consider renaming `box-plot` to `boxplot` so we don't need an awkward `config["box-plot"]` and instead can use `config.boxplot`
- [ ] For `mid`, I wonder if `midTick` is a better name.
- [ ] Consider using dash in style names as it is more consistent with the rest of the language (interpolation uses dash) -- `box`, `box-mid-tick`, `box-whiskers`

**Comment by kanitw** [comment]
cc: @starry97, @chanwutk

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/3454
