### ISSUE TITLE
Add Vega's `key` property for marks

### ISSUE THREAD

**Issue by knuton** [vega/vega-lite#3496]
Would it make sense to add [Vega's `key` property](https://vega.github.io/vega/docs/marks/#top-level-mark-properties) to the mark configuration?

It would be helpful to be able to identify the source of a data point in interactions, as described in vega/vega#49.

Is there a general policy for which features of Vega should be directly configurable from Vega Lite?

**Comment by domoritz** [comment]
This sounds like a good feature to have. However, it would break the assumption that fields are only used in encodings. Maybe instead, we could add a key encoding that works similar to detail. What do you think?

Once we decided on the design of this, we can look at an implementation. We won't have time to implement this soon but would be happy to review pull requests.

**Comment by kanitw** [comment]
Supporting `key` definitely makes sense. 

Like Dom said, the question is where would it stay in the language. 
Let's brainstorm a bit here: 

1.  I don't think mark configuration (`config.mark.key`) make sense since config suppose to be a theme for visualization and key is definitely visualization specific. 

2. Putting `key` in mark definition block would be inconsistent that all other mark properties are static values, not dynamic fields. 

3. I think putting it in `encoding` like @domoritz suggested is the right solution.   In a way, we are encoding the field as the "key" of each item in the scenegraph.

**Comment by kanitw** [comment]
@knuton 

Actually, thinking more, you can already access the data point via `item.datum.xxx` as in [this comment](https://github.com/vega/vega/issues/49#issuecomment-17513783)? 

I actually think that key is still useful for applying CSS transition correctly with streaming data though.

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/3501

**Comment by knuton** [comment]
That makes perfect sense. Many thanks for the timely resolution!
