### ISSUE TITLE
Add more window transform examples

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#3572]
- [x] Running sums and averages
- [x] Rank chart https://github.com/vega/vega-lite/issues/2488#issuecomment-373427904  (Good data would be sport league ranking)
- [x] Top-K

(Add to window.md)

**Comment by kanitw** [comment]
@AkshatSh 

The window_student_rank.vl.json  doesn't show anything -- so I'm gonna remove it first. 

Please correct it and submit them in a follow-up PR.  

I also wonder why the frame for rank and count isn't the same.  (Maybe it's correct, but I want to understand why -- given that it's not showing anything I suspect that it's wrong.)

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A bar graph showing the scores of the top 5 students. This shows an example of the window transform, for how the top X can be filtered, and also how a rank can be computed for each student.",
  "width": 300,
  "height": 50,
  "data": {
    "values": [
      {"student": "A", "score": 100}, {"student": "B", "score": 56},
      {"student": "C", "score": 88}, {"student": "D", "score": 65},
      {"student": "E", "score": 45}, {"student": "F", "score": 23},
      {"student": "G", "score": 66}, {"student": "H", "score": 67},
      {"student": "I", "score": 13}, {"student": "J", "score": 12},
      {"student": "K", "score": 50}, {"student": "L", "score": 78},
      {"student": "M", "score": 66}, {"student": "N", "score": 30},
      {"student": "O", "score": 97}, {"student": "P", "score": 75},
      {"student": "Q", "score": 24}, {"student": "R", "score": 42},
      {"student": "S", "score": 76}, {"student": "T", "score": 78},
      {"student": "U", "score": 21}, {"student": "V", "score": 46}
    ]
  },
  "transform": [{
    "window": [{
      "op": "rank",
      "field": "score",
      "as": "rank"
    }],
    "sort": [{ "field": "score", "order": "ascending" }],
    "groupby": [
      "Student"
    ],
    "frame": [null, 0]
  },
  {
    "window": [{
      "op": "count",
      "field": "score",
      "as": "totalStudents"
    }],
    "sort": [{ "field": "score", "order": "ascending" }],
    "groupby": [
      "Student"
    ],
    "frame": [null, null]
  },
  {
    "filter": "datum.totalStudents - datum.rank > 5"
  }],
  "mark": "bar",
  "encoding": {
    "x": {
        "field": "Score",
        "type": "quantitative",
        "axis": { "title": "Score", "grid": false }
    },
    "y": {
        "field": "student",
        "type": "nominal",
        "scale": { "rangeStep": 12 },
        "axis": { "title": "" }
    },
    "color": {
        "field": "student",
        "type": "nominal"
    }
  }
}
```

**Comment by AkshatSh** [comment]
Rank and Count have different frames because they compute two different things.

Rank Window Transform computes "how many students am I better than?" (rank) and the Count Window Transform computes "how many students total?" (totalStudents)

To get the Top K, I select (totalStudents - Rank) < K. Which means the top scoring student would be better than all students, so Rank would be equal to TotalStudents. The second student will have a Rank of Total Students - 1, so totalStudents - (totalStudents - 1) = 1, and so forth. 

This way the best student will get 0, the second best will get 1, and we can filter all these values while the value produced is less than K to get the top K students.

The fix here was to change `Score` to `score` and make the filter `"filter": "datum.totalStudents - datum.rank < 5" instead of `"filter": "datum.totalStudents - datum.rank > 5". 

I have a WIP PR for these changes and other examples: #3573

**Comment by kanitw** [comment]
You rationale still doesn't explain why rank would use `"frame": [null, 0]`, not `[null, null]`

**Comment by AkshatSh** [comment]
I wasn't sure whether `[null, null]` or `[null, 0]` would be the appropriate one. `[null, 0]` is the default value for the window transform, so I assumed to get it working as expected I would use `[null, 0]`. Also when I was thinking about rank I thought about it as the rank up until the current point hence I defined the frame as `[null, 0]`. 

I can change it to `[null, null]` if that is better.

**Comment by kanitw** [comment]
I d say test and see what s right.

**Comment by AkshatSh** [comment]
Update on this: After checking with the vega channel, rank does not rely on the frame. So I moved the example to have `count` and `rank` in the same window transform.
