### ISSUE TITLE
[Feature Request] API for passing arbitrary statistical functions

### ISSUE THREAD

**Issue by ashimb9** [vega/vega-lite#3611]
Background: A feature-request in the [Altair Github repo](https://github.com/altair-viz/altair/issues/761#issuecomment-381409149) for passing arbitrary statistical functions to the Chart object.

Apparently this has to be supported here before it can be implemented downstream in libraries like Altair. Given that, I was wondering if it would be possible to add support for passing arbitrary statistical functions to the Chart object (or its vega-lite counterpart; my apologies if this object is specific to Altair -- unfortunately, I am not familiar with vega-lite proper). In any case, for your convenience, here is the original post verbatim:

> As noted in the title, is there a way to pass a stat function name/call which, for instance, can overlay an OLS best-fit line or a lowess curve over a scatterplot? A relevant [example](https://altair-viz.github.io/gallery/poly_fit.html?highlight=polynomial) that I found in the docs (also, see image below) seems to first create a dataframe with the fitted values and then plots it rather than simply passing a function call to the Chart object. Unless I am missing something, please consider this issue as a feature request as it would be a pretty useful feature for users IMO to be able to simply pass a function name/call. Thanks!

![image](https://user-images.githubusercontent.com/22569641/38775807-b08bfdfa-4050-11e8-8f4b-60c6161ae5e7.png)

Edit: Perhaps the [stats layer](http://ggplot2.tidyverse.org/reference/index.html#section-layer-stats) (and/or corresponding geoms like geom_smooth) in ggplot2 could serve as a point of reference.

**Comment by domoritz** [comment]
Thank you for the issue. Can you clarify whether you want only scalar functions that are applied to each entry or a function that computes something on multiple rows?

Please keep in mind that Vega is in JavaScript and we won't be able to run any python function. However, we do allow passing expressions to calculate transforms. We are working on integrating more of Vegas's transforms into Vega-Lite. Vega has an extension interface to add new transforms.

**Comment by ashimb9** [comment]
> a function that computes something on multiple rows

Yes, it would require the function to be able to calculate an output based on multiple rows. Also, if I understood you correctly, since Python functions cannot be passed I would assume that relevant stat/ML algorithms not available in Vega would either have to implemented from scratch or imported from an external library. Is this correct? And if so, how would you assess the feasibility of the latter option?
Thank you!

**Comment by domoritz** [comment]
Yes, you are right, we cannot import functions from Python. I think for now the best option is to precompute the data and then pass it to Vega/Vega-Lite. 

Here are the core transforms implemented in Vega: https://vega.github.io/vega/docs/transforms/. Here is documentation on how to extend the transforms and expressions: https://vega.github.io/vega/docs/api/extensibility/#transform.

Let me know if you have more questions. I am going to close the issue here because Vega-Lite is a compiler for Vega and we can only use transforms that are implemented in Vega. However, if you have a specific transform that you need, we can see whether it can be implemented in Vega-Lite by composing Vega transforms or whether we need a new Vega transform.
