### ISSUE TITLE
Add ability to select theme in spec

### ISSUE THREAD

**Issue by davidanthoff** [vega/vega-lite#3680]
It is great to see theme support! Could one also specify what theme a given spec is supposed to use in the spec itself, not just in vega-embed? For example, I'd like to be able to pass a spec file to someone else, and then the figure that person sees should look exactly like what I had in mind, including the theme choice.

**Comment by domoritz** [comment]
I think you are referring to themes in [Vega-Embed](https://github.com/vega/vega-embed). [Vega Themes](https://github.com/vega/vega-themes) are actually just configs so you can just apply the config and it will work. The easiest way is to open the spec from Vega-Embed in the editor since we automatically apply the config to the spec. Then you have a spec with the theme applied to you can send off.
