### ISSUE TITLE
choosing color conditioning on 'null'

### ISSUE THREAD

**Issue by pagpires** [vega/vega-lite#3696]
There seems to be a bug when choosing colors conditioning on 'null'.

The vega-lite spec is [here](https://github.com/pagpires/temp/blob/master/condition_null.json). Note in the end that I specify `"test": "datum.rate !== null"` and there's no gray rect (only white rect without stroke) in the viz, and if I change that to `"test": "datum.rate === null"`, rects that have colors change to gray while these white rects remains white.

**Comment by domoritz** [comment]
Hi @pagpires. The issue is that Vega-Lite automatically filters out null values because they would otherwise be mapped to 0.

You can disable it with

```json
{
  "config": {
    "invalidValues": false
  }
}
```

See https://vega.github.io/vega-lite/docs/config.html#top-level-config for details. 

![image](https://user-images.githubusercontent.com/589034/39612896-1af57f6a-4f18-11e8-9b5e-e55a4981bb56.png)
