### ISSUE TITLE
`align` and `baseline` channel for text

### ISSUE THREAD

**Issue by tonne1** [vega/vega-lite#3726]
Bar charts can have value labels, created with text marks. This works well for bar charts representing only positive values. With bars showing both positive and negative values, it becomes necessary to change text properties `align` and `dx`, depending on input data, so that labels appear on either side and do not overlap into their bar. Like this, using d3:

![bar_orig](https://user-images.githubusercontent.com/39104080/39817596-dad1c2e6-539e-11e8-9adc-0ceb673f4df1.jpg)

Using vega-lite, I got this far: labels are left aligned and offset 5 px.
![bar_vl](https://user-images.githubusercontent.com/39104080/39817636-f327abda-539e-11e8-957b-93389c3749c1.jpg)

```js
{
  "mark": {
    "type": "text",
    "align": "left",               // "datum.dif" > 0 ? "left" : "right"  
    "baseline": "middle",
    "dx": 5,                       // "datum.dif" > 0 ? "5" : "-5" 
    "dy": 1
  },
  "encoding": {
    "text": {"field": "dif", "type": "quantitative", "format": ".0s"}
  }
}
```
The code comments indicate what would be required, is there a way to do this?

Related: in screenshot 2 the y-axis is at its original position. In this example it looks better if it sits at x=0.

**Comment by domoritz** [comment]
We would need to implement alignment as a channel. However, I see this as a special use case that is not common in exploratory analysis and so maybe we won't implement this feature in Vega-Lite and instead you would need to modify the resulting Vega visualization. 

We plan to make offset a channel so maybe that is sufficient to implement this example. Alternatively, we could think about some special logic for this particular case in our annotations feature.

**Comment by kanitw** [comment]
Why is this really a special case?  

Given we want to support condition, `encoding` channel seems to be the natural place to support this. 

The tricky part is to determine what should be the default range when a `field` is encoded, but users should not directly encode `align` with field in general so maybe we can just set range to `["left", "center", "right"]` as it doesn't matter?  

Note that https://github.com/vega/vega-lite/issues/1855 was "Add Missing Encoding Channels" and `align` was one of that until we change it to just "stroke dash" recently as we want to focus on critical one first. 

If we're to implement `align`, we better include `baseline` too as it will be equally important for vertical bars use case.

I'll assign this to @swojit since this issue is pretty to #1855 that he's doing.

**Comment by domoritz** [comment]
Sounds good to me. Let's implement an align and baseline channel. The example above can be a good demonstration. Also adding @starry97 for annotations.

**Comment by kanitw** [comment]
I guess another option is to implement encoding channel that supports conditional value def only (but not field def).

**Comment by tonne1** [comment]
Wow, almost real-time!
dx and dy are also needed to [nudge](http://ggplot2.tidyverse.org/reference/position_nudge.html)  a text label away from its anchor point. So we have to set align, baseline, dx, dy conditionally.

**Comment by g3o2** [comment]
An encoding channel without field definition? Given the way condition works, you're left with choosing between only two values. Maybe it would useful then to allow an array of value conditions ?

**Comment by kanitw** [comment]
> I guess another option is to implement encoding channel that supports conditional value def only (but not field def).

I think this is probably a bad idea (inconsistency in the language)

**Comment by kanitw** [comment]
https://vega.github.io/vega/examples/job-voyager/ is actually an example where encoding `align` with 
 a field  (via a quantize scale) is reasonable.

**Comment by kanitw** [comment]
The voyager example in https://github.com/vega/vega-lite/pull/3283 can also benefit from conditional `align`.

**Comment by LucCappellaro** [comment]
I'm quite astonished that this is still not possible with Vega-Lite.
This is such a common feature, see MsWord and MsExcel: label position = outside end, inside end, ... .
There is no left or right, because it is inconsistent/ugly whit negative values.

Additionally, it would be even better if the scale-padding could be automatically adjusted to display the labels properly inside the chart.

**Comment by kanitw** [comment]
Given the new expression feature, we can now set conditional align / dx like [this](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEzjQATjRyZ289AEEABEyTrDsU5kMB3OjEOy+O0oeJJBDNZUMB1OOaRZQxgaVUN6fyQADxoIQ2U2ZBog4UcFQ0DlQ2SITDgkLIYISPM5ZTpdd0MyTSyoNkE2M0w2ePUkawzDAC84dVaTYtS4SkUVJEwUVFA3DzU0AG1QKZB9MaY0fgAmAA4AXwVltBAAIXW0AFYLg6P0AGFz1H4AZmebkBWAEUeATgBGd4rACijx2AMOH2OADFHhc3hCVgBxR78P4-QHHAASoIA7Bj0ABJWFbPYAXQOIDgsnq5VkZDQoAAngyQAAzGhwQTKY4oJSYRk4ODHWSJZLuMbRWIshJJPSs9zFPk0KAAawgaHlgkVIEESCYnP0dMEQtQAAYlLr9YIAAoFWn01BiPYUqIs9mc7noDZ8gUmkAARwYgR0k2cQqU0HcJtAODtyQdW1NFMl6umIBqoTuDSaLPqsnKOjkLLyuWOygmDAQlFmnkMAF4G4ZTWMa36mLrVSAKa3jgBiZQDrvOim6xl9RagZDqFXHEzqLsQqcztP8wXHPJRTAS4RkPSgOBRHDz9DlzCVyhMQwAHibhgA-IYAOSaMhYR+GVBP42szCPhcqV00wPI8ywrKtLxvU170MbYP0MLYhyUKkaXjYsDy3NN3S5WcxlXP1A2DOgJhoUghzJPYgA). 


![image](https://user-images.githubusercontent.com/111269/103471961-c687a900-4db9-11eb-9d76-a79ae020d381.png)


Given the default range won't be smart by default anyway, I'm now less convinced that we should add `align` / `baseline` channel unless we find a strong argument.  (Thus, I'll close this for now.)

**Comment by kanitw** [comment]
I'm adding the example to the gallery in https://github.com/vega/vega-lite/pull/7144
