### ISSUE TITLE
Selectively disable warnings

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#3759]
Disable certain warnings like warnings about the type not being specified.

**Comment by kanitw** [comment]
This basically requires us to assign ID to all warnings that we're adding, making it way hard to add warning since every time we need to name the ID well, as it's a part of the API that we can't change later.  Thus,  I think it's much more work than it's worth.   If there is a warning that's worth hiding, maybe we should remove it.  

But for the warning about type, I think it is an **important* warning and thus shouldn't be hidden.

**Comment by domoritz** [comment]
Since all type warnings are the same, could we just offer a way to disable a specific warning? I'm proposing to let users disable any of the messages in https://github.com/vega/vega-lite/blob/master/src/log.ts#L94. No grouping. 

If we ever want to localize error message, we will need IDs anyway. 

I don't think @kanitw or I will have time to add this but we could leave this open for someone else to implement.

**Comment by kanitw** [comment]
Not sure what you mean "no grouping". 

We do have IDs, but they are mostly quickly named. If we do expose these IDs as a part of the API, then all the names must be way more well thought.  

Given (1) neither you or I will have time to do this, (2) it's a pretty tedious task, (3) it will slow down our development process  and (4) the utility is low, I think this won't ever happen so closing is probably the right thing to do.

**Comment by melissachang** [comment]
I know this bug won't be fixed, but just wanted to add +1. #4929 has a warning that isn't relevant in my app. I look at Javascript console for actual errors and warnings; it would be nice if I didn't have to see #4929 every time.

**Comment by domoritz** [comment]
You can write a custom logger (as described in the docs) and filter out this particular warning if you want to.
