### ISSUE TITLE
Support projection property center and scale

### ISSUE THREAD

**Issue by kobben** [vega/vega-lite#3942]
In the Vega-Lite documentation it says projection has several properties (https://vega.github.io/vega-lite/docs/projection.html).  However in the spec below I can change "center": [0,0] to whatever, there is no resulting shift. Rotate and clipExtent work. And it's frustrating anyway that the normal D3/Vega projection.scale is not available. How can I zoom in to a part of the world now...?

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.1.json",
  "width": 500,
  "height": 300,
  "data": {
    "url": "data/world-110m.json",
    "format": {
      "type": "topojson",
      "feature": "countries"
    }
  },
  "projection": {
    "type": "equirectangular",
    "clipExtent": [[0,0],[500,300]],
    "rotate": [0,0,0],
    "center": [0,0]
  },
  "mark": {
    "type": "geoshape",
    "stroke": "white",
    "fill": "#ccc"
  }
}
```

**Comment by kanitw** [comment]
@willium I can't remember why `scale` is not included?  Any clue?

**Comment by kanitw** [comment]
I wonder if allowing users to override `translate` and `scale` would be useful / working at all? (edited)

Like if `translate` (and/or?) `scale` are specified, then VL doesn’t automatically provide `fit`.

**Comment by domoritz** [comment]
I agree that it would be useful to be able to set center and translate and it shouldn't be too difficult to support this, right?

**Comment by kobben** [comment]
Small thing: Can I suggest setting the title to "Support projection property center **and scale**"...? To make suer the scale is not forgotten (the combination is necessary for the use case of zooming into part of a larger map).

**Comment by jheer** [comment]
I would like to up-vote this issue. In many cases it is useful to have more control over the projection, and there are plenty of times you want map content to be clipped rather than rescaled to fit the display. I think auto-fit is a reasonable default, but we should really be providing more control to end users when it is desired.

In response to @willium's comment above, I don't see why we can't just set the chart to the specified width and height and then perform clipping on the geo content. Then one could change projection settings to pan and zoom as desired. Perhaps we can simply disable fitting when specific parameters (e.g., scale) are provided.

While perhaps a stretch, it would be particularly lovely if we could roll this in prior to the week of April 30, 2019, as then I could use it within our visualization course materials.

**Comment by kobben** [comment]
I dont think I can vote,  but if I could, I would...!


Barend Köbben


---- Jeffrey Heer schreef ----


I would like to up-vote this issue. In many cases it is useful to have more control over the projection, and there are plenty of times you want map content to be clipped rather than rescaled to fit the display. I think auto-fit is a reasonable default, but we should really be providing more control to end users when it is desired.

In response to @willium<https://github.com/willium>'s comment above, I don't see why we can't just set the chart to the specified width and height and then perform clipping on the geo content. Then one could change projection settings to pan and zoom as desired. Perhaps we can simply disable fitting when specific parameters (e.g., scale) are provided.

While perhaps a stretch, it would be particularly lovely if we could roll this in prior to the week of April 30, 2019, as then I could use it within our visualization course materials.

**Comment by kanitw** [comment]
@kobben  You can. :)

**Comment by kanitw** [comment]
@willium -- would you have time to help?

**Comment by jheer** [comment]
I was looking through the VL code base and I think the necessary changes to the projection logic should be very easy / straightforward.

What I’m less sure about is how to enable clipping for the projected marks: if I have a projection that does not auto-fit and a mark that includes lat/lon channels, I want to enable clipping. @kanitw / @domoritz: Where in the code should I be looking to achieve this?
