### ISSUE TITLE
Caching a Dataset for Multiple Specs

### ISSUE THREAD

**Issue by chrisyeshi** [vega/vega-lite#4146]
I have a use case that a user can create different visualizations with a single dataset in a trial-and-error fashion. I tried inlining the parsed dataset into the specs but it didn't seem to help. From the Chrome profiling tool, Vega-lite always "parse" the dataset even if it's inline javascript objects. Relevant screenshots are provided below.

This report is created according to the stackoverflow thread: [https://stackoverflow.com/questions/51455030/cache-a-dataset-in-vega-or-vega-embed](https://stackoverflow.com/questions/51455030/cache-a-dataset-in-vega-or-vega-embed)

The spec as shown by `console.log`, which shows the data is indeed inline.
![vega_lite_spec_inline_data](https://user-images.githubusercontent.com/571692/44688110-14c95800-aa08-11e8-92e4-585172e957fb.png)

The screenshot of Chrome's profiling tool shows that the `parse` function takes most of the time.
![vega_lite_stack](https://user-images.githubusercontent.com/571692/44688126-1b57cf80-aa08-11e8-8c29-8f8bde91d895.png)

As this is my first time creating a bug report, I hope I am not breaking any rules. Let me know if I can provide more materials.

**Comment by domoritz** [comment]
Thank you so much for the bug report. This is perfect. The issue here is that Vega-Lite tries to merge different branches of the dataflow and thus has to hash the dataset to see whether it's the same as another one. However, this hashing has the overhead that you are describing. 

I see a few options here. 

You could:

* Use a top level dataset and a named data source as explained in https://vega.github.io/vega-lite/docs/data.html#datasets
* Instead of inlining the data, use a named data source and pass the data via the vega view api

We could improve Vega-Lite:

* Only hash when it's actually necessary. In other words, you would still see the overhead when you have a layered chart for example but not if you only have a single view chart
* Reimplement the whole logic and use comparison of objects if possible. This could reduce overhead quite a bit. 
* Don't hash large datasets and just assume they are different. This could be problematic but at least would reduce the overhead.

**Comment by chrisyeshi** [comment]
Correct me if I am wrong. Since I want the same dataset to work across multiple Vega-lite specs, the first approach doesn't work for me, since a top-level dataset can only be reused within the same spec.

I should definitely try the second approach though, which is using a named data source and passing data via the Vega View API. I will update once I get around to give it a try. Thanks.

**Comment by chrisyeshi** [comment]
I tried the `named dataset` approach and it works. With my new understanding, it seems the `top-level dataset` is basically the same as `the named dataset`. The only difference is that the `top-level dataset` specifies the actual data in the spec while the `named dataset` specifies the actual data through the `Vega View API`. I am not going to try the top-level dataset approach because I am no longer on the project and I am lazy :P, but I believe you are correct. I will pass the knowledge to the current project members. Thank you very much for your support.

**Comment by domoritz** [comment]
You are right. The advantage of the top-level dataset approach is that you don't need to have access to the view API (you can do it all in the spec itself). 

Having said that, the data processing in Vega-Lite is not optimal and should be improved to handle this case better so that you can just use inline data.

**Comment by domoritz** [comment]
I'm going to fix this now with the second approach: reimplement the logic with a different approach.

**Comment by domoritz** [comment]
@chanwutk Do you have some code for me to test my fix? I removed the need for hashing so it should be much faster now. We are still going to iterate over the data when we run a comparison but I hope that this will be less common. Also, when the objects in two datasets are the same, we will just merge them without iterating over the data. So unless I missed something, we have eliminated this issue.

**Comment by chrisyeshi** [comment]
I don't think I have any code that you can just use as a test case, but I can provide the related code snippets. I hope that helps.

Since I switched to using the named dataset approach, the current code looks like:

Caching the dataset:
```javascript
$.get('/data/GlobalTerrorism.csv')
    .then(text => {
        const dsv = d3.dsvFormat(';');
        const data = dsv.parse(text);
        this.cachedData = data;
    })
```

Running vegaEmbed:
```javascript
vegaEmbed('.vast-vis', spec, this.vegaOpt)
    .then(result => {
        result.view.insert('GlobalTerrorism', this.cachedData).run();
        return result;
    })
```

For your test, I think you can just replace the second piece of code with:
```javascript
const injectedSpec = {
    ...spec,
    data: { values: this.cachedData }
};
vegaEmbed('.vast-vis', injectedSpec, this.vegaOpt);
```

If I remember correctly, I was using the global terrorism dataset from Kaggle: [https://www.kaggle.com/START-UMD/gtd#globalterrorismdb_0718dist.csv](https://www.kaggle.com/START-UMD/gtd#globalterrorismdb_0718dist.csv)

And the spec is a simple bar chart:
```json
"mark": "bar",
"encoding": {
    "x": {
        "type": "nominal",
        "field": "iyear"
    },
    "y": {
        "aggregate": "count",
        "type": "quantitative",
        "field": "*"
    }
}
```

**Comment by domoritz** [comment]
Thanks! This should be fixed with the next release.

**Comment by chrisyeshi** [comment]
Thank you very much!

**Comment by chrisyeshi** [comment]
I guess I will leave it to you to close the issue? ;P
