### ISSUE TITLE
. in field names breaks with quantitative

### ISSUE THREAD

**Issue by Alcampopiano** [vega/vega-lite#4150]
I know this axis title is too long but wanted to bring this to your attention.

[Works](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6baRHIAmALgBakAsADEwDRS0Fq3WkDMLAL6DW4KJQCG1CaRzwJAWwKlIk6QFoAjIgkMGAdgCcAJgIBWCRLOb9mgpqabjiAGwAOTW-1nDms8pExSAUJACcAaxUAIzDIUQhIAng4SmR4dCxQCASAD1lIagBPAAdlLEh4WAU0iQAbOKgUAlrKFRlA7KhC-KLSlQBHAFcJeGpkaTHcZXZIJpaVAEFiyEExDqgAEgBnaE4QlR5qYq2MAHpTqdQJADpUcdpBqOvkWFOdvYkLgiv1WvGCC7Ga4ua5Ma4AKy2CDiQTUEi2BGoW1kYgScK0Oj0RlMFisNjsDicrg8Xh8fjKYAA2qjsjgZOUFg1IEtSMY3OtOnSVAAhJksrBmMwc2mQelQADCfOWWAYfGFEC55QAIlLSL55WQxZAAKKqrAeDWKqAAMT1YDMcvinU1KgA4mbNIZDaKVAAJM1eZ1agCSZrMxlWnQAumsQIIgA)

[Doesn't work](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6baRHIAmALgBakAsADEwDRS0Fq3WkDMLAL6DW4KJQCG1CaRzwJAWwKlIk6QFoAbHwCclAOwBGTQCYArE0Qm9+yQQbmC0SnwAciPgCMrZyCLGQChIATgDWKp4hkKIQkATwcJTI8OhYoBCxAB6ykNQAngAOyliQ8LAKyRIANtFQKARVlCoy-hlQebJibbmFxVAAjgCuEvDUyNJjuMoxbXWEjSoAggUFwbCZyEHUDXlgtLBEYEHwu-uDwQDOYBJgkruUsGB5sINgF0XwlGAIb7DQyNUjgQkjcABQEAB0qAh7AAkvALtJUMFFOwACoUajbYLsADK8gK0FoUnYADEJNACJ5YLBQuwCNRoBCAJQAfkgXTAgjErSgABILkSCEEVDxqAULhgAPRSqaoCRQ8a0QaeCHIWBSwWcIKygjy9RVcYEWUmCGaCFMCEAKwuCGiATUEguDIunW6jq0ugMxnMlmsBjsDjMThc7i8PlIAG1ORB0rNYjISot7fHYstVutNlIdnsDkcRqcXpdrrcJPdHs9Xu94l8frb-oClCCwOCoTCwPDERJkaiwBjxti8QSiSSwOTKdTafTGSz2VgTK4Y1yZm04-HIImoAAhFOpyDptYbLY5-aHY6F85XG53W4Vl5vD61+C-BtVIHN1vQuEIpEohTozFBzAfEJEJYlqDJCkqRpOkwAZJk2VIMwzCXXlVyXBMVAAYV3dcD0zY8qkLM8C1zS8SxvB4nnvatPm+Z96wBN8mwBFtIS-Dsf27P8AIHAgcWA4dwMgicYOnBC5zABg+FQlcMjXWYNxUAARXDFPwo9syI3MSJOMji2vMtb2oqtH3ol8mPfVjP3bTtf17fssX4odQJHCCxygydYPg2dSB0QxZKXBTuk3SAAFE1O6DSs22bTT3zPSzgM0tyxMh8a3MxjG2Baz2Nsrie3-PtAOcwTXOEjzRKnOCZ0QrBXAC+M0PkjCoFC0lIoyfcVkPGKTzzc99KvFLjMrdK6LrP5LJYsE8u-LtCt4pyBJAsDR3HaDqp8uqwDMGSmrk2NWqUkoAHFOrTHqCK04iEovZLKLvUyMsm18rNmtt5vsorHKA1a3JEzbvNqyTDB0QL42CrrQoACQuqBosI27BqS4bHrS2inws7KPzmziFp44q+JWoT1s8sSaok0hXH0CHZihzCSlheHuozTTYuR0jUYooyqLGzHMqmnHcs+-HvqWv7SfcjavPE3ysDMExUM5ABdHkQEEIA)

**Comment by domoritz** [comment]
The issue is the `.` in the field name. See https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6baRHIAmALgBakAsADEwDRS0Fq3WkDMLAL6DW4KJQCG1CaRzwJAWwKlIk6QFoAbHwCclAOwBGTQCYArE0Qm9+yQQbmC0SnwAciPgCMrZyCLGQChIATgDWKp4hkKIQkATwcJTI8OhYoBCxAB6ykNQAngAOyliQ8LAKyRIANtFQKARVlCoy-hlQebJibbmFxVAAjgCuEvDUyNJjuMoxbXWEjSqIsLAAOisAdJHBkF1ggmKtUAAkAM7QnEEqPNQFJxgA9PdTqBLrqOO0g57ryLD3ZxcJE8CC91FVxgQniZ1pp1kx1gArE4IaIBNQSE4EagnTrddFaXQGYzmSzWAx2BxmJwudxeHykADauwg6VmsRkJQAgqi2bElrBNlEsCZXMy9jM2qy2ZAOVAAEI83mQfmC7ZYMxmMWHSVi9kqADCiulKq2jD4WolGSlsxlKgAIkabSahWAdIYLWLrd1ZZAAKKO7rOtVgVzutnaq26qA+gBiAYyyuWqtIZnN4ctLKjtpKAHF43yk6asIYdB62V6Ez6ABL5uqFl2ufRl2YVvUlACStcTAqLYDMJi1uwAugcQIIgA. 

I think this is a regression where we don't generate the right transform.

**Comment by domoritz** [comment]
Actually, this is correct. Look at https://vega.github.io/vega-lite/docs/field.html for details about escaping.
