### ISSUE TITLE
Using scale in tooltip "works", but does not pass validation 

### ISSUE THREAD

**Issue by ijlyttle** [vega/vega-lite#4218]
Using 3.0.0-rc6, this spec does what I want it to do - using a scale in a tooltip, but it does not pass validation (try at editor):

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {
    "url": "https://vega.github.io/vega-datasets/data/seattle-weather.csv",
    "format": {"parse": {"date": "utc:\"%Y/%m/%d\""}, "type": "csv"}
  },
  "transform": [{"filter": "datum.date <= utc(2012, 0, 7)"}],
  "mark": "point",
  "encoding": {
    "x": {"field": "date", "type": "temporal", "scale": {"type": "utc"}},
    "y": {"field": "temp_max", "type": "quantitative"},
    "tooltip": [
      {
        "field": "date",
        "type": "temporal",
        "scale": {"type": "utc"},
        "format": "%Y-%m-%d"
      }
    ]
  },
  "config": {}
}
```

FWIW, this is the same "flavor" of error found in #3350, using this [spec](https://github.com/vega/vega-lite/issues/3350#issuecomment-362649271): it works, but still throws a validation error.

**Comment by kanitw** [comment]
Not sure if it really works. If it does, I think it only works if there is only one field because we don't really have the logic to handle when there are multiple tooltip fields yet.  

Thus, I don't think this should be fixed. 

If you want a support for tooltip scale, please feel free to file another issue. :)
