### ISSUE TITLE
Proposal: Remove temporal type

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#4257]
I am proposing to deprecate the `temporal` type in favor of a general `temporal` property on encodings. I propose this change because

* Conceptually, the type (ordinal, quantitative) seems orthogonal to whether data is temporal or not. 
* Temporal is just quantitative but we create a different scale and axis.
* Right now, the `format` property is either `timeFormat` or `numberFormat` depending on the `type` or `timeUnit` but it's not possible to format ordinal data that has a timestamp. 

I think we can implement this in a backwards compatible way where we set `temporal` to `true` when the type in `temporal` and set the type to be `quantitative` instead. 

Thoughts @kanitw @arvind @jheer?

**Comment by kanitw** [comment]
Basically you're proposing that for temporal field, users have to do:

`{field: 't', type: 'quantitative', temporal: true` instead of a simpler `{field: 't', type: 'temporal'}`.

I think this might be too complicated and introduce unnecessary breaking changes.  

The problem that you state can be fixed with a simpler `formatType: 'time' | 'number'` property, which should be used via `ordinal` type only.  (Basically formatType is number for Q, and time for T.)

**Comment by domoritz** [comment]
Yes, that is my proposal. Time unit would be as concise as before but the case you describe would be a bit longer. 

The temporal type bothered me for years because it's semantically orthogonal to quantitative/ordinal. For example, why don't we have a `temporal-ordinal` type?

**Comment by kanitw** [comment]
> The temporal type bothered me for years because it's semantically orthogonal to quantitative/ordinal. 

It's not entirely orthogonal.  Based on type of measurement, our treatment of quantitative types are more like ratio scale (zero is not arbitrary, thus log/power transform makes sense -- that's partly why we auto include zero for Q, but not for T).  While not all Q are ratio, they are more likely to be ratio than interval.

On the other hand, temporal data is naturally interval (zero is arbitrary and doesn't make sense for log / power transform). 

------------

I agree that VL's type system is multi-faceted.  That said, I'm not convinced that this proposal is beneficial for both users and for maintenance of VL.  Basically, `type` in Vega-Lite is essentially higher-level categories of scale type with some affects on the scale range.

- Nominal and ordinal types use ordinal scales with different types of ranges for color. 
- Temporal uses time/utc scales and automatically apply time formatting for labels.
- Quantitative uses linear scale by default but can use any of the quantitative scales and sequential. 

When we use time unit with ordinal type, it uses ordinal scale and thus makes sense to have ordinal type.  Plus, raw time with ordinal type doesn't really make sense. 

It's gonna way harder to explain to users why temporal data would use `temporal: true` rather than `type: temporal` like other types of data.  In a way, temporal is a special case of interval-quantitative, but most people who don't think about it that deeply. This proposal will simply just confuse people more. 

Plus, I believe that many existing logic already check `type` so introducing this complexity, not only will confuse users, but may also introduce new bugs due to refactoring.

**Comment by jheer** [comment]
Similar to @kanitw, I'm not seeing big advantages to the proposed change, but I do see multiple downsides, not least of which is user confusion...

**Comment by domoritz** [comment]
Thank you for the comments. We will implement `formatType: 'time' | 'number'` only then (as discussed in the meeting today with @chanwutk).
