### ISSUE TITLE
Add labelOffset and titleOffset to header config options

### ISSUE THREAD

**Issue by tedsanders** [vega/vega-lite#4519]
Today I learned from @kanitw that the labelOffset and titleOffset fields in the header documentation are erroneous and don't actually do anything: https://vega.github.io/vega-lite/docs/header.html

I would love if these were turned into real fields. Otherwise, the labelAngle and titleAngle are basically useless fields, since turning a label horizontal will jam it into the axis. Would love love love if there was an offset.

**Comment by kanitw** [comment]
I just look into this. We actually already have the properties, but they are named `labelPadding` and `titlePadding`.

So previously, we mistakenly write label/titleOffset in the docs instead so they didn't show up. 

(We named them `-Padding`, rather than `-Offset` since `axis` also have similar properties.) 

The docs will be fixed in https://github.com/vega/vega-lite/pull/4581
