### ISSUE TITLE
Expose `interactive: boolean` in Vega-Lite

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#4567]
From all the discussion about the line hovering problem, I wonder if we should expose the mark `interactive` property in Vega-Lite? 

If so, should it be a property of the mark definition block?

```
{
  mark: {
    type: 'bar',
    interactive: false
  },
  ...
}
```

cc: @domoritz @jheer @arvind

**Comment by jheer** [comment]
I don't have a strong opinion, but I wonder if this is really necessary. The central question I'm curious about (for @arvind  and crew to answer) is how the selection logic should appropriately limit which items get considered by the event streams.

**Comment by arvind** [comment]
Yeah, I’m not yet convinced exposing this property is necessary (if the primary motivation to do so is to address #4255, #4260, and #4264). Selections should do the right thing in these cases rather than expect (non-obvious) intervention from the user. It should be fairly straightforward to restrict selection event processing to sibling marks, and I have a student investigating whether this strategy works and if it has any knock-on effects.

**Comment by kanitw** [comment]
Let's not do this for now.  We can revisit this if we find a stronger motivation.
