### ISSUE TITLE
VL3 breaks null filtering for scale domains

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#4798]
This chart creates a y-axis that is much too large:

```json
{"mark":{"type":"circle"},"data":{"url":"data/movies.json"},"encoding":{"x":{"field":"Rotten_Tomatoes_Rating","type":"quantitative","bin":{"maxbins":20}},"y":{"type":"quantitative","aggregate":"count"}}}
```

If I add an explicit null filter, I get the correct scale domain:

```json
{"transform":[{"filter":"datum.Rotten_Tomatoes_Rating!==null"}],"mark":{"type":"circle"},"data":{"url":"data/movies.json"},"encoding":{"x":{"field":"Rotten_Tomatoes_Rating","type":"quantitative","bin":{"maxbins":20}},"y":{"type":"quantitative","aggregate":"count"}}}
```

This appears to be a regression that violates the expected behavior from VL2. This breaks our curriculum examples and I'd like to request that it be an immediate priority for a fix and patch release.

**Comment by domoritz** [comment]
Related PR: https://github.com/vega/vega-lite/pull/4032

**Comment by jheer** [comment]
Looking at the example gallery - particularly https://vega.github.io/editor/#/examples/vega-lite/rect_binned_heatmap - it appears that this is not a bug per se, but rather an explicit breaking design choice that was made for VL3. Unfortunately, I don't recall discussing this at any point and it is not clearly indicated in the [VL 3 release notes](https://github.com/vega/vega-lite/releases/tag/v3.0.0).

The problem is that this choice causes biased and confusing scale domains, with _no indication that there are missing values causing the bias_. If the chart properly visualized invalid values (e.g., plotting invalid values along the margins, as in [these](https://vega.github.io/vega/examples/histogram-null-values/) [examples](https://vega.github.io/vega/examples/scatter-plot-null-values/)), I would be comfortable with a change.

Suppressing invalid values introduces its own kind of bias, of course -- but right now the design is neither here nor there. If we don't have a proper solution, I would vote for reverting to the VL 2 behavior.

Thoughts?

**Comment by kanitw** [comment]
I think about it more -- there are at least 3 possible things to do with null/invalid (e.g., NaN) values:

1) Hide them -- This is what we currently do.  I think the change in #4032 was motivated by the problem when people iteratively explore data and add a new variable and then scale domain on existing encoding channels suddenly change because the new variable has a lot of missing values that cause a lot of data points to get filtered. 

2) Filter them -- This was what we did in VL2.  This is apparently better for the problem you describe above.  

3) Properly visualize them values on the margins like you mentioned -- This is probably what we should do, but it requires some amount of work to make it systematically work across mark types.  See https://github.com/vega/vega-lite/issues/2544#issuecomment-478265017 for further discussion.  
  
-------

I think 1. and 2. are both problematic, but I agree that 2 is a bit better given that a problem with standalone plot should be get a higher priority than one with plot transition.  

That said, I think we should explore 3 when we have more time,  but for now I'll revert the behavior and consider adding special text indicating when there are values filtered.  Any preference for where should the text be? (Yes, the null would have its own style and be configurable.)

Btw, I just notice that the "152 null" text in https://vega.github.io/vega/examples/scatter-plot-null-values/ is a bit confusing since they only count values that are null on both x and y.  (But the text may mislead that 152 is the count of the grey values along the x- and y-axes too.)

**Comment by jheer** [comment]
Agree that reverting to 2, and upgrading to 3 in the future after more in depth work makes sense!

Also agree that the Vega example is not the one we should necessarily model directly, but it is illustrative of a general approach.

Thanks for looking into this! I’m facing some time pressure getting our curriculum in place with the spring quarter starting next week.
