### ISSUE TITLE
vconcat selectively fails when using selections

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#4866]
A [spec using vconcat and interval selection](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEBuDGD2A7WBDALpAXGA2uCYoBBkAtigE4DWWh+xEkaAngA4CmtksAlhbABtO9AgF8ANCMbtk8ACY9EAc1pEGjAB6qpDSADMe7AXK4AleGjQyA+gBV45NPHYBna6fSKVk9cSZtObEgARwBXFEQ0HjRPaGFfMAkdRmZtBMYDIxMggEkAWQARACF3T2VIH3T-Di4wiKiYqLjIZMTK9SZ4eAEo1jSqzOMuW2ihCtbGFhqgxAdFFAEWhKSEyHhWFF4WftXoBdDAsAAGADojgFZ2324kBSikHaqXI3ZYe8QuZ4EAZnPx9JIewEB1opwA7OcJolWqIdLDiCsCGo-ORqI8-FNDpAAEaUJYMRF+L6vd7okhfX5kjEBLiKKwUIH-KoyBAKZQuWh4AGafEJAC6MLhV2ksjZKmwyN0WglUP0hiGQVMLxQz2sBXQnGFukxXCspFY8AoCyZqyipHYAFVENEuMx2HitRjRliAGI8ASkFxgbHMMBKoQq9hgACa9oovIJjqgqRlAOqWLqkWisU1spQSiUFHYSg1XAQoUiJuuDTG2EQoQEAkF6kJJAAFuweEo6xhsOcjiJ4WA+ZVIHJ0ChHpBQhRFkF+zEAPSkeDQQwuE4AKxcD3wiMgLg2vHKbZAoiAA) "crashes" when the selection is defined in the second chart and used to modify the first chart. The resulting error message is `[Error] Error: Undefined data set name: "concat_1_main"`.

If I [remove the selection condition from the first chart](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEBuDGD2A7WBDALpAXGA2uCYoBBkAtigE4DWWh+xEkaAngA4CmtksAlhbABtO9AgF8ANCMbtk8ACY9EAc1pEGjAB6qpDSADMe7AXK4AleGjQyA+gBV45NPHYBna6fSKVk9cSZtObEgARwBXFEQ0HjRPaGFfMAkdRmZtBMYDIxMggEkAWQARACF3T2VIH3T-Di4wiKiYqLjIZMTK9SZ4eAEo1jSqzOMuW2ihCtbGFhqgxAdFFAEWhKSEyHhWFF4WftXoBdDAsAAGADojgFZW0R1r4hWCNT9yah3dKcPIACNKJYZ7vxcRnYsCiSFeAKMAGZzuC3gEuIorBQ9ot2r5IDIEAplC5aHh0iQtBMwABdK43NHSWTYlTYR66LR04n6QxDIKmIEoQHWAroTiUuHTKBWUiseAUBbjAlMHikdgAVUQ0S4zHYPwFfgaYyCADEeAJSC4wJ9mGAOUIuewwABNNUUX7qf66VJM6XvWrhSLRWL85koJRKCjsJR8rgIUKRKVVLWHRChAQCcmOgWQAAW7B4SlTGGw5yOIlupMqkDk6BQr0goQoiyCpZiAHpSPBoIYXCcAFYuMH4e6QFwbXjlXMgURAA), the error goes away (though of course the selection no longer has the desired effect).

If I [reverse the order of the views](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEBuDGD2A7WBDALpAXGA2uCYoBBkAtigE4DWWh+xEkaAngA4CmtkARpZPQQC+AGgGMAzuwA27WGgCWSWkQYTpAZgCsysQyZtO2SPMRp2FaCimRRq4pHbJ4AExMBzcbTx29AD34+EAC6uhCCuiK6Dk6uiG46PpD+2CqJAGby0s5cAErS7CiSAPoAIuictoH6HFxmpKzwFFY2oSQKpOwAqojyGEbMBRQtgVAKaDJcAGLyUqTiYNzMYHkyhexgAJqDAXaRicwJVSw1RgCOAK4opr3o8tAVrYwobm4U7G7lXAjnpsNHvRNsIhzlIpK1wqo9noABbseRuaF9MCaAAMAihEFSJHI1EOqmqhigsHkFFgEwilXsjgQsXiKVaSTxdkgGSyuXgaDMiCKABV4OQ0PB2OIijlbnE-oljoTIBcrmNbvcdpDKXoDvSRizMlJskYAJIAWRKACFReL4qr8dKuHLrmhFZxwZa2vB4FIFKwmfjWTquDyAQ9NdajIh+SZmk6GfBWChiSwvXpLFJzoSUQA6FGaZ32BCIVwKJQakZQSQyOSKRBcUtaSVVJMp2jpgDsmkeYAhuwi6PwQUqkGc6BQTMg5wo1iMA-tAHpSPBoJlxGmAFbiJT4KGQcQx4kS7CtwRAA), the error also goes away, suggesting that underlying VL compiler error is sensitive to view ordering.

**Comment by arvind** [comment]
Closing because the error no longer seems to occur at least as of Vega 5.17.1, Vega-Lite 4.17.0. 

(The field names in the dataset also appear to have been changed since filing, so here's the [first spec with updated field names](https://vega.github.io/editor/#/url/vega-lite/N4Igbgxg9gdhCGAXEAuA2qAtvATga1VEQE8AHAU1RAgEscIAbSgXwBoRy4oATGmAc0IgAHkIBmNcg25UASlESJOAAgAqUbIijkAzstlI+g9iQpUAjgFd4MRDUSGwLdsXGTpVAJIBZACIAhfUMBEBMyShQQKxs7BzsnEDYQLSgGO1I3KRlI1XsmUOTwqhgNPngGRPYoUnhaEiEwcssIgAYAOhaAVnZoGF47WCEdKXIIAZgqYYYAZk6CxoZm1HaAdk7mDbYsXAIUIiLIgCNcSpAp0fGhqVmhUwiQPiUcBYLOaF4BHVQ0ERAAXQ27DePCMQlEexAEiychG8GGyl8SEoYTMkSUmFIUBw5QKdkw5AAqjB7FRiOQTiY8vcAGI0BiYPSHYj6WHwgCa5Jwp1cELuFmstnsjmRIHg-H4OHI-CRVGgllsuKpqBglgYDEBIAAFuQaPxNcgUJ0Wsw-uxuEh4EJLDgKpFzQ4APSYKBgSQ6NoAKx0gySOhqtBChuYQA).)
