### ISSUE TITLE
Checkbox only works once

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#4870]
Reported by an Altair user in https://github.com/altair-viz/altair/issues/1428

If you bind a selection to a checkbox, the checkbox only works once: [(vega editor link)](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4yghSA3WAbArgKYDOKYA2uBhMJAEK4D2AxgNZmQCCkANFABpkAjH0gBNYQCYAvjyrVaDFu1T1eAspNETUQgAyz5GRUzYduowagDM2sgFZD1GvVMqoddZCtgALHdRJAyMAXSonKABbWAAnd1p4AE8AB0IOACNYrwAzAEtcXEJoMngYogjIQgA7ZkZoXKqAczJ0DEhaphiWo0w8wlxi1SUzOWcoJNSOKsZIhrxeHqhaqvr4XMYqluw8Ig5cXMaAC3hGmNhEr2J+wmY1jY4AZUPGAHdIaSMIzAAPLYm01SMGL1KrzUR9AYcQRfKAXVAJFIAqAAR3wsCqa0QaywaXBuX6gygEg+EAqV0Kt3Wm3hRkgT1e3TGkH+HGIDUahQWTOqtRBjVIqHI7UYnUgIVGzkg6QahNoDWS+HgHGYhxurHSjF+JIw2o+0iAA)

1. Click the checkbox once, and points change color.
2. Any subsequent change to the checkbox has no effect.

Chart spec here:

```json
{
  "data": {
    "values": [
      {"Block": "A", "X": 1, "Y": 12},
      {"Block": "B", "X": 2, "Y": 10},
      {"Block": "A", "X": 3, "Y": 5},
      {"Block": "B", "X": 4, "Y": 20}
    ]
  },
  "mark": {"type": "bar", "filled": true},
  "encoding": {
    "color": {
      "field": "Block",
      "type": "nominal",
      "condition": {"value": "lightgray", "selection": "Show"}
    },
    "x": {"type": "ordinal", "field": "X"},
    "y": {"type": "quantitative", "field": "Y"}
  },
  "selection": {
    "Show": {
      "type": "single",
      "encodings": ["color"],
      "bind": {"input": "checkbox"}
    }
  }
}
```

**Comment by joelostblom** [comment]
I would also like to see this fixed, so I tried to look into what is happening. I started with [this Vega-Lite spec](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9p3OgENCCvCCgKAtphQhFygLSYATApgBOTAA4zAdgBsmBQssTzMAKw2JdTDABGRmB0fjBgLCByIBoKAE4A1joADhAk4tyYUJB0JEioIBCJCmBwhACeqgTZxNCqaAoANqTayGwAdEbclJj1mGDVUDpdPX0QMWwAjBIR3HWNzW2WkQAeqmWJzSAAjqQKRCVKcGja3PDddDpLs9Mg5XlrG9u7xMrERyAnWPXnyDdXsp3dXr9VRDIGjCZTO6ldaDHI9d4gPwkb6gEiJUjiH5gRi9OJ+CArWSRPQKLqESiqEmGEzmKy2BxOFxuTzeXwBIIhMIoADaoEuDRQXF+AuQ+jaRgk7ncljYRjMEi87hYlncZjkfKuyHG3FKmraNnsNiM4zsHDs7glbE86pA-PqKA6wvtovG7XGbDMMssNgm1jMbAkRhtdskOr1rRYntskbsliMLGNRhVwc1LDDItdsZYXiM9mllnYdlzKZF7nTzqMrRscbsRsDEmz4yMExLzrs5ZQrpcbB9saLdibUklrZQNg7WtabBVPfGljnMobLAkas4GpFlnH+v9FpYdmX43z8psI+QZnHrp7PrMkYkResLATdmkAF1ZEA) using a checkbox to try to toggle the opacity of the points:

```json
{
  "config": {"view": {"continuousWidth": 400, "continuousHeight": 300}},
  "data": {"name": "data-e2af9e8976eaa83f9f573defb2cdbfc4"},
  "mark": "point",
  "encoding": {
    "opacity": {
      "condition": {"value": 0.2, "selection": "selector013"},
      "value": 0.8
    },
    "x": {"type": "quantitative", "field": "xval"},
    "y": {"type": "quantitative", "field": "yval"}
  },
  "selection": {
    "selector013": {"type": "single", "bind": {"input": "checkbox"}}
  },
  "datasets": {
    "data-e2af9e8976eaa83f9f573defb2cdbfc4": [
      {"xval": 0, "yval": -0.2355802937354859},
      {"xval": 1, "yval": 0.7767216006523057},
      {"xval": 2, "yval": -1.2109808701899032},
      {"xval": 3, "yval": 0.4989749682421285},
      {"xval": 4, "yval": 1.6847327658840627},
      {"xval": 5, "yval": 2.782672323471201},
      {"xval": 6, "yval": 1.8307068626123035},
      {"xval": 7, "yval": 1.0850718888034439},
      {"xval": 8, "yval": 0.7905246391588937},
      {"xval": 9, "yval": 1.0770949362894426}
    ]
  }
}
```
In the [compiled vega code](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhBMkUANZkATmwbiAJmhAB3GHTjSQOJBo01xZNAJk6aG+mgAsABhcz4NMljQBmNzIQmACeADaG6FBwoaFGGkiYKKgA2qDiSAgRIBDRcFCYbMouAIy+APpBhYYAvlJpGVnxiQC0cABMSABmAJxwABzdAOwAbHBISH2+PZ0Cg74acJ1MbVAaTJ1QTkbESKEMcBBoqSAAHjuxqO4gwedozS6Ubb4CAn0ubd2+cwJOfQLdtVAZ12aGKMhuIMulEGI0GbWKwzcwwETxcs0Bp1uqDa4KxzWKj2KLm6bz6gxKA26Ll8bQxwIuvlxkIeThJQ1Zwz6bSc8LafzpWKcTIuBM5TjmbRGrz6rmGkoFkJs1yxbWhXOGcJpvnFxTaJQVF2GwtBlEmLnJnLlw11-meBrQg2NqAJLj+5uKfU9b21Tl8ALqmMhfSdD0GVJRTmGfuK0s+g3tqG6TpdMOJrN8coGTh5w2qAF0MelMtomkgyi4jGIGMooiWEkhWh0ev0hqNxpNprN5otlqt1psjJhlEhxBBOoUEEdQCEcFl7HBxJgaJ0aHBlEYkId0GViGQIPYyiAMTOsivQpg10Y4CccOv0DQIAA1Xb2AAUTQYCGSAB1A6Ff3mACUAAEABkoHAQ+ABiFgGK+ADUH5fr+9IASB4GQU+L4aO+CSfj+yq7GhYEQdBsEXghSEERC-4gEBR4FnmgReOkoRbscRZZOodDbLs+xoMAtQgBIU4gHApCLluIAIGoOQyaQRgMDgTRzhAAAqSnhK+KhqDgr6ASBAD8wE6Up+nAagwHcZgDGFg02g5OE+SFCU5Q7nuB68XsETiAwMQyEwFhaKgoAWDgDA2ZE8CKEwbAnEednFugjl5AURSlIpykJFkxChAAyrk+TsOIABKBxsKEpCvr+KXOel5SVMocC-lIwG-txEgtcBQ77K1PVwIBR4BpxDmFWlrllJgmmGDISkqaNTnjaUZTufuGhlMBACEAC823Ab5MTAcZwArtEGj4MBtVLeUU04OEZSnaE52tec+wXckV0uctq0HgWFn7X5sSJVkn31ZN00PauT2HDIr0RMcJ7aAAokYj3BSAP3rbZw32clY1feUMnmJ0wRGCJKSgOJC6YFuoD7mQrELalBPg3dNSzVlF7aETy7BNV2T42DjXNdIl2CxNt3hH1yj7IN+b5jIyDKAo7H1El0lIMrMMgIjyXBAgsWxIEIThEcxhsBYNlMSAltrvIS4Kag-UyJ0qiTiFIClnWiTlkNYniFAbALAJIBzdlIdsCYUB0KTFM6wckUgJt4SWPQuGJPzoMTcLv4GcBAA++fAblBWLcVakJ5n4vLTnotIYNsN8REDy0gGcNoA8fQKyAZ4XKA7foEOI4QCYTWLn7QSqAoET9032gAMROFAgx9BMfuazQSAlRVcAACIHFAyg0DgS7k7P3naDgFvj0JCzQEfJ-FSH9OM+gKHnJZv7AfBwGvuOyjIEwOnfC78iJ0Var+XOIEf6-gANzARop-EA39f7-0AcA5ChFaJMTaiAKBft4oe2gLsLI8UXZQ3RvSP2sc6ZQBIdoUm5CzoMNuNUNh3diHhFViAEa6AyE62CLObQoQLBjHXDIDQbBkAWBDl7dApZfZMKetoKhQlhyWHhu4OmLFIS6HsI4bu4gaC1idjLOAMgABea42BoH6sDBhg5BFZBEeIMRcQpFIBkR7ORnt6yKJ7hQlhII1EjjIPDbRDNdGeG8DZWoLhrZGJMc7EAVjVC2LMd3JAJwDiiU4aQsmR9qbaFitgKRRgVD2DynQ026BGEgAqcFZJS5FAAGE1DjyIToi4IAog0FCK+OwDgYAEFcHLCRHivGdF2DkGQoQkBMGiFuKZbFzEgA3kkZZMyNYnCRicC8HSrgIAsLs-ZkUrjNJVmgTZqyLFBWvB3DEeSHEyEKKuDpIBwidBsjIBpVT6F8PKUfRpZiZAXLaeoSKETX49LgH0180SsAjJcGMz2EzJCoGubM+ZiyrnTNWes3FKzFZZJOUUy4itjl7LJec4xlyMV4ssXcwhLhHnVPyS8wp7ySkFEnD8oFhKtlLkwDUv8Rg5kLNCFBPYEAYDpN6h87FoQADypBlBzJwHK1ZYL2mQuyF07QvT+mDPoEilFtzND3MuKy-51wClvMTp8759T+X0qJTrOgIqaJisVSqtc6rNWgtpeCjpULdGGvhbCmJpq-bmoWMy+WQA) you can see that the opacity section looks like this

```json
          "opacity": [
            {
              "test": "!length(data(\"selector013_store\")) || vlSelectionTest(\"selector013_store\", datum)",
              "value": 0.2
            },
            {"value": 0.8}
          ],
```
I don't understand why it is testing the length of the checkbox values, but that might the reason it only works the first time, since the selection_13_store starts out empty but is then populated with one value (true/false) and stays constant at one value. Changing that section to the following, gives a compiled vega spec that works as intended (it is even sufficient with just the first part, but I kept the part after the `||` in in case it has some corner case functionality):

```json
          "opacity": [
            {
              "test": "selector013__vgsid_ || vlSelectionTest(\"selector013_store\", datum)",
              "value": 0.2
            },
            {"value": 0.8}
          ],
```

Does anyone know if this change is reasonable and where in the Vega-Lite codebase the generation of this compiled Vega code can be corrected?

**Comment by domoritz** [comment]
@arvind?

**Comment by arvind** [comment]
Thanks for digging into this @joelostblom. What's going on here is that a "toggle" checkbox isn't quite the right use of selections — which are suited for driving interactive logic that is data-driven (i.e., enumerating data values or data ranges). So a checkbox selection would yield the desired behavior if you had a field in the dataset that had `true`/`false` values. 

Instead, for interactive toggles, you'll want to use the new [variable parameters](http://vega.github.io/vega-lite/docs/parameter.html#variable-parameters) that were introduced in Vega-Lite v5. [For instance](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9p3OgENCCvCCgKAtphQhFygLSYATApgBOTAA4zAdgBsmBQssTzMAKw2JdTDABGRmB0fjBgLCByIBoKAE4A1joADhAk4tyYUJB0JEioIBCJCmBwhACeqgTZxNCqaAoANqTayGwAdEbclJj1mGDVUDpdPX0QMWwAjBIR3HWNzW2WkQAeqmWJzSAAjqQKRCVKcGja3PDddDpLs9Mg5XlrG9u7xMrERyAnWPXnyDdXstyFGKaSgoADaoHUWkG3V6hFGEym3D8JG+oBIiVI4h+YEYvTifggK1kAF15EoFF1CCC8noFIYTOYrLYHE4XG5PN5fAEgiEwmDQJcGiguL8hch9G0jBJ3O5LGwjGYJF53CxLO4zHIBVdkONuKVtW0bPYbEZxnYOHZ3FK2J5NSBBfUUB1RY7xeN2uM2GY5ZYbBNrGY2BIjHaHZI9QbWixvbZo3ZLEYWKajGrQ9qWBGxe74ywvEZ7LLLOw7Pm02L3JnXUZWjYE3YTcGJLnxkYJmXXXZKyh3S42H74yW7C2pNL2ygbF2da02Gq++NLAu5U2WBINZwtWLLJPDYGrSw7KvxoXFTYx8gzJP3X2-WZoxIS9YWEm7NJibIgA):

```json
{
  "config": {"view": {"continuousWidth": 400, "continuousHeight": 300}},
  "data": {"name": "data-e2af9e8976eaa83f9f573defb2cdbfc4"},
  "mark": "point",
  "encoding": {
    "opacity": {
      "condition": {"value": 0.2, "selection": "selector013"},
      "value": 0.8
    },
    "x": {"type": "quantitative", "field": "xval"},
    "y": {"type": "quantitative", "field": "yval"}
  },
  "params": [{
    "name": "selector013",
    "bind": {"input": "checkbox"}
  }],
  "datasets": {
    "data-e2af9e8976eaa83f9f573defb2cdbfc4": [
      {"xval": 0, "yval": -0.2355802937354859},
      {"xval": 1, "yval": 0.7767216006523057},
      {"xval": 2, "yval": -1.2109808701899032},
      {"xval": 3, "yval": 0.4989749682421285},
      {"xval": 4, "yval": 1.6847327658840627},
      {"xval": 5, "yval": 2.782672323471201},
      {"xval": 6, "yval": 1.8307068626123035},
      {"xval": 7, "yval": 1.0850718888034439},
      {"xval": 8, "yval": 0.7905246391588937},
      {"xval": 9, "yval": 1.0770949362894426}
    ]
  }
}
```

For your specific question about why we test for the `length` of selected values, it's to support [handling of empty selections](http://vega.github.io/vega-lite/docs/parameter.html#as-predicates). 

Hope that helps!

**Comment by joelostblom** [comment]
Ah I see, thanks for bringing clarity to this @arvind !
