### ISSUE TITLE
Latitude of -90° seems to break the whole map

### ISSUE THREAD

**Issue by christophe-petitjean** [vega/vega-lite#4927]
Tried on online vega editor.

I add a layer with just one point on the airport example. If I set the latitude to -90, the first layer disappear and the whole map just become blank.

Try with this json (if you change latitude to -89, it works as usual) : 
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "width": 500,
  "height": 300,
  "layer": [
    {
      "data": {
        "url": "data/airports.csv"
      },
      "mark": "circle",
      "encoding": {
        "longitude": {
          "field": "longitude",
          "type": "quantitative"
        },
        "latitude": {
          "field": "latitude",
          "type": "quantitative"
        },
        "size": {"value": 10},
        "color": {"value": "steelblue"}
      }
    },
    {
      "data": {
        "values":[{"longitude":0, "latitude":-90}]   
      },
      "mark": "circle",
      "encoding": {
        "longitude": {
          "field": "longitude",
          "type": "quantitative"
        },
        "latitude": {
          "field": "latitude",
          "type": "quantitative"
        },
        "size": {"value": 150},
        "color": {"value": "green"}
      }
    }
  ]
}

```

- No error message

**Comment by jheer** [comment]
In the [Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgB3RgBMW2MAFYADMfURIKRtXwHpp81DHoAnsgBOBgNoaIoCAFQOuh4mDj+gQGQrO5iBpDBoaTojO6E3O54sHTwsBSQvgEAvo6BkBjuANbx8KnwYshqhRbISvDcOoxK1AYRkU7KTHisOo3hzZGQAGaMyGI68WKDzCONpf1QeC6EY1AAjqzoSnjMIYxUBRtgJRMWzifDo723UTNzCziQ9ytP6-2QWx28QORweZwuLxuV0gsEYAC9dsBIBR0GJWLsAIzGKEbSDtJaecLI1Ho+KwPDIObsNGNIoTOmBHF+CYJEJhMB9SYommwbBeJFLbo-MZmJxnR5jEQATmxAF0AvS-lAKtVPrV3PU1izWu1Ot1ntDBUNVgarlA3vNFssJU0zZttrtICDjqcThCrkzJt8beM7dNZpbPt6TUqyoDHc6wW7GpDQ1BYQjesSaQYMSZPWV8Rkk9zSZ9qO5KSoGZESxAS7KQEUgA) I'm not seeing the issue with the map going blank -- the airports layer stays visible for me as I adjust the latitude value. I am, however, seeing an issue where the visualization size becomes extra large due to the projection settings. (You may have to scroll to see the airports or the extra data point.)

Vega-Lite's default setting of a `mercator` projection is not well-paired with showing extreme values near the north and south pole (it cuts off around +/-85 deg). You might try using a different projection that fits your use case. You might also run into undesirable views due to Vega-Lite's automatic fitting of map projection parameters. You can try setting explicit `scale` and `translate` parameters for the projection to exercise more control

As a reference, it can help to include a graticule layer to provide context when making sense of the map. Here's an [example in the online editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgB3RgBMW2MAFYADMfURIKRtXwHpp81EIAnbnOTw8PFTlAR-UHgAnoTIBpCoyM7w6HjczpAaAL6OkGLoQVEGANoaEH4BUDqxmL55hZDUzrGM8KxiYTh4zqzI5RAp7VAYzgDWBgWFgSGNUNTI3LCI6KFqXRawzdy9o2nW+FXIQYlDSeWdAYP+kMV4pWBHAZCszmLhp+ik6IzOhPF4sHTwsBQ7hQcVHr9HCQeAveANOZDSDIJTwbg6RhKagDeZQMTKJh4Vg6UaXCoAM0YyDEOnCGORzBxYUcQwswVmIIAjqx0EovGcvFQ-rtaRV0hzqai6cciSSySCBVTcVCRcNGVAWWyOTVuWiAdDYIwAF54yAUdBiVoGACMxg1FXhGISvn1huNIMWyBJ7CNYT2u32fPxJxKwrpdrdsGw2WAaUx0saZnRNWxMqwIgAnOaALr+LoWixA8Jg6KQvkWWHwxHI-3QilYoVlOVQMWk8kRuM0tH0kbhJXs5iqsLqgvHKVNssBusSmOCmV9q4M1YdlVcnsizPHLW6gaBh1gE0mJcWK3xNcGt3hTawyAe-77DQpkBJIA).

Hope that helps!

**Comment by christophe-petitjean** [comment]
I'm using Chrome 74 with MacOS 10.14.4

What I see at -89° : 
<img width="540" alt="Capture d’écran 2019-05-01 à 11 34 26" src="https://user-images.githubusercontent.com/354149/57012129-5187c780-6c05-11e9-99f5-8216bc20aba2.png">

What I see at -90° : 
<img width="547" alt="Capture d’écran 2019-05-01 à 11 34 45" src="https://user-images.githubusercontent.com/354149/57012151-695f4b80-6c05-11e9-87a4-b2c6361b9ab1.png">

At +90°, I see airport at the bottom of the page with my green point at the top. So I still believe this is a bug for the mercator projection

But you're right, I should probably change projection (equirectangular is working for this kind of point) automatically if I have some point >85% or <-85°
