### ISSUE TITLE
Cannot sort unioned domains by anything other than count

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#5048]
When a scale domain is the union of two datasets (as it can be in layered specs for example), Vega can only sort by count. This is not just a limitation of our implementation but a general limitation stemming from the fact that aggregates over two datasets that may or may not have the same rows in them can cause wrong aggregates. 

See https://github.com/vega/vega/issues/1500 for more details. 

Instances of this limitation are (some of which we have resolved with specific soluions):
* ~~#4522~~ -- Ham: the issue sounds like there is a weird bug for parsing that's causing it
* ~~#4932~~ -- Ham: the issue is for custom sort order, which can be addressed by a different solution.
* ~~#5013~~ -- Ham: the issue isn't limited by this issue.
* ~~#3152~~ -- Fixed
* ~~#3153~~ -- will be fixed in #5049 
* ~~#5028~~ -- duplicate
* ~~vega/vega-lite#4075~~ -- duplicate
* ~~vega/vega-lite#3710~~ -- aggregate node with same groupby should be merged
* ~~altair-viz/altair#820~~ -- fixed 
* ~~vega/vega-lite#3566~~ -- fixed 
* ~~vega/vega-lite#2038~~ -- fixed
* ~~vega/vega-lite#2964~~ -- fixed

**Comment by g3o2** [comment]
This is a pretty severe limitation in practice. For now, I edit the compiled source accordingly and in tandem with vega-embed got an ok workflow out this.

How do other packages solve this issue?

**Comment by domoritz** [comment]
@g3o2 No, it is not a limitation of Vega but an inherent limitation of sorting aggregated values. 

What we can do is to solve specific instanced of this problem but the underlying issue is a mathematical limitation.

**Comment by g3o2** [comment]
I am certainly not acquainted with the underlying mathematical constraints nor do I know about the vega-lite's internal architecture and relationship with vega.

What I do understand is that vega, as a flexible DIY system, is not really limited by those constraints. After all, in vega, you can, manually or by merging several datasets manually, define domains and ensure proper sorting using a single domain definition.

The question is then whether vega-lite should or could offer more flexibility. For example, would it be conceivable to merge systematically domains across layers, given the same encoding channel and field name?

**Comment by g3o2** [comment]
just remembered that vega-lite never sees the data ...

**Comment by domoritz** [comment]
> What I do understand is that vega, as a flexible DIY system, is not really limited by those constraints. After all, in vega, you can, manually or by merging several datasets manually, define domains and ensure proper sorting using a single domain definition.

That is not the case as https://github.com/vega/vega/issues/1500 explains. 

https://vega.github.io/vega/docs/scales/#domain says "Note: For domains drawn from multiple fields, the sort.field property is not allowed and the only legal op is count."

Seeing data would not help in the general case, either, unfortunately. 

To explain the issue a bit, imagine you want to sort the union of two tables by an aggregated value. You don't get the information what tuples in the tables are duplicates. If you want to sort by the sum of some value, you need to know the multiplicity of each tuple though or the aggregate value could be wrong.

**Comment by g3o2** [comment]
What I meant was wrangling the data using transforms, if needed in several datasets, then merge them back into a single one, including the aggregates, then calculating the domain from there. Instead of multiple fields, there's really only one field. Admittedly, this approach could be qualified as bricolage ...

**Comment by domoritz** [comment]
That works in some but not all cases. But yes, what you describe is exactly what we are trying to do.

**Comment by kanitw** [comment]
I've look at all the issues you listed above, none of them is really "sorting by another field when users layer two distinct datasets".  They are either fixed or inherently single dataset (that somehow got structured as multiple datasets).  Thus, the solution is the correctly structure them as a single dataset.

Since we haven't seen a specific case that "sorting by another field when users layer two distinct datasets" and @domoritz already marks this as a `wontfix`, I'll close this issue as there is no actionable item for this specific issue.

**Comment by domoritz** [comment]
I opened this issue and pinned it to avoid a number of new issues that are being created without being aware of the fact that we cannot sort unioned domains by arbitrary aggregates. I didn't mean for this to be a discussion but rather a note.

**Comment by kanitw** [comment]
> I opened this issue and pinned it to avoid a number of new issues that are being created without being aware of the fact that we cannot sort unioned domains by arbitrary aggregates. I didn't mean for this to be a discussion but rather a note.

But all the problem listed are not really inherently multiple data, it's just our implementation somehow mistakenly derives multiple data from single data source.

**Comment by domoritz** [comment]
That's what I tried to say. There is an underlying issue but we can overcome it in most cases but if the underlying issue wasn't there, we wouldn't have to find solutions for the individual problems.

**Comment by kanitw** [comment]
I'd argue that 
1) IT seems like there is no good solution for the sorting by another field when users layer two distinct datasets" case. 

2) As the issues we are listing here are one datasets problem that become two datasets because of other inefficiency. Solving each of the problem correctly would make the output specs have higher performance (as we shouldn't redundantly fork two data sources when it's not necessary).
