### ISSUE TITLE
Revisit multi-selection storage format when there are multiple projected fields

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#5143]
Consider this [spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4yghSA3WAbArgKYDOKYA2uBhMJAIJmSwCMkANFABpkBMAHB0gAhRgCNWAXzZVqtBqiY92XMgFZVgkQtFKpMjHMawlg7qgDMPTWMnTqNekdamyAFlfXtu-QF0qezABbWAAnAGsyWngATwAHQkZYgHsASwA7eEgAqEI0gGMk6HSAc0j9SAAPSMgAMxTCXGhGbkEY+MYAR3xYDJTEeBSsBOzMaOq6hqaFBla4hIU0pMD0vCy7DEgC3CSQ8frGxhFZ9oWlldw18qTY2Dy+sdR0e02ktKKB1+r4EkzHyEXfmhIMQGoQ8h80owQbgwZkJFIoDgCPMwAAGAB05gk+mxEGyLzSdVKj3x0NhKU+fzJ4K+c0YgXwuAGylq+2gpFQ5Ec1h88JAEiAA) which has 

- `x = X`
- `y = A`
- `color = B`

![image](https://user-images.githubusercontent.com/111269/60631593-09c41e80-9db5-11e9-836c-3853de8a4381.png)

If I project the selection on `fields: ["A", "B"]` and select 3 points one by one -- `(a2, b1)`, `(a2, b2)`, `(a1,b2)`.  My intention is that the predicate is `(A === 'a2' && B === 'b1') || (A === 'a2' && B === 'b2') || (A==='a1' && B === 'b2')`.

To store this intent, the selection signal should store the 3 tuples in a long format as `{"A":["a2","a2","a1"],"B":["b1","b2", "b2"]}`.

However, the selection signal currently stores `{"A":["a2","a1"],"B":["b1","b2"]}`, which makes it impossible to replicate the selection in an external tool.

**Comment by kanitw** [comment]
Similarly, [setting `init` to` `"init": {"A":["a2","a2","a1"], "B":["b1","b2", "b2"]}`](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4yghSA3WAbArgKYDOKYA2uBhMJAIJmSwCMkANFABpkBMAHB0gAhRgCNWAXzZVqtBqiY92XMgFZVgkQtFKpMjHMawlg7qgDMPTWMnTqNekdamyAFlfXtu-QF0qezABbWAAnAGsyWngATwAHQkZYgHsASwA7eEgAqEI0gGMk6HSAc0j9SAAPSMgAMxTCXGhGbkEY+MYAR3xYDJTEeBSsBOzMaOq6hqaFBla4hIU0pMD0vCy7DEgC3CSQ8frGxhFZ9oWlldw18qTY2Dy+sdR0e02ktKKB1+r4EkzHyEXfmhIMQGoQ8h80owQbgwZkJFIoDgCPMwAAGAB05gk+mxEGyLzSdVKj3x0NhKU+j3KZPBZXsUDaKMggXwuAGyn0mAmjVIqHIjmsPnW1Eg6T61Xk-OM7EUMpYkCFUC0-PEMp0ykg6p8uIwOuxEiAA) does not work correctly.  

(Did I overlook anything?)

**Comment by arvind** [comment]
Thanks for filing this @kanitw. The specific three-tuple representation you suggest would not quite work because, to reduce code paths and the amount of computation that must occur to resolve a selection, we also use these signals to drive scale domains for bound selections. 

Nevertheless, the more general concern of being able to accurately read a multi-selection predicate is indeed an issue. But I'm having trouble coming up with the right representation for the following two reasons:

1. While multi-selections union within a unit view (like your example above), they may union or intersect across views. When multi-selections are unioned, we can simply append all values to an array, along the lines you suggest. But, what should we do when multi-selections are intersecting? It would be good to have a consistent representation across these two cases.

2. The above issue is exacerbated by the fact that if the same multi-selection is defined within a repeated view and projected over an encoding, it may refer to different fields (e.g., think of a multi-selection in a SPLOM projected over the `x` or `y` encoding channel). 

My current thinking is along the lines of saying we extend the current selection signal with an additional property (e.g., `multiPredicate`) which would be an array of objects whose keys are field names. But, how would we distinguish unioned predicate entries from intersected ones? 

I'm very open to ideas here!

**Comment by arvind** [comment]
Thinking about this more, perhaps the most straightforward solution is to emit the same structure as we ingest for logical composition (`LogicalOperand`).

**Comment by arvind** [comment]
@kanitw, here is what I have working. Let me know if it matches what you're hoping for and/or how to modify it. To summarize, for multi-selections, the top-level selection signal contains an additional property named `vlMulti` which uses a `LogicalOperand`-esque structure to enumerate the entries in the selection store (not, we do not do any de-duping to keep things performant and consistent with the fact that it's difficult to resolve intersecting multi-selections across multi-views as described above).

In single views:

![Kapture 2019-08-14 at 10 14 48](https://user-images.githubusercontent.com/42262/63028245-73d3e700-be7c-11e9-8b10-4cfeadb7b455.gif)

In unioned repeated multi-views (entries just get appended to the `or` array, rather than nesting): 

![Kapture 2019-08-14 at 10 25 51](https://user-images.githubusercontent.com/42262/63029142-0a54d800-be7e-11e9-99b2-917b332a0b93.gif)

In intersected repeated multi-views (an `and` appears at the top level with nested `or` for each selected view):

![Kapture 2019-08-14 at 10 29 41](https://user-images.githubusercontent.com/42262/63029450-9535d280-be7e-11e9-9097-8b20714bb3d4.gif)
