### ISSUE TITLE
y-axis label doesn't render properly in canvas with bound scales

### ISSUE THREAD

**Issue by manzt** [vega/vega-lite#5258]
In canvas, the y-axis label moves dynamically to pad the changing scale of the interactive plot. The y-axis label is static in SVG, regardless of the scale on the y-axis.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24403730/62290300-f1e5c600-b458-11e9-9ef6-f6ff7464c24f.gif)

```json
{
  "config": {"view": {"width": 400, "height": 300}, "mark": {"tooltip": null}},
  "data": {"url": "https://vega.github.io/vega-datasets/data/iris.json"},
  "mark": "circle",
  "encoding": {
    "color": {"type": "nominal", "field": "species"},
    "x": {"type": "quantitative", "field": "sepalLength"},
    "y": {"type": "quantitative", "field": "petalWidth"}
  },
  "selection": {
    "zoom": {
      "type": "interval",
      "bind": "scales",
      "encodings": ["x", "y"]
    }
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v3.4.0.json"
}
```

**Comment by arvind** [comment]
As of Vega 5.17.1, Vega-Lite 4.17.0, I see the same behavior between both Canvas and SVG. The y-axis label does indeed shift due to padding, but it occurs under both renderers and doesn't yield the rendering artifact any longer. So I'm guessing we might have fixed the issue some time since this issue was opened (likely at the Vega level?). @manzt thank you for filing the issue, and please re-open if you continue to experience it.
