### ISSUE TITLE
Duplicate titles under facet

### ISSUE THREAD

**Issue by buckle2000** [vega/vega-lite#5432]
[The example and schema are here](https://observablehq.com/@buckle2000/baysian-bandits#graph0)

Note in the screenshot below, each column/row has its own title. I think each row should share one title.

![screenshot](https://user-images.githubusercontent.com/10850402/66098657-f3bb2b00-e568-11e9-9f06-98cfcd735002.png)

```js
{
  data: {values: data},
  facet: {column: {field: 'i', title: 'arm', type: 'ordinal'}},
  width,
  spec: {    
    vconcat: [{
      title: 'Expectations',
      layer: [{
        width: 180,
        mark: 'area',
        encoding: {
          x: {field:'x', title: 'proportion'},
          y: {field:'y', title: 'probability density'},
          opacity: {value:0.1},
        },
      }, {
        mark: 'rule',
        encoding: {
          x: {field: 'p'},
        },
      }]
    }, {
      title: 'Outcomes',
      mark: 'bar',
      encoding: {
        x: {field:'name', type:'nominal', title:null},
        y: {field:'count', type:'quantitative'},
      }
    }]
  }
}
```

P.S. I also ran into #4680 and #5219 in that working example

**Comment by domoritz** [comment]
This is expected behavior since the title is set for each layered chart.

**Comment by buckle2000** [comment]
How can I set title for each row then?

**Comment by domoritz** [comment]
I'm not sure I understand. Can you be specific about what you want? A sketch would help me answer your question.

**Comment by buckle2000** [comment]
I meant something like `concat: [facet: {title: ...}, facet, {title: ...}]`. However, a specification like this will error out (as in #4680 and [here](https://observablehq.com/@buckle2000/baysian-bandits#graph1)).

**Comment by domoritz** [comment]
Ahh, I see. Can you create a minimal example that reproduces the problem in the editor?

**Comment by buckle2000** [comment]
If you mean the problem of duplicate titles, [here's an example in the editor](https://vega.github.io/editor/#/url/vega-lite/N4KABBYEQCQM4GMAWBTAtgQygLmkgLvgA5zYD0ZAbigOYYB0NAlvkgK4BG9TA9mYqkxVaGALQAbFiioAWegCs4PAHZQANOEhQAJikQAnJkXy9VuKAFEAHhjRFxKMADMe+sAWKkKzVp3oIeNGE6YLFJfGkmODg2PTIAVhkAZgAmdU0IHQx8LFxQSALoSgxxWLgcMABtfMLaqFzoAEF02rqOCpSADgzCgF81MBrWrQaoACEW4a123Hj4noLegF0e-p6oJwwEFHwKocKNphRxbQr6ybr8AE8iFDPXbSZlEqhVjQKoOFuEPYWtSgCygQ2Qq1T+lxYDjOABVIY4XG4nEx9HB8GB9DwAO4XKZQTD6ADWZw4GH0r2G-UG4IOJnwUPMsLp8NcYDgKEB2nRWJxwzxpKJ5hJZOpy1WIF6QA),

**Comment by domoritz** [comment]
The repeated titles are expected behavior. The spec is asking for a repeat inside a facet. The individual views do not have access to their parents and therefore the titles need to be repeated. Also note that we do not yet officially support repeat inside facet. 

If you want a single title per row, use vconcat with facet. 

![image](https://user-images.githubusercontent.com/589034/66768980-c889e300-ee68-11e9-856b-4ee3c5d3b0a9.png)

https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATZAgBOjQnh4qckAKIAPdKkJjkYAGbddYfERLkmLDnXjdUQrSBohJ4UoywsKw6pACs0gDMAExqGpCa6HiYOMCQFOhi0bDYYADaudlQAIJqUOwlSQAcAL6qYBUlkABCtZD1OLGxzQC6rWkUfkrwmSWlGhCgEEtQRnh2nQAqzHaOzo6MurB4YLrcAO6pyxCQDujwyHgluQ6MyGKanZhtkHgAnoTITrOTSMJQFSBjK5QWAA+BPSAYXQAa067HQugh8zAkKWiyuP22gNMWzW9icLlgyEmmhO50u+Nu90eORur3en16fwBQN0ILBYgh6ihkBhVPhiJRpjRGOaWNlEGGIGaQA

I hope that help.

**Comment by buckle2000** [comment]
Thanks, but facet inside vconcat is broken [(editor link)](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATZAgBOjQnh4qckAKIAPdKkJjkYAGbddYfERLkmLDnXjdUQrSBohJ4UoywsKw6pACs0gDMAExqGpCa6HiYOMCQFOhi0bDYYADaudlQAIJqUOwlSQAcAL6qYBUlkABCtZD1OLGxzQC6rWkUfkrwmSWlGhCgEEtQRnh2nQAqzHaOzo6MurB4YLrcAO6pyxCQDujwyHgluQ6MyGKanZhtkHgAnoTITrOTSMJQFSBjK5QWAA+BPeZXSAYXQAa067HQukuUKgyCm3BBSmoT0gvxJLzeH1M9W+fwBnQAjqx0EpVplGFQIc0ERBuctIUtFojVutTFs1vYnC5YMhJpoTudscsbncHuTXu9Pr06YDTMDQeCBcqYbL4TioMi0dTMUrEXi-ITiTlSerKejtf9dVAmSy2UZOc0+Vcg7yNMMQM0gA). Can you point me towards fixing this?

**Comment by domoritz** [comment]
Ahh, that's a bug. I filed this as a new issue at https://github.com/vega/vega-lite/issues/5475. Thanks for the small example!
