### ISSUE TITLE
Support fixed aspect ratio in responsive charts

### ISSUE THREAD

**Issue by donghaoren** [vega/vega-lite#5479]
Related, but not the same as, #4367

It would be great to support charts that have responsive width/height and fixed aspect ratio. Here are two proposals for updating the spec:

**Proposal 1:**

Add an “aspectRatio” property:

```js
{
    width: "container",
    aspectRatio: 0.8
}
```

To have the desired behavior, we specify two of width, height, & aspectRatio. Specifying all of them shall result in a warning and aspectRatio shall get ignored.

To further support min/max width/height, we have to later add minWidth, maxHeight, etc.

**Proposal 2:**

Interpret string-typed width & height as expressions:

```js
{
    width: "container",
    height: "containerWidth * 0.6"
}
```

You can even do the following so that height is always >= 100

```js
{
    width: "container",
    height: "max(100, containerWidth * 0.6)"
}
```

**Proposal 3:**

Perhaps the two proposals can be combined?

**Comment by domoritz** [comment]
Do you think proposal 2 should be

```
{
    width: "container",
    height: "width * 0.6"
}
```

since `containerWidth` is not necessarily a signal?

**Comment by domoritz** [comment]
Or

```
{
    width: "container",
    height: {
		expr: "width * 0.6"
	}
}
```

unless we make this work

```
{
    width: "container + 10"
}
```

**Comment by domoritz** [comment]
Offline, we decided that the cleanest option right now would be to support

```
{
    width: "container",
    height: "width * 0.6"
}
```

The logic is that we 
* Support number
* When we see `"container"`, we automatically create the responsive behavior (expression + capture the right resize events)
* Strings are just treated as expressions

This doesn't break the current behavior and doesn't block us from extending the behavior to support `container + 10` in the future if we automatically replace references to `container` with the corresponding expression.

**Comment by kanitw** [comment]
So @donghaoren further discussed offline.  

The most important point is that there are two aspect ratios.  The aspect ratio of the plot frame (as in #4367) and of the whole drawing canvas (more like the focus of this issue). 

I don't think the latter should be the responsibility of Vega-Lite since they can just set the width/height of the container to have such aspect ratio.

The plot frame aspect ratio seems more important. 
But as discussed in #4367, 90% of the time, users would just want 1:1 or  `"equal"`.


That said,  though I don't think we need this issue, earlier we discussed a few points about these syntax:

## Proposal 1

- `aspectRatio: number` isn't great because it's awkward to specify 10:6 as `1.66666667`. Better use string with colon (e.g., `"3:2"`).



## Proposal 2

Overall, I think it seems a bit too complicated to support expression for the following reasons:

1) It's unclear when we need those `container + 10` use cases given that one can specify such things in CSS anyway.  

2) For designers, it might be more natural to think about `"10:6"` ratio rather than having to specify complex math. 

3) The following example

```
{
    width: "container",
    height: "width * 0.6"
}
```

uses string for both keyword (`"container"`) and expressions.  
We never did this anywhere else in the language, so better keep that the standard. 

4) To support the following,

> support container + 10 in the future 

it would work if we change `"container"` to `"containerWidth"` and `"containerHeight"`, but that's a bit lengthy.  

5) We also haven't used `{expr: ...}` elsewhere.  (We had `labelExpr`, but we should not `widthExpr` because we better put all `width` customization in one property.)

All of these cons lead us to discuss whether we really need it and thus lead to the conclusion above.


@donghaoren  @domoritz 
We can think a bit more about this, but if you agree that we only need the aspect ratio of the plotting group rect. We can close this issue.

**Comment by kanitw** [comment]
Also it's worth noting that the aspect ratio of the plot frame as in #4367 is only useful if we use autosize:fit / fit to container because we can otherwise set fixed weight and height for the frame to have the aspect ratio we want as well.

**Comment by domoritz** [comment]
I agree with most of the things you say. What’s the conclusion? Do we need anything new? What’s the proposal?

**Comment by donghaoren** [comment]
I believe the conclusion is to not add anything new.

One can have a fixed aspect ratio by setting constraints on the container, and specify in VL both width & height to be `container`.

**Comment by kanitw** [comment]
Yep we don’t need a way to control aspect ratio of the container (the main focus of this issue), but we likely need to support aspect ratio of the plotting frame when we use fit sizing (#4367).

Since that’s already tracked in #4367, let’s close this issue.
