### ISSUE TITLE
geoArea support

### ISSUE THREAD

**Issue by WouterDX** [vega/vega-lite#5490]
So, just for info: any plans to include support for geojson expressions as supported in [vega](https://vega.github.io/vega/docs/expressions/)?

I'd want to use vega-lite as a visual parser for geojson. User of my parser has a link to a geojson, so points to an URL, by default this is plotted with geoshape as mark and eg. geometry area as quantitative color. Something like [this spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCjpWebrEYAvZNigAzZmo2QA7owAmLYwDYADM-URIKRtXzHpr9yhbdDxMHFAID1YAJzFjTwJiMlIrVLo8aPQTE25o22DQsXROHj5CEMZ0MQB9AvQU9DzSACZnAEYAdlIMrJy86qtG22rYVkJkaOrqZCUJqsZYZFsGZG4FZQtI01yMPGNgSEJo7nHovABPeJNkEJjkWDVIC-HsSHWVAF8ND8DIDGiANb7J7nF44SDTXSIdAvVRQWAZbgAozgqyISRqeGI5EAdTsDhwbR+lhm8G4tkYSmo+w0HjJYlyNK2HjMyDEtniRxOEzwjHudEaN2qSnQqCMgS2ILBUCU3FQlKqkFpYGJzMiT243DEvMIxgA2sq1QdWezOcdTrz+YL0MLReKoM8UTK5Qq4nCnswxE7IDihpBVWrIhFA5KTRzwZCxRlzgLojdNiH1Y74gBHVjoJS80K8qgJxMOz3egDKAEkAFoAUSV+a+IYAut8QB8gA).

The spec here suggests a shorthand which I like "geometry.area". But probably better to use the transform interfaces in vega-lite, which can handle other vega expressions,  eg.
`
"transform": [
    {"calculate": "geoArea(datum.geometry)", "as": "SIZE"}]
`

**Comment by mattijn** [comment]
If I do:
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "autosize": "fit",
  "width": 600,
  "height": 300,
  "data": {
    "url": "https://www.trafforddatalab.io/spatial_data/ward/2017/trafford_ward_super_generalised.geojson",
    "format": {"property": "features", "type": "json"}
  },
  "transform": [{"calculate": "geoArea('', datum.geometry)", "as": "SIZE"}],
  "mark": {"type": "geoshape", "stroke": "white", "strokeWidth": 1},
  "encoding": {
    "color": {"field": "properties.area_name", "type": "nominal"},
    "tooltip": [
      {"field": "properties.area_name", "type": "nominal", "title": "Ward"},
      {"field": "SIZE", "type": "quantitative", "title": "SIZE"}
    ]
  }
}
```
It works somehow:
<img width="528" alt="image" src="https://user-images.githubusercontent.com/5186265/67591188-2073f400-f75d-11e9-921f-e5190561b5ba.png">

But I've no idea if the `SIZE` value makes sense. I'd to use `''` in `geoArea('', datum.geometry)` since there arise a `Error: Cycle detected in dataflow graph.` in the Vega spec if `geoArea` is combined with `fit` if I use the correct  `geoArea('projection', datum.geometry)` .
<img width="528" alt="image" src="https://user-images.githubusercontent.com/5186265/67591337-7f396d80-f75d-11e9-9a5d-b7d92cbf43cc.png">

Spec for the latter: [URL](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KOlZ5usRgC9k2KADNmCpZHbp4Aa2oAnbqxkATXZADuiZjsURIhdPfuMZal1RTyhnRnsWXQA2AAZY0MgURmp8XQBmeMTYPABPABsdHEh4ZHz8oy97dDxMHABtJQhQCFaoGXRUIqhpVitSgH1YyraoPori-CIScmc5ujwrdD09bis-GvR89E4ePh88Ri2B6trSZ3R10gAmWIBGAHZSReXV9YGL99hWQmQrAeoyBkfy2jFgyHsDGQ3CkshGbUgbwweF0wG8Nl+VjyTj0yBqfWQsAUUDyvycsLk8igPis4NRAF96aEES8ZLAkbpGqNWi1ua1IKTuoi1qhWNt4XzIMgAB6EKxOU6sVD1AA66O4mMOhLVAF0wAAyfVgRXKtVyjV-LWwXWqyCXPEDDpdXUS7l2onFc2axiEuj29COzo6JqjJkhtpowU4kVizBUqWy+XFQHcACCVjxAAoAOTmiTIeCHWTZqkmqHcLqLXIASmJ7qcAGUAJIALQAopB6eGwDqQ12IDrEnmC0W2ZyQ7yEU6hcPCzxKd3IBptKilykOhMoPVwpFEFTkqk8DrO8z+QYUTg0RpqBuFZsc71+sghtna-3Wu-B8YMFZzB6wFyPKLtOTg-n+rokrkZLFLAiDoGSp5eDkBTdPUkAprB8E6F+bp6DYqCrqcdQ9LYT5DCei5AvA3D2N0k6jJAPynHR3YIjkNjmHRkAUFsrBCq47gUXy-LsdwnEAOoRFEl7cbx3R3GGwleAY5SrggWxCtR+RrHWBhlI4noYpaPrWiqfoZgGIGKUpArcNw+SHIQqKsQx163sUwBquJlz2GqODZtmADUJq2l6xm+v6gbOpAg5gGqzbtn5YBIjUmYhfFrZtrqVJqmq1b0pALkQO+3IlR+iEkksbIcg0kZQUKGFwQh1I2Pmc5woZMIjvOna9m0n7ZPAGn-oBzTAUGThaTpFUCvVThrP4t4zfYFboAEznCZARFOI+gzDBVyk+vkBktRaWImSqZmRSBB0kViuiLHx3bWQiVWApNNQ0GsuSFf1Sg4VAhSAg4I0TouKmbiU9nTYu1i+D6Mh4AAMkC1DSWAV7rlsk3bKghCZge+BUtEAAsVK3LEb4zbAuSoOw9kACpzcU8CMP0hQQQKzAc513oRRZUUeJRMjUbRam0-T+T-miTGfWpixiVxPH5HxTgCXgOiMoyfb-Yk1EyAYQQyaYFjWLYDhq24GudiA9JAA)

**Comment by kanitw** [comment]
Vega-Lite’s calculate transform supports any Vega expression.

So I’m not sure what’s the action item here.
I’ll close this for now. Feel free to reopen with a more specific request.

**Comment by WouterDX** [comment]
Hey, mattijn's solution works for me, thx.
