### ISSUE TITLE
Set axis offset to a value from another axis

### ISSUE THREAD

**Issue by lane-s** [vega/vega-lite#5515]
When plotting some functions, I want to have the x axis at y = 0 and the y axis at x = 0. I would prefer that the axis titles stay in their original position, but that the axis line and tick marks go to the specified position. 

I think what this amounts to is something like:
```json
{
  "mark": "line",
  "encoding": {
    "x": {
      "field": "a",
      "axis": { "position": { "x": 0, "y": 0 } }
    },
    "y": {
      "field": "b",
      "axis": { "position": { "x": 0, "y": 0 } }
    }
  }
}
```

Specifying only one value determines the axis position relative to itself, but referencing another axis determines the position along that axis. There could also be labelPosition to override for the labels. I think it would be sensible to keep the label behavior as is, requiring the user to override the labelPosition if for some reason they want the labels inside the plot.

**Comment by domoritz** [comment]
Thank you for the feature request. Can you create a mockup of what you would want a chart to look like? How would we need to generate the Vega spec to make this work?

**Comment by lane-s** [comment]
I can get close by tweaking the `offset` property of each axis.
![visualization](https://user-images.githubusercontent.com/19609843/68091822-e6a19c80-fe84-11e9-918c-9bfece4ccaaa.png)

However, this moves the labels as well, which I don't want. So I think in order to do this we would need to first be able to correlate the pixel values with the data values, calculate what pixel offset we would need to move the axis to the given data value, and then apply the reverse offset to the labels.

**Comment by domoritz** [comment]
Can you create two axes? One for the domain line and one for the labels?

**Comment by domoritz** [comment]
At this point, wouldn't it be the same as adding a rule at x=0 and y=0?

**Comment by tmori3y2** [comment]
Perhaps it means that it is difficult to calculate the axes offsets with vega-lite, so he wants sugar syntax.

I want this feature too.

By the way, `position` is a reserved word and cannot be used.

How about `intersection` ?

Since vega-lite cannot use signals, calculating the axes offsets require some tricks.

For example, [vega-lite](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATZAgBOjQnh4qckAApjueWGHRh4jXfDHIwrWIyXVbYasiXIuuh4yJpgsMgAjqz+8Mh0ahqQAO6MmizYYADMAAw56hCQKIzU+JnSeQVawZg4oBCFEdGxyJn1DY146Lp4mSIAjHl0lRodkLB43ISZgznD-VVjE8jTOHM5C6MNkOiwmZAAHpBbAL4aJ1WQeEFKsABm3LqomQDaW+1jd4xiIbptkF9kGJNPsjqooDc-K8BuCAKwAXTOHQu7y2hXg6DE8FYYmCrVMAzAAGowIRuMkABQUzTBVioOgHMAiMD9ACU4IATKywKQwNJEh1Crt9gBPY7IjTwy4YXQAa32EgCAqgsW4mk81DaW0OWsFUEBwNByrGeBFhHxUGi6CURi6Rioxu26AOjD2dTR21tLiNi0FAMeGF6pjo-TujrG3DudwiQaZ-QAbDkPSi9eMMd73XrCppuBhPNCFmAEcnTr7IGLM36DSDTGLfYVTeb9labcxgowHfWoM7Xbqs1dmBmoHWPYUHk9gvsQ2Gu4VI9HkLGRLCk3qU36EJiLR8-Tm8yYwC8RBzwVl4SXkWXHto-nUAYwgTWoGCoI2LZAW7b2w6kWAzicgA).

The axes offsets can be easily calculated manually by settings the following values to the “nice” values.

- width
- height
- domain [min, max]

In the case of vega, we can calculate the axes offsets without the "nice" settings.

[vega](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KABNkCAE6NCeHnJyQACgBtueWGHRh4jdfCPIwrWIxnULYashnJ16PMmUwWGQAR1YveGQ6BSVIdnR4AGtqdW5WGWVsKAB3RGZkGIhIQnRlZRdqLNFFIuzGZRYsgGYABhaa3GRGanwsgBY2jshYPABPeyzISKMjQpU-TBwAbSUIUAgNqBl0VAL9aVZbZAB9FrnNyDxfGVgAM251VCyVzc3114uxwj2oYLCIgodD5FEbodR4LIAWgAjINVsDhnhuIQsrCWnQWtCgQiRsgUTh0ZjsR9IOhYJMAB6QeGbAC+xI2wEuo2+k1ujCM-nUCigyAphG5+hc108AAplH5WKglgAdSAUuUAXXkYCWMJVokVAEpIPSaYzmaz9PdHqwjJgVZA+QLJjCwABqMCEbjZUXiyWoOgUsCQsDQrUqgBMWrApDAfR5pPJ+lGuv1ivhtKUytizmo2yM0dV8PeF22u0mLi5wXgOlkxwpsYZkAo6CM4We7TALQTdOTQww6kSWZejP1kHzP0gne75w2hqHRhcgP7I3GPyWkCn3kgKZJ0nBWSZ7OQRkyy0gErwUtl8qVq8tD1UgtVUciGQqq71JNuqSeOCZR8WvzSR1OuurCJuFULd9SKVhCCPH5cxxK5uESaCazrBt9AAYj6eAAHYAA50GwgCwPHKkP2GeA6yHKlLR3PdKQI4Fx1jEiEHIyYqygaj9ygWNn3olRkHZbxOJg+jhm6DNC1gAA1Ot6ndY9pTlBVVxDAAyFSwEYWAADEXHyUV7SPE9FKVVT1M06Sp2UOSjMgUYTLANSNO03T-H0wyFNskzqV4sAk3ovzXgCiAArXX4yPsHsc37QdaOrL5J2nMExyKZRuAwFwt0PBZJgOP8zioxhd04+U6NeSARQXJsmTTcT9DqBpEF1UK80YSIsiucJqwALx8bgsluOtgkTbFhK2HYhyrft4smZdkCS6tUvSvQwE-bL9l-SJ-wKorWNKi4KueaqxLrSYUG6Xp6WbZrxxkVqfg65But69r1HCRN21idAKTUZ4ovXcKKOSqAHkKmQIX0dhTCRJ5qxSeoAGUAd22HNE4h64taxIAGE0jBzKapO-RIg5UV6pYUgBh1HiLkW9AMpwAbM0e-tzXYXcs0Z4JqwwCkAFEKX8PGCW5lx+cF8HmwxpIOcG5mSS6lxVGI5thr+srmImGMgcgEGvAlpd+IhFGEaR-RKP7OG0deuWyp0JIcfSCWjvTQmoGJoxRTOno8AploqYWtK6eWzmbYuVn2f62Xua+sW9aydp+1QUWBbj4WpsxmWme6xW+Xj1W3lnU2oHNkldaFqBIYINLtctyOs-TvBNeL7WTQwfW6GhW5te4W5bmCJ3RJd2Z9EhL38AdIIAdFAByUZp5VIsfBLMsZArUYlmhbU9vHcOjC0+tYEanB0ZZ9A2aMAB5Kh1HNfEwBPkk7ex3GB4J4e3a6D2ycQX3-f7BWMi5wJPnPs-0WJa2rGXfW9hbhGwtqjOuXMG5N1si3B4bdJgdy7pA3u-d8bHXfpASEGtkAzwpPPDSYMl7IFLLoNeSwWx-xJLvK+Phb4vU6une2L98FD0mO7T2XRva-23kUABSs85tggKFKYsh2SVBIvEJIKRcbFVyPkOMtIgA)

vega-lite should set intersection_xy according to the new property, but it is a little difficult for concat and repeat layout.

**Comment by domoritz** [comment]
Here is what I was thinking earlier.

![image](https://user-images.githubusercontent.com/589034/68097061-89e4b880-fe69-11e9-9cc3-141728c6dde4.png)

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "width": 300,
  "height": 400,
  "data": {
    "sequence": {
      "start": -10.00,
      "stop": 11,
      "step": 0.1,
      "as": "x"
    }
  },
  "transform": [
    {
      "calculate": "-1 + pow((datum.x - 1), 2) / 4",
      "as": "y"
    }
  ],
  "layer": [{
    "mark": "line",
    "encoding": {
      "x": {
        "field": "x",
        "type": "quantitative",
        "title": "x"
      },
      "y": {
        "field": "y",
        "type": "quantitative",
        "title": "y"
      }
    }
  }, {
    "data": {"values": [{"zero": 0}]},
    "mark": "rule",
    "encoding": {
      "x": {"field": "zero", "type": "quantitative"}
    }
  }, {
    "data": {"values": [{"zero": 0}]},
    "mark": "rule",
    "encoding": {
      "y": {"field": "zero", "type": "quantitative"}
    }
  }]
}
```

We could make this much nicer with https://github.com/vega/vega-lite/issues/1601.

**Comment by lane-s** [comment]
Ideally, it would be possible to put the tick marks in the center as well and skip the 0 tick label. I see the main use case of this as being function plots where you care about where the function is crossing an axis, in which case having centered axes with tick labels helps (particularly for large plots). Having a tick label at 0 on each axis is useless though, because it's obvious that that's the origin anyway.

**Comment by domoritz** [comment]
I see. You can use conditional encoding/formatting to remove the `0` label. I can see that moving the axes could be useful but we won't have the resources to work on it. If you want this feature, please send a pull request.

**Comment by kanitw** [comment]
With the new `datum` syntax, this is pretty nice.

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "width": 300,
  "height": 400,
  "data": {
    "sequence": {
      "start": -10.00,
      "stop": 11,
      "step": 0.1,
      "as": "x"
    }
  },
  "transform": [
    {
      "calculate": "-1 + pow((datum.x - 1), 2) / 4",
      "as": "y"
    }
  ],
  "layer": [{
    "mark": "line",
    "encoding": {
      "x": {
        "field": "x",
        "type": "quantitative",
        "title": "x"
      },
      "y": {
        "field": "y",
        "type": "quantitative",
        "title": "y"
      }
    }
  }, {
    "data": {"values": [{}]},
    "mark": "rule",
    "encoding": {
      "x": {"datum": 0, "type": "quantitative"}
    }
  }, {
    "data": {"values": [{}]},
    "mark": "rule",
    "encoding": {
      "y": {"datum": 0, "type": "quantitative"}
    }
  }],
  "config": {
    "axis": {"domain": false}
  }
}
```

![image](https://user-images.githubusercontent.com/111269/79077320-a22cef00-7cb5-11ea-8f23-04d18d303e9e.png)



With the experimental signal support, we can move axis to the middle like [this](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgB3RgBMW2MAGYADMfURIKRtXwHpp81B3o8mHKAgXYyAI6tkSvDIBh6eXq4ATngGIgCMxnQOGmGQsHjchAaxsY4paciZOAk5yZ6Q6LAGkAAekKUAvhr1jpB4EehKsABm3BGoBgDapaEp8Ohi8KxiLsE4kHFgANRghNyaABTrznisqHTVYCJgsQCUqmAATCdgpGDSaqUWFVUAnnVhjRAAuo4akBgRADWVQkSmCLQC8G4OkYSmoIVKNQRYQsXUYyDEOiqtVyZTwL0Isygfg6eGYLkYVAeKKgZLwYiJSNxT2qjEq7keZWm7AxAFFqoQIlVtrs6BRxv4wABeGVgYxgAD8YAA5MqwDgRXtuRjqTSoNwul1vNF3KlrEpxlURFYbHglmAEONkOtlS9ledjCdIJ8UT6IM1EW8OTTIGiMVi5m9mbSCYySUo6RSqdHWswGa9dWFOeVWeywCMUZBtWJ+YLhS5ReKxJKZVK5YqVWqNRWtegeWJM4WDUbkCb82bqBaO3MRI6GS7qu65V6-Z5Zz6AxYoUo0fDTehcyFINQIroDF1xt56o16kA):

![image](https://user-images.githubusercontent.com/111269/79077502-16b45d80-7cb7-11ea-81fc-1402f2e8663d.png)



Note that this would benefit from allowing us to name scales (https://github.com/vega/vega-lite/issues/6168).

We also track the discussion to make signal an official feature in https://github.com/vega/vega-lite/issues/6189.
