### ISSUE TITLE
Cannot set a theme's cornerRadius* in a way that works for both vertical and horizontal bar charts

### ISSUE THREAD

**Issue by dantman** [vega/vega-lite#5813]
I am trying to create a Material theme for Vega (Lite) bar charts that works with both vertical and horizontal bar charts. However I am unable to specify corner radius in a theme that works with both vertical and horizontal bar charts.

Vertical | Horizontal
-------- | ----------
![Vertical Material Bar Chart](https://storage.googleapis.com/spec-host/mio-staging%2Fmio-design%2F1576174064000%2Fassets%2F1Md92j8E5eRPBXPXghpTiVXNyvvKVC5v7%2Faxes-zero-baseline-do.png) | ![Horizontal Material Bar Chart](https://storage.googleapis.com/spec-host/mio-staging%2Fmio-design%2F1576174064000%2Fassets%2F1Mjxo2honXOC9GJhGfWyj6DNreTG8oRh9%2Faxes-rotate-do.png)

For horizontal bar charts I need to use:

```json
"config": {
  "bar": {
    "cornerRadiusTopRight": 2,
    "cornerRadiusBottomRight": 2
  },
}
```

For vertical bar chart's I need to use:

```json
"config": {
  "bar": {
    "cornerRadiusTopLeft": 2,
    "cornerRadiusTopRight": 2
  },
}
```

As a result I cannot have a single theme for bar charts. It would be preferable if there were a way to specify radius for the bar cap that works both horizontally and vertically.

## Solution 1

The first potential solution I can think of is to add extra corner radius props, following the css RTL pattern of using aliases like start/end instead of left/right.

```json
"config": {
  "bar": {
    "cornerRadiusCapStart": 2,
    "cornerRadiusCapEnd": 2
  },
}
```

Then on a vertical bar chart the top left corner would fallback through `cornerRadiusTopLeft > cornerRadiusCapStart > cornerRadius`. On RTL it would flip to CapEnd instead.

## Solution 2

The second option would be to do the same as Solution 1 but just use one property:

```json
"config": {
  "bar": {
    "cornerRadiusCap": 2
  },
}
```

Then on a vertical bar chart the top left corner would fallback through `cornerRadiusTopLeft > cornerRadiusCap > cornerRadius`.

## Solution 3

The third option would be to add variants of `bar`, the way that `axis` has `X/`Y`/`Band`/`Bottom`/etc variants of the bar.

```json
"config": {
  "barX": {
    "cornerRadiusTopRight": 2,
    "cornerRadiusBottomRight": 2
  },
  "barY": {
    "cornerRadiusTopLeft": 2,
    "cornerRadiusTopRight": 2
  },
}
```
## Solution 4

The final option I can think of is to link up with a comment in vega/vega#1969. It was suggested that for a stacked bar chart the corner radius wouldn't necessarily work out and a clip path would be preferred. And that this might be possible using signal. Though I have no clue how this would work.

If this is something that could work, either via a signal/`clipPath` property and there was some way in a signal to differentiate between a horizontal and vertical bar and someone could explain how. Then we could document this and use this method for specifying bar chart radii.

This would have the added advantage it would automatically work with stacked bar charts with small tops.

And the additional added advantage it would be compatible with variants of the Material theme that use alternative designs like cut corners that can only be expressed using clip paths.

**Comment by kanitw** [comment]
> The final option I can think of is to link up with a comment in vega/vega#1969. It was suggested that for a stacked bar chart the corner radius wouldn't necessarily work out and a clip path would be preferred. And that this might be possible using signal. Though I have no clue how this would work.

FYI, we actually manage to make cornerRadius work with stacked bar chart in Vega-Lite.  Please wait for the 4.1 release.

**Comment by kanitw** [comment]
## Solution 5

I like the idea of following strokeCap like in CSS.

However, strokeLineCap normally means both caps of a line.  
![image](https://user-images.githubusercontent.com/111269/73291536-31e1f780-41b5-11ea-8e3d-70a780939f79.png)

Thus, I'd think that the following charts 


Vertical | Horizontal
-------- | ----------
![Vertical Material Bar Chart](https://storage.googleapis.com/spec-host/mio-staging%2Fmio-design%2F1576174064000%2Fassets%2F1Md92j8E5eRPBXPXghpTiVXNyvvKVC5v7%2Faxes-zero-baseline-do.png) | ![Horizontal Material Bar Chart](https://storage.googleapis.com/spec-host/mio-staging%2Fmio-design%2F1576174064000%2Fassets%2F1Mjxo2honXOC9GJhGfWyj6DNreTG8oRh9%2Faxes-rotate-do.png)


should be both expressed with:

```
"config": {
  "bar": {
    "cornerRadiusCapEnd": 2
  },
}
```

since the top of vertical bars and right of horizontal bars are their ends. 

(Blending the proposed solution 1 & 2).

**Comment by domoritz** [comment]
Sounds good but the name is a bit odd. How would you add corner radius to the bottom of a bar (which doesn't make sense imho so maybe the answer is that we don't support it)? Why not just `cornerRadiusEnd`? 

Another option is to automatically rotate the corner radius and say that the top in on the right when a bar is horizontal. Yes, it can be a but confusing at first but maybe it's easier and less surprising since many designers may not consider horizontal bars and then the design doesn't if they set the radius at the top.

**Comment by kanitw** [comment]
>  Why not just cornerRadiusEnd?

That might be better. 

> How would you add corner radius to the bottom of a bar (which doesn't make sense imho so maybe the answer is that we don't support it)?

The question is for RTL use case, how do we support it.  
Since Vega-Lite doesn't have a mode where the bar start from the right, one possibility would be to allow `cornerRadiusStart` for when bar starts from the right. 

That being said, it might make the most sense to implement only `cornerRadiusEnd` (or something equivalent, but with a different name) for now and consider adding either `start` or proper RTL support later. 

> Another option is to automatically rotate the corner radius and say that the top in on the right when a bar is horizontal. Yes, it can be a but confusing at first but maybe it's easier and less surprising since many designers may not consider horizontal bars and then the design doesn't work if they set the radius at the top.

I don't think this is better than `cornerRadiusEnd`.



@donghaoren @haldenl @jheer @jakevdp @arvind  -- any thoughts? 

(I'd like to add support for `cornerRadiusEnd` or equivalent soon.)

**Comment by kanitw** [comment]
Will be fixed in https://github.com/vega/vega-lite/pull/5818.

Let's discuss the property name in the PR.
