### ISSUE TITLE
Make sort aggregate schema consistent with normal aggregates

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#611]
The schema is different, for some reason.

**Comment by kanitw** [comment]
Can you elaborate?  I do not understand what you mean.

**Comment by domoritz** [comment]
normal aggregate:

```json
aggregate: {
type: "string",
enum: [
"avg",
"sum",
"median",
"min",
"max",
"count"
],
supportedEnums: {
Q: [
"avg",
"median",
"sum",
"min",
"max",
"count"
],
O: [
"median",
"min",
"max"
],
N: [ ],
T: [
"avg",
"median",
"min",
"max"
],
: [
"count"
]
},
supportedTypes: {
Q: 1,
N: 1,
O: 1,
T: 1,
: 1
}
},
```

sort (note the schema for aggregate):
```json
sort: {
type: "array",
default: [ ],
items: {
type: "object",
supportedTypes: {
N: 1,
O: 1
},
required: [
"name",
"aggregate"
],
properties: {
name: {
type: "string"
},
aggregate: {
type: "string",
enum: [
"avg",
"sum",
"min",
"max",
"count"
]
},
reverse: {
type: "boolean",
default: false
}
}
}
}
```

**Comment by kanitw** [comment]
Thanks for clarification. They are actually similar, but not exactly the same!

One design decision in migrating `sort`to vega2  is picking whether we want `sort` to be consistent with Vega2 ’s `DataRef.sort`  or consistent within vega-lite because `DataRef.sort` has a property called `op`, not `aggregate`. 

In #615 I decided to rename the `aggregate` property to be `op` like Vega 2. 
There are a few benefits to this approach:
1) We can explain in the doc that whenever there is an aggregate, a `summary` data table is produced.   However, if we have scale’s `op` we only supply it to the scale — no additional table is created.  
2) `op` is required in the `sort` object — while `aggregate` is not required in the encoding property definition so having different name might not be a bad idea. 

That said, the enum list of supported aggregation functions should be similar.

**Comment by kanitw** [comment]
Done in #621

**Comment by domoritz** [comment]
I like your reasoning.
