### ISSUE TITLE
no tooltip in concatenated charts

### ISSUE THREAD

**Issue by mattijn** [vega/vega-lite#6198]
I added tooltips to this [chart](https://altair-viz.github.io/user_guide/transform/filter.html#selection-predicates). But they only appear to be working on the bottom chart. Observe the following:
![ezgif com-optimize-10](https://user-images.githubusercontent.com/5186265/77833881-de524280-7140-11ea-9f1e-f306c2c32f32.gif)

Created with the following spec:
```json
{
  "vconcat": [
    {
      "mark": {"type": "line", "point": true},
      "encoding": {
        "color": {"type": "ordinal", "field": "year"},
        "x": {"type": "ordinal", "field": "age"},
        "y": {"type": "quantitative", "aggregate": "sum", "field": "people"},
        "tooltip": [{"type": "ordinal", "field": "year"}]
      },
      "height": 200,
      "transform": [{"filter": {"selection": "YEAR_SELECT"}}],
      "width": 600
    },
    {
      "mark": "bar",
      "encoding": {
        "color": {
          "condition": {"value": "steelblue", "selection": "YEAR_SELECT"},
          "value": "lightgray"
        },
        "x": {"type": "ordinal", "field": "year"},
        "y": {"type": "quantitative", "aggregate": "sum", "field": "people"},
        "tooltip": [{"type": "ordinal", "field": "year"}]
      },
      "height": 100,
      "selection": {"YEAR_SELECT": {"type": "multi", "fields": ["year"]}},
      "width": 600
    }
  ],
  "data": {"url": "https://vega.github.io/vega-datasets/data/population.json"},
  "$schema": "https://vega.github.io/schema/vega-lite/v4.0.0.json"
}
```
[Vega-Editor URL](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEBuDGD2A7WBDALpAXGA2uCYoBBkAtigE4DWWhkaAngA4CmtkANgJaJsA0UJvB4ZsaCgFcWAXz75ikFsngATHgHNaRYiQQd4FLfWZtskA2sQoOkAZABmXFhxXsGLSpFnydkAB5GjKzsFjzWtlCOzq5mKOps3jokDIEm7ACOEiiIaFxo6FzQ-FBx6hQs6uimUADOEqQRDk4u7KzwTBwJckkQ9PDwHLlMtDjAxsFmoVY2dlEtZu6e0gC6PhCJvgAWLFzqm6JgAEwADMfdvuLZNfYGDdijTYMshthjNc4ssLlI7ACaAKIAQQASgB9ADK-wAMv8AMIAFS8K3OCgA7lwVGhNrQAGynHwbCDaBTkajsABGnhRJCUCEsmlea10AwMWiZCgQiDU30QRmg1ik7BqaBYznJHEFdnenS+XB+ZgBIIh0LhiMJPRgAuqnF2+zKKBS7LA6oUAVe421U3Cs2aMSgi0MJuSqQmUEy2Vy+VyRUapXKlRFQvqjTmdsgbQ6XSNfQGQxGYyCloolmtkVtbg8jtWSSdkG2uoOAEZTtTetLPjyjIqwZCYQiXdrSBJBlwQ7aaiNIA7IMtpLn0Zjsdg8ccCfhludICp0CgjBIKDYzPs0EwapgAPTroqVAB06jymwk5J3cq3FRQAFpp-l3mgauvryh10ImM2CkgdwArGo-DaQAAkNSwNs5DsMuq4bmeu77liR4nvA65ASBT7bpe3AiluAAsO7HDhX4-ryIDSEAA)
No reason jumps in my mind why the top chart should not respect the `tooltip` encoding.

**Comment by keckelt** [comment]
It is due to the selection.
If i take the [vconcat example from the docs](https://vega.github.io/vega-lite/docs/selection.html#compose) and simply enable tooltips in the mark property that i also have no tooltips in the facet without selection: [Link to Editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvSl46I7HmKVAX3URIFeMut4zAbQ0RQCCCoWGQxZHg8HhV9SHYjVlhEMwM8AE9CZDNIRiU8ZCMKdFNHZ38gyAwjAGtsVIysnEhCblzvVSg8bm4xKMIzPATkMuDXZCUPTVzqFPLgyAAPFMgAM0YwzWyACW5bZBaAdwK1TobsgEdWdDzmHUYqSBHR1zTltY3sgFlGcNgAfUyRj+AHFimJlCdIOlMhcrjddFEHo45mBkcEngEUVCjNdYCtdqhfCjMc95mtesd9MTRpBrpscD5INo8KxUHQAOrIRjUfB-XJ-MTsWBgAB8YAAzAAGaUnAyhcKRaLZeKJZKOAC61IgaNJOuC6pcNKqtSw9RhTRabUhXR6fQGQwxFXGk2ms1JUCWVPdrneYnpUAAgvB4GECncIYb3VCzk1Ltcogj7llI6TIAhio0wAZNNwMLlfJKOgAmACs6r1o0d81eXu9q3WfuyABFGLBCGJ0CHUON2lrTuaoHH4XcHinnmnrOFljm8zEwD5C2AS9Ly9SK9ryjrNY4gA)

After removing the selection and transform it works: [Link to Editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvSl46I7HmKVAX3URIFeMut4zAbQ0RQCCCoDCMAa2wDPABPQmQzSEJuRiVvVSg8bm4xPEZCMzwjVmRnfyDIZCUPTRTqM0Dg8oAPesgAM0ZkMU0EgAluW2QkgHdkIzUM2PicSABHVnRU5h1GKkhSxvLo1o6unpmAWUYxZFgAfTijM4BxdDExZQnIGLiE+cXc3Vy1xzKIX+CGyCDWCkFCESwUSmCSSKTSGSyOTyBSKJRcjQqVW4NSUdX0f2a9QJoN23QSAEF4PAumMVo90ZtXC9plB3ksvqt4gzGZAEHcWQZNNwMClfAAGdIAJgArABdAGMoGbSDbfGM8qk-ZQAAijFghDE6GpqEqaWJ5WZbwW7JWa25yr5J1aQpFKhwPglYGlYrF8vNCsBZQVspAjiAA)

**Comment by prateekkembhavi** [comment]
@keckelt, so for all plots involving selection, it's impossible to view tooltips?

**Comment by keckelt** [comment]
Not all. Just for plots that also use concat and selection. Concatenation alone, or selection is fine.

I haven't checked the linked issues though if anything has changed in the past year.
