### ISSUE TITLE
 VL 4.8 breaks autosize:fit calculation in concat views autosize:fit sometimes doesn't work with concat views

### ISSUE THREAD

**Issue by jheer** [vega/vega-lite#6209]
Take a look at the [linked interactive Seattle weather specification](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQxKHKhJMaANqhkAJwDWaUJgCeOOGhA42NWZqUAzGoMFwAJmkx6GcAL5KcLKq7nZkxiCqgmx6EcRIgr5WwmRYZHpIpoqRcqGY7PKooBBwblD5clYlggDM2c6lnugA7nAa8LFKZhZWsmwIdgnZ0AmWRSDu-Uh22iAQDPJObOFK7no0AF4bbtkZM0oQfc0gALpKGbJkY1ogAMRwAOxMSACsAEzZt0gP39+fSHAoA84AAOT4ARkcDyeYk+AE4xAA2J6eE4BED5TA7dAAdTa9DgsT86IgmzGoAagia1j0gJoODoGgK2W6YxAAEcGEh7Iz8qRhupsaBJsgZqgtPxwQoXgAGM4gC5XbTgmXSmVy9GY7EgAAKtKg9N5zPRMXchIilOpOH1hswTMqXXMbM53MxTP5BximnQZugQVClxA6IAHhaaI0rO4NJZHT10JhEDYMoIWTQEHAAKqyOhWBByehRhPZJDBmgQCJatkAEWj9RiyG9IAApEwg+isuNLVYEwgcAB9ZCh2POrk8u18mNzQXkiZTMUSl4KMQapQlssVujagCya4QDAQAAIay5TAeACqJwkaBi0g8ACgADQBhACUbfRzRo7noaDhLzESjwDQqTejU6oHKUgIVIUxSlHU4yslYdgJno8QpoEwRsAGZDluKIChmimoXBAjj1toFIuChETVFBzLoNUsLEmiCi6EghgVk6VjPESGEhGEERRDEcQJEk6ApGkGRZEoqiyHkdGwWU0FVKUsJOOGVJWK07TmsOvT9IM6FTqMEQitMhQ3PMiwgKRKwTOsWw7OcZnDEcpxOZc1x3I8zzvP8Pz+f8gLAmCSi3JC0JMKpdwIsiTCopqm5sni2lEiGHFxhyo5uhOxZkOkfBFugqgLJo7ZhhGLT4h0LKcegfQDLIQwHNOJlzuZcwLHWtlrJs2yTnsVmHGwxzMRiiVWMlBKpUon7fjAv7-hBinyXMKnpWye6CPk2RBHxly4TcgmxIRXTEaRegIOR1mUea4w0eUdGrbUbZovKhYoOMN4pugWC4PgRCkBQ1B0IwLDsLwFD8O9JSYBABDvZw+JYnA-BaVNlBQBAxBBquDCYGwpIbDOiHoM4mD8EOOT2GZuHWEg7jYW2QA), generated from one of our current Vega-Lite API examples on Observable. As of 4.8, the spec no longer works correctly, instead producing a thin, empty visualization. With 4.7, the spec works as intended. (In both cases I'm using Vega 5.10.)

When I compare the Vega specs generated by 4.7 and 4.8, it looks like they handle the chart's width differently. In 4.7, I see a width value defined at the top-level of the Vega spec. With 4.8, I do not. Without a proper starting width value to adjust, the `fit-x` autosize fails, leading to the collapsed chart. For `fit` autosize calculations to work, an initial value must be provided, which is then used as the target value to "fit" to (for details see [ViewLayout.js](https://github.com/vega/vega/blob/master/packages/vega-view-transforms/src/ViewLayout.js#L145)). 

So, for now it seems VL 4.8 is not generating proper Vega specifications like it used to. This issue also suggests that the VL test suites may not be sufficiently covering `fit` (or `fit-x`, `fit-y`) autosize configurations.

**Comment by jheer** [comment]
A few more observations:
- Unsurprisingly, this breaks when using autosize `none` as well.
- There is no top-level `width` property support for concat, so I also can't hack around this by moving the size outside the internal charts.
- If I set the view  config `width` property I still can not get the example to work in 4.8.

**Comment by domoritz** [comment]
Simpler spec

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A", "b": 28},
      {"a": "B", "b": 55},
      {"a": "C", "b": 43},
      {"a": "D", "b": 91},
      {"a": "E", "b": 81},
      {"a": "F", "b": 53},
      {"a": "G", "b": 19},
      {"a": "H", "b": 87},
      {"a": "I", "b": 52}
    ]
  },
  "vconcat": [
    {
      "mark": "bar",
      "encoding": {
        "x": {"field": "a", "type": "ordinal", "axis": {"labelAngle": 0}},
        "y": {"field": "b", "type": "quantitative"}
      }
    },
    {
      "mark": "bar",
      "encoding": {
        "x": {"field": "a", "type": "ordinal", "axis": {"labelAngle": 0}},
        "y": {"field": "b", "type": "quantitative"}
      }
    }
  ],
  "autosize": {"type": "fit-x", "contains": "padding"}
}
```

**Comment by domoritz** [comment]
It doesn't seem to be https://github.com/vega/vega-lite/pull/6095

**Comment by kanitw** [comment]
> It doesn't seem to be #6095

Why not, it's probably it.

**Comment by domoritz** [comment]
I tried reverting the main commit and it didn't seem to fix it. Maybe some caching is broken for me.

**Comment by domoritz** [comment]
Okay, something may be wrong on my side. Going back to 4.7 doesn't change anything either. It probably is #6095 (the only change that looks related).

**Comment by jheer** [comment]
I just looked at the content of #6095 and it indeed looks like the culprit. Would it be safe to revert this change? It makes sense that fit might not make sense for complex repeat/concat setups (or, at least save that as an issue for Vega/Vega-Lite to deal with in the future), but for single row or column cases it would be nice to keep the old behavior.

**Comment by kanitw** [comment]
Reverting fixes the  [linked interactive Seattle weather specification](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQxKHKhJMaANqhkAJwDWaUJgCeOOGhA42NWZqUAzGoMFwAJmkx6GcAL5KcLKq7nZkxiCqgmx6EcRIgr5WwmRYZHpIpoqRcqGY7PKooBBwblD5clYlggDM2c6lnugA7nAa8LFKZhZWsmwIdgnZ0AmWRSDu-Uh22iAQDPJObOFK7no0AF4bbtkZM0oQfc0gALpKGbJkY1ogAMRwAOxMSACsAEzZt0gP39+fSHAoA84AAOT4ARkcDyeYk+AE4xAA2J6eE4BED5TA7dAAdTa9DgsT86IgmzGoAagia1j0gJoODoGgK2W6YxAAEcGEh7Iz8qRhupsaBJsgZqgtPxwQoXgAGM4gC5XbTgmXSmVy9GY7EgAAKtKg9N5zPRMXchIilOpOH1hswTMqXXMbM53MxTP5BximnQZugQVClxA6IAHhaaI0rO4NJZHT10JhEDYMoIWTQEHAAKqyOhWBByehRhPZJDBmgQCJatkAEWj9RiyG9IAApEwg+isuNLVYEwgcAB9ZCh2POrk8u18mNzQXkiZTMUSl4KMQapQlssVujagCya4QDAQAAIay5TAeACqJwkaBi0g8ACgADQBhACUbfRzRo7noaDhLzESjwDQqTejU6oHKUgIVIUxSlHU4yslYdgJno8QpoEwRsAGZDluKIChmimoXBAjj1toFIuChETVFBzLoNUsLEmiCi6EghgVk6VjPESGEhGEERRDEcQJEk6ApGkGRZEoqiyHkdGwWU0FVKUsJOOGVJWK07TmsOvT9IM6FTqMEQitMhQ3PMiwgKRKwTOsWw7OcZnDEcpxOZc1x3I8zzvP8Pz+f8gLAmCSi3JC0JMKpdwIsiTCopqm5sni2lEiGHFxhyo5uhOxZkOkfBFugqgLJo7ZhhGLT4h0LKcegfQDLIQwHNOJlzuZcwLHWtlrJs2yTnsVmHGwxzMRiiVWMlBKpUon7fjAv7-hBinyXMKnpWye6CPk2RBHxly4TcgmxIRXTEaRegIOR1mUea4w0eUdGrbUbZovKhYoOMN4pugWC4PgRCkBQ1B0IwLDsLwFD8O9JSYBABDvZw+JYnA-BaVNlBQBAxBBquDCYGwpIbDOiHoM4mD8EOOT2GZuHWEg7jYW2QA), but not the [simpler spec](https://github.com/vega/vega-lite/issues/6209#issuecomment-606100468) because the x-scales are not shared for vconcat.

Add even if we add shared scale, there seems to be a different problem:

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A", "b": 28},
      {"a": "B", "b": 55},
      {"a": "C", "b": 43},
      {"a": "D", "b": 91},
      {"a": "E", "b": 81},
      {"a": "F", "b": 53},
      {"a": "G", "b": 19},
      {"a": "H", "b": 87},
      {"a": "I", "b": 52}
    ]
  },
  "vconcat": [
    {
      "mark": "bar",
      "encoding": {
        "x": {"field": "a", "type": "ordinal", "axis": {"labelAngle": 0}},
        "y": {"field": "b", "type": "quantitative"}
      }
    },
    {
      "mark": "bar",
      "encoding": {
        "x": {"field": "a", "type": "ordinal", "axis": {"labelAngle": 0}},
        "y": {"field": "b", "type": "quantitative"}
      }
    }
  ],
  "resolve": {"scale": {"x": "shared"}},
  "autosize": {"type": "fit-x", "contains": "padding"}
}
```

![image](https://user-images.githubusercontent.com/111269/78050856-b6760100-7331-11ea-9dd9-9b856c7e631c.png)


I'll revert for now and leave this issue open for the remaining issues.  I'll downgrade to P2 since the issue left is no longer a regression.

**Comment by kanitw** [comment]
This fit thing is also problematic with legend:

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "repeat": ["Horsepower", "Miles_per_Gallon"],
  "columns": 1,
  "spec": {
    "data": {"url": "data/cars.json"},
    "mark": "bar",
    "encoding": {
      "x": {
        "field": {"repeat": "repeat"},
        "bin": true,
        "type": "quantitative"
      },
      "y": {"aggregate": "count", "type": "quantitative"},
      "color": {"field": "Origin", "type": "nominal"}
    }
  },
  "autosize": {"type": "fit-x", "contains": "padding"}
}
```
