### ISSUE TITLE
Windmap image broken

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#6231]
<img width="427" alt="Screen Shot 2020-03-31 at 23 33 38" src="https://user-images.githubusercontent.com/589034/78106332-0e4f4f00-73a8-11ea-84aa-53054b9d5c21.png">

**Comment by kanitw** [comment]
I think it's a bug with SVGText renderering.

**Comment by domoritz** [comment]
A bug in Vega?

**Comment by jheer** [comment]
The new Vega-Lite wind vectors example is broken due to lack of data type parsing. To be properly sorted, the lat and lon fields need to be parsed as numbers to avoid lexicographic (rather than numeric) ordering.

**Comment by jheer** [comment]
However, I can also confirm that when I switch from Canvas to SVG rendering I'm seeing clipped symbols. Not (yet) sure why that is happening.

**Comment by jheer** [comment]
OK, found the other issue: the plot is using stroke rather than fill by default. It looks like SVG uses a different default miter limit than canvas, hence the "clipped" shapes. Here is a [fixed specification](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATdHkw5QECJFYAnMdi070pAO6MlmqvDzcTsOvFgU1GowDNXDDwLYEg8AE9CZAtIT29VKEJ0N2j9SDFlJjxWTVSoJVZUdmQTNSgxHWYcvMgCopLIAF9GjUb1IwwTAGsQsMiawm57YITIWER0KJibZE1qaNG-RjExWYs8E1ZkNo1IZCV4bk17ahDfKAAPXqXkMU0YjKUs6rK+qZxIV2OldHNR9AujFgFgKKx2hig4TOEP8jFu9w+FTwVVyrwi7ygX3svx8MKgAKBINYK1GihMwQ+uQQ+2+p3O4MMsW4GVK+nOsPhMWOpVG6JqAEdWOglMjdMiqLiYWN4L88qFNNwMPYLABtAAMCQAzAA2NUAXVJSDQNRM6Hs7G4Nia7Slq3mDiJK3pNqMwuoq2hUpudy5jB5UD5MUFwtFlQlLsZCFlvQVSpUOHVWt1BqgpqeeRVAEYABwasAAVmk+paEIZRlgjAAXnL2VBvQioLAomtef0g0KRcwwwta9Lo2k0-NVXmi8X6a0bUylEtTmyIZAKHCrWlYHhkIQLJm85AlisYuwKvAeiWwC1GkA) that uses filled shapes and an adjusted size scale range.

I will separately need to look at making sure Canvas and SVG use consistent miter limits in Vega proper.

**Comment by jwoLondon** [comment]
In terms of the gallery example (independent of the fill/stroke issue above), perhaps it might be nicer to use geographic projection. That way it becomes easier to integrate with other contextual information. Here's an [example spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATZAgBOjQnh4qckAGrJ4ebrrDpdu9AE8wGQmFiJuAd0ZLqYL5Kmh6EyMgh6MFgmoy6lkbKdGoakPDKAGaM1NhgwJAUjMjeufmweMiEuQCMAAyqUFliYrmQ7GLo8ADWkAC+veoQkL6aLLkAbLX1qSjZ+LkArJODUIS63HIJxqWQeE5hrcgAjqzoYgCi9mMDqR1OyLq5ANoaEKAQH1roeJg4758fSCsXQtUz4IgkchMeDIJR4eIMZhsTg8Uiab7oUjIYHcMKkJTec44sIAGSimnkihUKwBjRsGDwOz2B1M1kIGypakayG+wOQrSUyAA+nVUEKOsE+q8PjdaZAMLoen9dvt+aZqMhuJ50AcGpByusumqoN5EJIufr4dwjQB1RijRDYWp0aSqSBNMQRXIZM6wZC9aWyj7-T6QdE-HbA0G4AjEMhCWiIlgcLi8Ki0cSSNEY0hBTRUKw2WB0eCwCh9GmA2HpWL+UrS0NiZRMPCsbQ7LLIMSaVpN-zMNv8vXM42QE5RIw-IxUCsNwEdSeDjtFbu974D9vD1Wtcdw5jrmdBuXpJuPP5z0Od1emWKPStykc7057qeMGf3gGQT0ayU4JSsZoP1DBAzmNfJNG4DA-GeeowAAZkmABdPV+DQUdHD8dgfClWkICPT8omoT161wwErx7G84hSUihkfUxd0nA8hwvQEQOI5UIKgkwwCeWCENqZCoEcfxjSeaoAA5YIWaQBIDUj8OAxgAC8wPdFcKKgWAwi9LcWSgBj92nfk5IBBSoAVJU8hVPTIHZPxGRQxAdVHbwIg1HCZQ0RCQF6IA).

**Comment by domoritz** [comment]
https://github.com/vega/vega-lite/pull/6295 doesn't seem to fix it. 

<img width="756" alt="Screen Shot 2020-04-07 at 17 15 19" src="https://user-images.githubusercontent.com/589034/78731054-6b408d00-78f3-11ea-9b49-d257758679ef.png">

What am I missing?

**Comment by domoritz** [comment]
Reported as Vega issue. https://github.com/vega/vega/issues/2662
