### ISSUE TITLE
Missing enums for formatType, strokeCap, strokeJoin in schema

### ISSUE THREAD

**Issue by marcprux** [vega/vega-lite#6241]
Prior to VL 4.2.0, there were constrained enum definitions for various properties like `strokeCap`, `strokeJoin`, and `formtType`, either as references to internal defs (for `StrokeCap` and `StrokeJoin`) or inline enumerations (such as `formatType`). E.g. https://github.com/vega/schema/blob/master/vega-lite/v4.1.1.json#L6777 :

```json
        "formatType": {
          "enum": [
            "number",
            "time"
          ],
          "type": "string"
        },
```

These definitions are now unconstrained strings. E.g., https://github.com/vega/schema/blob/master/vega-lite/v4.9.0.json#L657 : 

```json
        "formatType": {
          "type": "string"
        },
```

These enum constraints were useful for validation in the vega editor, as well as generating APIs to vega-lite in other languages (e.g., Altair), so it would be good if they could be restored.

**Comment by kanitw** [comment]
Thanks 

`strokeCap`/`strokeJoin` is fixed in Vega-typings (https://github.com/vega/vega/pull/2496), pending updating VL to the latest typings. 

`formatType` now supports any arbitrary custom formatter registered as an expression function, so it's accurate to show "string". 

Plus, our TS definition is:

`formatType?: 'number' | 'time' | string;`


If you still think this should be fixed, please file an issue in the JSON schema generator repo.  https://github.com/vega/ts-json-schema-generator/
