### ISSUE TITLE
Legend with disabled scale

### ISSUE THREAD

**Issue by dechamps** [vega/vega-lite#6392]
I want precise control of the mapping of an encoding channel (e.g. color), by directly passing encoded values in the input data. Vega-Lite makes it possible to [disable the scale](https://vega.github.io/vega-lite/docs/scale.html#disable) which is exactly what I want.

So far so good, except that if I try that, [the legend disappears](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEC2CGBOBrSAuMwoBcCeAHApqlAMYCW8xANoWAL4A04U+AdsQPYAmpLA5kaAgRI2AUyFY8hNJBbtoPWJUiMJwgGal8lTkUgdl4uqqH72ldvDFrJBPXIUslKoxq069xFzcgBnYkrSYCwArpSURrRMDEyQnLCYsAKQAG5KIfi+RADaRsBmyjIAGipQhVAAgqX6egDE6uoADM2NkDES+QZ6AJrV5ZAAQtVeMrUtjQ1tALpRtEA):

```
{
  "mark": { "type": "circle" },
  "encoding": {
    "y": {
      "type": "nominal",
      "field": "col"
    },
    "color": {
      "type": "nominal",
      "field": "c",
      "scale": null
    }
  },
  "data": {"values": [
    {"col": "X", "l": "A", "c": "#ff0000"},
    {"col": "Y", "l": "B", "c": "#0000ff"}]}
}
```
![visualization(66)](https://user-images.githubusercontent.com/866859/80036106-08e9ae00-84e9-11ea-8fba-61f040497f55.png)

Okay, well, I guess that makes sense because otherwise the legend would just show the color values themselves, which is not particularly useful.

But that's precisely the problem: it would make sense to be able to customize which *field* is used for the legend labels, so that I can use some field (here, `c`) for the color but some other field (here, `l`) for the legend labels. That is, I want this:

![visualization(67)](https://user-images.githubusercontent.com/866859/80036416-95946c00-84e9-11ea-9a8d-9eb4ef0efc1a.png)

Which [can be made to work](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEC2CGBOBrSAuMwoBcCeAHApqlAMYCW8xANoWAL4A04U+AdsQPYAmpLA5kaAgRI2AUyFY8hNJBbtoPWJUiMJwgGal8lTkUgdl4uqqH72ldvDFrJBPXIUslKoxq069ykxMgBnYkrS6FDwsHxBANqQAMTq6gAMifEqUNFJ8XGQALp0RrRMDEyQnLCYsAKQAG5KAK74vkQRRsBmyjIAGimQbVAAgl3EerEJSZCFEi0GegCaXT2QAEIDQ+mZtFn5tEA), but only by manually spelling out all the color values in the color channel scale range, and then praying they don't get out of sync with the data itself.

Ideally, what I'm looking for is a way to (1) set a legend where the legend labels come from a specific field (or Vega expression), and (2) have that legend show up even if the color scale is `null`. Something like this for example:

```
    "color": {
      "type": "nominal",
      "field": "c",
      "scale": null,
      "legend": { "values": "datum.l" }
    }
```

**Comment by kanitw** [comment]
Conceptually, a legend is a visualization of non-position scale, so if scale is null, then legend shouldn't be generated.


The right way to support this is to allow customizing scale range based on another field. 

We can hack to make this work today by [setting the range to a valid Vega range object](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEC2CGBOBrSAuMwoBcCeAHApqlAMYCW8xANoWAL4A04U+AdsQPYAmpLA5kaAgRI2AUyFY8hNJBbtoPWJUiMJwgGal8lTkUgdl4uqqH72ldvDFrJBPXIUslKoxq069y+mFdQAzsRK0uhQ8LB8wcCQnLCYsHp+7ACuFPgA+gAMKlCa2royxNmQifCYApDsuHqORbkeMsq0tHRGtEwMTNGx8WhRAG5KSfh+qADavhBRBnoAGkXKMgCCRYUy8Pi6HTaTZgtQAJrzegBCK3oARpRDkFvbU+Z6AFpHMgDCZzK866w3vgC6bVoQA).

```
{"data": "source_0", "field": "c", "sort": {"op": "min", "field": "l"}}
```

Note that we need to sort by `l` to maintain the order.



I could see we extending scale `range` to support a field def like `range: {field: 'c'}` and automatically sort this range by the main field (`l`). 

However, this would only work if the field `c` has 1:1 mapping to the field `l`. Otherwise this wouldn't work.  

We could guarantee the correctness by performing an aggregation that produces only one color per the main field, but that's probably too much work to implement.

**Comment by kanitw** [comment]
will be fixed in https://github.com/vega/vega-lite/pull/6402
