### ISSUE TITLE
Make Line Chart Tooltip Less Precise with Mouse Hover

### ISSUE THREAD

**Issue by pybokeh** [vega/vega-lite#6407]
Please see this issue at the Altair-viz repo: https://github.com/altair-viz/altair/issues/1812

Per this above issue, altair users have to resort to adding a layered point chart as a workaround.

Plotly's and Holoviz's implementation of tooltip mouse hover precision seem to be more reasonable or don't require nearly as much mouse hover precision as vega-lite's implementation.

**Comment by davidgilbertson** [comment]
+1

I can't work out how to get tooltips to work correctly with Vega.

This is not close enough:
![image](https://user-images.githubusercontent.com/4443482/220249353-5e2d26e8-dc9a-49b6-9bdd-4e4ee36f9f46.png)

This is:
![image](https://user-images.githubusercontent.com/4443482/220249380-0996c3e3-dc75-4a05-a858-476e02718e47.png)

And if I do two layers with a line and a point mark, tooltips don't show at all (maybe only when the line chart has a `selection`? I'm not sure). I use charts for exploration so being able to do something quickly is very important (rather than spending an hour crafting a beautiful chart) so the idea of having to manually create a second chart and layer it on top every time I want a tooltip seems not great.

It's wonderful to have tooltips out of the box (coming from Matplotlib), I just wish the target area was a bit more than 1px x 1px!

**Comment by PBI-David** [comment]
Here is a solution I have posted on SO that works fine. 

https://stackoverflow.com/questions/74796097/vega-lite-line-mark-show-tooltip-at-a-distance

**Comment by davidgilbertson** [comment]
Thank you @PBI-David , but what I really want is a way to show tooltips nicely on every chart I create without having to write a bunch of extra code (the issue by OP is that users must "resort to adding a layered point chart as a workaround", not that getting tooltips to work is impossible).

@domoritz if this is now closed, is that
1. closed as a "won't fix" (maybe the issue is in another repo?)
2. closed as a "coming soon in a new version, tooltips on line charts show when the cursor is within 5px of the point, and users no longer need to resort to adding a layered point chart as a workaround 🤞

**Comment by joelostblom** [comment]
@davidgilbertson I think the functionality you would like is a "nearest" property on the tooltip which is being tracked in https://github.com/vega/vega-lite/issues/6851
