### ISSUE TITLE
Inherited styles

### ISSUE THREAD

**Issue by marcprux** [vega/vega-lite#6424]
The following specifies that all `mark`s should be filled with green, and that all `rects` should have a red outline:

```json
{
  "data": [{}],
  "mark": "rect",
  "config": {
    "mark": {
      "fill": "green"
    },
    "rect": {
      "stroke": "red",
      "strokeWidth": 3
    }
  }
}
```

<img width="42" alt="Screen Shot 2020-04-29 at 20 36 57" src="https://user-images.githubusercontent.com/659086/80660234-2d013e00-8a59-11ea-8315-f246661b0317.png">

But the same spec with the stying embedded in a `style` object only applies the `rect` stylings and seemingly ignores the `mark` style:

```json
{
  "data": [{}],
  "mark": "rect",
  "config": {
    "style": {
      "mark": {
        "fill": "green"
      },
      "rect": {
        "stroke": "red",
        "strokeWidth": 3
      }
    }
  }
}
```

<img width="46" alt="Screen Shot 2020-04-29 at 20 38 58" src="https://user-images.githubusercontent.com/659086/80660352-75b8f700-8a59-11ea-9e73-3f7d41ca961f.png">

It would be nice if styles inherited from each other like the config objects do. As well as being the intuitive behavior, it would also enable things like setting a `font` in `mark` and having it apply to all the group & guide styles (`guidelabel`, `guidetitle`, `grouplabel`, and `grouptitle`).

**Comment by domoritz** [comment]
@kanitw and I discussed a similar idea before. I think we have to see what part here is Vega and what is Vega-Lite.

**Comment by kanitw** [comment]
> I think we have to see what part here is Vega and what is Vega-Lite.

@domoritz I disagree and I don't remember having any conversations about `config.style.mark`.


> seemingly ignores the mark style:

This is an expected behavior. 

See https://vega.github.io/vega-lite/docs/mark.html#general-mark-properties.

Bar mark will have `"bar"` as its style name by default, not "mark".
We only do this because Vega does not have `bar` marks so we need to redirect the config.bar to config.style.bar in Vega config to enable this. 

Since `config.mark` generally works, I don't see why we have to support `config.style.mark` esp. since people should use the more concise `config.bar`, not `config.style.bar` anyway.

> As well as being the intuitive behavior, it would also enable things like setting a font in mark and having it apply to all the group & guide styles (guidelabel, guidetitle, grouplabel, and grouptitle).

I also disagree with this.  Setting mark's color to be blue doesn't mean you want other guideLabel to be blue. 


If you disagree, feel free to reopen and explain your rationale.
