### ISSUE TITLE
Introduce a cyclical type

### ISSUE THREAD

**Issue by willium** [vega/vega-lite#6590]
Cyclical values are not quite the same as ordinal. As we increase support for radial visualizations, I move that we introduce a cyclical type. I propose that this would be useful for all timeunits that don't begin with "year", and would default to using a [cyclical color scheme](https://vega.github.io/vega/docs/schemes/#cyclical) rather than a sequential one. Sequential schemes are misleading for cyclical values—December is both the ultimate month and the one immediately proceeding January.

**Comment by kanitw** [comment]
Can you think of non-time use case? If not, it might make more sense to consider if default color scheme for cyclical time units should be cyclical too.

**Comment by willium** [comment]
there are enough possible datasets that I think it would make sense to allow it generally:
- seasons (winter, spring, summer, fall)
- moon phases and other astrological phenomena (incl horoscopes, etc)
- biological cycles (ATP, krebs)
- natural/ecological cycles (nitrogen, carbon, photosynthesis, water)
[here is a neat wikipedia page I found](https://en.wikipedia.org/wiki/List_of_cycles)

Additionally there are: degrees, radians, colors which I suppose are slightly different (they're quantitative cyclical, rather than ordinal cyclical).

**Comment by kanitw** [comment]
> maybe instead of adding a new cyclical type, we should add a boolean property to scale called cycles? Then you could use it for timeunits fields (months, hours, quarters), ordinal fields (seasons, musical scales), or quantitative fields (degrees)

I agree that I don't want to add type: 'cyclical' given the term itself can be applied to both cyclical categories and cyclical quantities.

That said, if we gonna add another boolean to scale, you can always set "range" to pre-defined named range https://vega.github.io/vega-lite/docs/scale.html#range-config.

One problem here is that we don't have "cyclical" as pre-defined color scheme in Vega yet. So it is probably worth filing an issue / submit a PR there.  
I'm also curious if the simple `domain` and `range` properties we have are sufficient for how to map each cycle interval to the range.  That said,  these are all Vega issues, so I'll close this. Feel free to file relevant issues in Vega. 


Note: In hindsight, I think our `type: 'ordinal'` is a mistake too, because the only thing it does is to change color scale range similar to what we're discussing here.  We don't even know the right sort order without the "sort" property.  In fact, I think maybe we should deprecate it (See https://github.com/vega/vega-lite/issues/6633).
