### ISSUE TITLE
Distinguish between gallery for visual test and "example" gallery 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#662]
For visual test, we want test coverage for various specification, but they do not have to be all meaningful/interesting visualizations.  However, for examples we show in vega-editor should have higher standard.

**Comment by domoritz** [comment]
Should the gallery stay in vl then? Maybe that's not a bad idea. Have only the cool examples in the editor and a gallery of examples that exhaust the features in vl. 

We should use a common format though so that we can move easily. I propose to have individual files for all specs and one map with the metadata (link, title, desc, ...) like we have it in the vega editor.

**Comment by domoritz** [comment]
I can do this if we have a consensus @kanitw

**Comment by kanitw** [comment]
> We should use a common format though so that we can move easily. I propose to have individual files for all specs and one map with the metadata (link, title, desc, ...) like we have it in the vega editor.

Sounds great!

> Should the gallery stay in vl then? Maybe that's not a bad idea. Have only the cool examples in the editor and a gallery of examples that exhaust the features in vl.

Yeah, but I guess it could share some common code with gallery in the editor.  


-----

Also, the visual test specs should be a superset of example specs as we surely do not want to screw up examples.

**Comment by kanitw** [comment]
- [ ] add heat map without text

**Comment by kanitw** [comment]
Thinking more about this, if we carefully pick our test examples, we can avoid this problem.  So I’m closing this for now and we can revisit it later if this assumption is not true.
