### ISSUE TITLE
Negative values in size channel

### ISSUE THREAD

**Issue by sacundim** [vega/vega-lite#6634]
I got somewhat confused today because I used the size encoding channel with circle marks and my data had negative values.  Here's an example that illustrates what I ran into and what I did to get the effect that I wanted (encode the *absolute value* of the variable as the size of the circle and its sign as its color).

* [Negative values in the size channel](https://vega.github.io/editor/#/gist/c257cf8b95faad2bf4636d574cbefdca/spec.json)

The reason I was confused was that I expected zeroes to always be omitted (i.e., to be rendered with no area) but that's not the behavior at all when there's negative values, rather it renders each mark with `size = value - min_value`. And this has the counterintuitive effect of rendering zeroes to positive areas.

I couldn't find any reference in the documentation about how negative values would be interpreted, and no warning is logged to the Javascript console. Both of these might be worthwhile additions.  Alternatively (and more ambitiously), an enhancement could be made to give options on how to interpret negative values, perhaps these alternatives:

* Implicitly treat them like zeroes;
* Implicitly treat them as their absolute value;
* Implicitly scale them as the current behavior does.

```json
{
    "$schema": "https://vega.github.io/schema/vega-lite/v4.8.1.json",
    "title": "Negative values in the size channel",
    "data": {
        "values": [-4, -3, -2, -1, 0, 1, 2, 3, 4]
    },
    "transform": [
        {"calculate": "abs(datum.data)", "as": "abs"}
    ],
    "repeat": ["data", "abs"],
    "spec": {
        "mark": "circle",
        "encoding": {
            "x": {
                "type": "ordinal",
                "field": "data"
            },
            "size": {
                "type": "quantitative",
                "field": {"repeat": "repeat"}
            },
            "color": {
                "condition": {
                    "test": "datum['data'] < 0", 
                    "value": "red"
                },
                "value": "blue"
            }
        }
    },
    "resolve": {
        "scale": {"size": "independent"}
    }
}
```

**Comment by kanitw** [comment]
Thanks for the issue. 

You can actually already do all of these:

> Implicitly treat them like zeroes;

You can set the domain to `[0, max_value]` and set `clamp: true` in the scale.
I could see that adding `domainMin` (https://github.com/vega/vega-lite/issues/1721) can be useful here, so the domain max can remain data driven.

> Implicitly treat them as their absolute value;

You can use a transform like in the example you provided.

> Implicitly scale them as the current behavior does.

This is the current default.

I agree this behavior is not ideal, but we shouldn't use size encoding with negative values anyway.  This is the best default because we're encoding the original data via the scale. So it is at least transparent to users that there are negative values. With this knowledge, users can then intentionally choose another encoding channel other than size or transform the data (like applying absolute).   If we have other behavior as the default, users might not even notice that there are negative values in their data.
