### ISSUE TITLE
Stack: center should create diverging axes

### ISSUE THREAD

**Issue by willium** [vega/vega-lite#6862]
When you `stack: center` as in [this chart](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICONjgaC17WVJnyAvkszaksiADM22hGgDaoNzSCmHDa+qqYDAiUAJ5wSNoABAC8SQkATAAMWSAOoFBIglDmanBhapGUEHAAHsmpaQkA-AkA5ABiiAVwLQmorQCyXS2KIEgQ+mRwssohOQC6SsjaANb6TPEjAO40yvRooBDBOGgAjADsDiBTUGzKNLJk+yDRT0hkZNp8wfoQkSMBcEEyn0ODgpkEpUcdAhINMxUwVhGhyQUFW6CgU2CoUu1SeAKB+jepUuN0EnjxNEBwPQk2msyU0C6T2cD1KqB8IAAxAA2M4AVhOAE4AMwjTn5AAcEu5JxAczsCrsQA)
![image](https://user-images.githubusercontent.com/356976/93010466-bcf3e000-f541-11ea-92fa-d5b5d62ca039.png)

the axis should be zeroed in the center and grow in both directions like [this](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AQQAETJBBpRdSRdtgnM2uAA8kCHABs4U7QHc6MbcSQOGcbQ5ITHAOENoQMGyu4toMOBLaCGwMEP6RpIqU0iDusvRoACwADEUy8DRkWGgATCUyOEiysjTiZGgCMrJImCioANqg4nZwaCA9TE7Z3r4KaAMgUN3kbIoAnqOa2XbJ4pg1ABwAvlKgi5jLa6MAQltJDLvtAsenS2Qr6+gAwrc7e6gFAGZngtXu9RgARH73P4ATgAjMCzhcPiAAKJQh6ofYIk4g85vS7oABiGL+AiBuKRBJRAHFSWg4TDEaDCSAABL0rEAdkOAF0+TJoD5Zv1BsNRqshU44dlZGxkC00KAuj1RuNJjIAGY0EKyUbbaEgY4gcSGEaoTCKPwyRRIVrmjBwCpVYFDBAOyWLJzVWXypCK1DK7q9MZBDUgbW6-V3B7G01Qc2W60gRRwDKpNBJ5wpu1kB3lSp7AUgJDWEXzFY6zEgJyavaCr0eqVwGXAytwau1+sgZsS5s++psAxqCQ1Ep8w5AA) 
![image](https://user-images.githubusercontent.com/356976/93010619-566fc180-f543-11ea-8cc5-eac5292435b3.png)

**Comment by kanitw** [comment]
It's worth noting that `stack: "center"` is only for creating streamgraphs, which are typically not shown with axes. If I were to show an axis for a streamgraph, I'd probably want to keep it from 0 to max value, and only show two ticks. 

Thus, I'm not sure if this issue is worth doing.
Even if it's worth doing, I'd want to make the value below zero negative (not positive like the screenshot above have shown). 

If you really want to do that, the right way to fix this is to change the stack transform's behavior in Vega to include 

For now, I'll close this issue since I don't think the negative values is the right thing either. 
If you really think stack center should output negative values, please file an issue in Vega.

**Comment by willium** [comment]
@kanitw what about this example from vega: https://vega.github.io/vega/examples/population-pyramid/

It seems like having the axis positive both directions makes sense. If you are stacking bars where the color channel has only two possible values, it seems it would often be preferable to stack: center with two positive axes rather than stack: zero.
