### ISSUE TITLE
Question about groupby of `Q` columns in aggregations

### ISSUE THREAD

**Issue by ellisonbg** [vega/vega-lite#688]
Right now, if you perform an aggregation on a column, a groupby is done on all *other* columns. If multiple columns are aggregated, all of the remaining columns are groupby'd.

The groupby'd column include even columns that are of type `Q`. I find this to be a bit odd as it is a bit odd to groupby a column of floating point numbers. If those numbers were first binned, then it would make sense, but the grouping is not limited to that case. When playing around with these things on polestar, I find that it gets very confusing when this automatic grouping of `Q` columns is done - I would never know what I am looking at unless I had access to the vega spec for the plot.

What is the logic for doing groupby's on columns of floating point numbers?

**Comment by ellisonbg** [comment]
Pinging @aggFTW

**Comment by domoritz** [comment]
You are right, it doesn't make sense to group by a quantitative field without binning. However, I'm not sure whether we want to fix this on the vega-lite or the polestar level. I created an issue at https://github.com/vega/polestar/issues/336

**Comment by ellisonbg** [comment]
I am not sure why this would be a polestar issue. Shouldn't it be fixed in
this code block in vega-lite:

https://github.com/vega/vega-lite/blob/master/src/compiler/data.js#L188

Right now every column that is not aggregated is added to the dims that are
groupby'd below. A simple exclusion on `Q` columns would fix that.

On Wed, Oct 21, 2015 at 9:58 PM, Dominik Moritz <notifications@github.com>
wrote:

> You are right, it doesn't make sense to group by a quantitative field
> without binning. However, I'm not sure whether we want to fix this on the
> vega-lite or the polestar level. I created an issue at vega/polestar#336
> <https://github.com/vega/polestar/issues/336>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vega/vega-lite/issues/688#issuecomment-150077024>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
Although binned `Q` columns should be grouped.

On Wed, Oct 21, 2015 at 10:02 PM, Brian Granger <ellisonbg@gmail.com> wrote:

> I am not sure why this would be a polestar issue. Shouldn't it be fixed in
> this code block in vega-lite:
>
> https://github.com/vega/vega-lite/blob/master/src/compiler/data.js#L188
>
> Right now every column that is not aggregated is added to the dims that
> are groupby'd below. A simple exclusion on `Q` columns would fix that.
>
> On Wed, Oct 21, 2015 at 9:58 PM, Dominik Moritz <notifications@github.com>
> wrote:
>
>> You are right, it doesn't make sense to group by a quantitative field
>> without binning. However, I'm not sure whether we want to fix this on the
>> vega-lite or the polestar level. I created an issue at vega/polestar#336
>> <https://github.com/vega/polestar/issues/336>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/vega/vega-lite/issues/688#issuecomment-150077024>.
>>
>
>
>
> --
> Brian E. Granger
> Associate Professor of Physics and Data Science
> Cal Poly State University, San Luis Obispo
> @ellisonbg on Twitter and GitHub
> bgranger@calpoly.edu and ellisonbg@gmail.com
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by domoritz** [comment]
Are you proposing only to group ordinal and nominal fields but keep quantitative fields as they are? In that case the implications for the semantics would be eve more confusing than always forcing binning.

**Comment by ellisonbg** [comment]
Some cases are not clear.

For example the following is fine because you can compute the
avg_Acceleration by the Cylinder groupings:

mark=point|x=avg_Acceleration,Q|y=Displacement,Q|color=Cylinder,O

But the following doesn't really make any sense as there isn't a meaningful
field to groupby:

mark=point|x=avg_Acceleration,Q|y=Displacement,Q

Options I can think of:

1. Auto bin `Q` columns that are not aggregated.
2. Disallow unbinned `Q` columns that are not aggregated in the spec.
3. Alow them in the spec, but tell people it wont work


On Wed, Oct 21, 2015 at 10:07 PM, Dominik Moritz <notifications@github.com>
wrote:

> Are you proposing only to group ordinal and nominal fields but keep
> quantitative fields as they are? In that case the implications for the
> semantics would be eve more confusing than always forcing binning.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vega/vega-lite/issues/688#issuecomment-150082105>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by domoritz** [comment]
Option 3 is what we have done so far. However, I think option 1 would be best. 

In general, we try not to rely on errors in Vega -Lite.

**Comment by kanitw** [comment]
I do not agree that option 1 is the best in Vega-lite.   
I think it is a good idea to show an alert in Polestar that “You might want to bin a quantitative field” and provide “yes/no” button.  

But vega-lite is lower level and if you did not specify bin, the output vega should not return bin.  

Tthe data aggregation logic to be equilvalent to taking `aggregate`, `bin`, `timeUnit` and `field` (currently `name`) and put them them SQL select.   So if I understand correctly, SQL would support binning by floating value, but it won’t make sense in most cases. 

However, you can imagine a scenario where it works.  For example, if you have a field that contains student grades for a subject, which can be 0.0, 0.5, 1.0, 1.5, 2.0, 2.5, …, 4.0.  In this case, grouping by the grade is okay.

**Comment by jheer** [comment]
Interesting. Note that Tableau avoids this issue by requiring _all_ `Q` variables to be aggregated (unless aggregation is disabled), but I don't think we want to follow this path.

Having Vega-Lite auto-magically re-write the spec (e.g., by binning) may lead to confusion and undue complexity, so I'm a bit reticent of option 1 (though I certainly understand the impulse here!). What the default behavior of tools like Polestar should be may be a different question than the Vega-Lite defaults.

I don't like option 2, because I'd rather have Vega-Lite produce _something_ that can then be refined, rather than flat out failing.

In the end, I'm actually leaning towards some variant of option 3. Let's consider Brian's example: `mark=point|x=avg_Acceleration,Q|y=Displacement,Q`. As Ham mentions, in some cases it could be perfectly sensible here to group by the quantitative values (e.g., when dealing with striated or truncated displacement values, perhaps of limited cardinality). However, that case would be better specified with a data type of `O` or `N`. So, perhaps a solution here is for unaggregated `Q` variables to be coerced to type `O`, but alongside some kind of accessible warning flag + message. While unlikely to satisfy everyone, this approach seems workable, involves a minimal-distance spec "re-write", can surface warnings for higher-level tools, and at times will even produce the precisely desired result.

**Comment by domoritz** [comment]
Sorry for the short answer earlier. I wasn't on my computer. 

The consensus seems to be to have different behavior in Vega-Lite and Pole*. Vega-Lite is a specification language and should have predictable behavior. Thus we want it to either throw an error or just treat the `Q` as an `O along with a warning` (prefer the second). We have to see how we treat errors/warnings (log it, return some kind of error list with the vega spec, ...) because that is something we don't support right now. In Polestar, we should not allow unbinned Q and maybe ask the user to add binning or change the type to O.

I disagree that it ever makes sense to group by a quantitative field. Yes, you can do it in SQL but there you don't explicitly say that the field is quantitative. Just because a value is a float doesn't make it a quantitative variable.

**Comment by kanitw** [comment]
I like the treat as `O` option suggested by Jeff.  That means we will use ordinal scale and such and thus make the output not as confusing as treating `Q`.   

Re: error/warning.   Since our compiler is synchronous and only returns the output spec,  we could do somehting like
- provide API for `getLastErrors()` (inspired by our JSON schema validator).
- has an option to produce console warning (but this isn’t as useful for higher level application like Polestar)

**Comment by kanitw** [comment]
Also, we can make polestar never use floating point as type:Q when it is used as a group by in aggregation.  That way, we never lead people to copy bad vega-lite output code too :)

**Comment by jheer** [comment]
In terms of error reporting, I see two approaches:
1. Have Vega-Lite return a JSON object that includes the Vega spec as a sub-property. Other properties might include metadata, including warnings.
2. Support a `warning()` method for the most recent compilation job, as some validators do.

Console output may be useful in some cases but is certainly not a solution. My general preference is for option 1 above, but I'm open to other suggestions / arguments!

**Comment by kanitw** [comment]
> 1. Have Vega-Lite return a JSON object that includes the Vega spec as a sub-property. Other properties might include metadata, including warnings.

I like this more than 2. too.

**Comment by ellisonbg** [comment]
Thanks for the comments everyone, this helps. I think the solution of treating `Q` columns as `O` when aggregated without binning makes sense. I can implement that in Altair and use the Python warnings module for the warning on our side.

**Comment by kanitw** [comment]
Noted as part of #726
