### ISSUE TITLE
width: “fit” for text table 

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#700]
In the heatmap example in the VL gallery ("Text Heatmap"), the cells appear to be a particular width no matter what data is put in them. (In the example, the cells are considerably wider than even the widest text.) Any chance of a control that says "make the width equal to the widest text" or "make the width equal to the height" or something that gives us a little more fine-grained control?

**Comment by kanitw** [comment]
With current version (0.8.3), you can specify `config.textCellWidth` like this

```
config: {
  textCellWidth:  <value>
}
```

We haven't documented this because we are considering to move this to be either `encoding.col(umn).width` or  `encoding.text.cellWidth' in `0.9`.

(We plan to stabilize most of our syntax in `0.9` before start optimizing Vega output in `0.10`)

**Comment by jowens** [comment]
Perfect. Very handy. Looks like the units for <value> are points or something like points.

**Comment by kanitw** [comment]
> Looks like the units for are points or something like points.

The unit is pixel.
