### ISSUE TITLE
V5 Schema requires list for a selection parameter value and contains broken links

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#7281]
The schema, as illustrated with this [query widget example](https://vega.github.io/vega-lite/examples/interactive_query_widgets.html), appears to require that the initial value of the selection specified via `value`, is an array of objects rather than a single object. Not sure if this is a bug or by design, but I can't see the rationale for requiring an array here.

The schema also references  now out of date (and broken) https://vega.github.io/vega-lite/docs/project.html and https://vega.github.io/vega-lite/docs/init.html pages.

**Comment by domoritz** [comment]
I think we require an array since point selection parameters can have multiple data points.

**Comment by domoritz** [comment]
Docs fixes are in https://github.com/vega/vega-lite/pull/7282

**Comment by jwoLondon** [comment]
Can we not allow both arrays and single objects then? The query widget example does render without an array.

**Comment by domoritz** [comment]
@arvind?

**Comment by arvind** [comment]
Thanks for filing the issue, Jo. Yes, this is by design since Vega-Lite v4 (https://github.com/vega/vega-lite/pull/5304). We used to allow both single objects and arrays, but that caused a lot of confusion as people would interpret the type signature of single objects as allowing columnar initialization. As a result, I'm a little wary of re-introducing support for it via the schema. We could investigate silently supporting objects by wrapping them in an array, but I also worry that that may eventually push us back to the confusing situation we were in prior to v4.
