### ISSUE TITLE
Line in layer with sparse data doesn't get rendered?

### ISSUE THREAD

**Issue by mpereira** [vega/vega-lite#7379]
I was breaking my head for a couple of hours trying to understand why a line wasn't being rendered when it had data to be rendered. While trying random things out, I added `point: true` to it, which showed the data points (confirming that the data is being given correctly), but still no line.

You can see it below: the layer showing the blue data is kinda sparse, and doesn't render as a line.

![image](https://user-images.githubusercontent.com/112426/114316910-ef7cb000-9b05-11eb-890b-c7adce40c36e.png)

To reproduce, check out [this spec](https://gist.github.com/mpereira/6d259db303a087b1777487538d78b84f).

Am I doing something incorrect here?

**Comment by domoritz** [comment]
I think this is expected behavior. Invalid points (with null) create gaps. See https://vega.github.io/vega-lite/docs/line.html.

With the invalid tuples removed: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IghgrgLg9gzgSwF4FMQC5RQJ4Ac3ogBmCUIANCAMYwB2UYCtcGIuYAJh0wOYUgAnFIlQYoAiCgC+ldl14YAjAAZKAdwQcoACwwAOZapDaUCHtrLoAbIcoASOFRMBbMKwtRccdAHofANxQeMAA6HlJtCAAjEIQYH0cXMACgsABaABtSFACAVhCAKzg6fgywbBQBDABtUAcnFFd3KE9vP0DgsIjo2PjExuSO9KyoHP98opLKMoqq9FqQDjAGDFB-MAzJFnnQABFy1gAmZWO05QBmNMVcgBVDdEMALX4AcUrXWmwAfV2AUQBVL5wbQwARQL6jATOL64eCkBD+UjfATLAj5AyGTFYzGKGR7A6EY6nC5pQ6HO7KB7KZ6UN5QsCfH4AoEgsEQ94wuFQBFIr4o0YYKwhACceJA+2wRxOyjOl0OwopVJpIDpH2+f0BwNB4Mh0NhiG5iJwfNR+hCAHZhVbrTabWKJVLiQAWM63e5PV7vBnq5latm6zkGnnG-kEUXkfGSwnSs4uxTk93Uz30xkalna9lQwPwo3I03oPT2gkgIky5RxhWJ5Wq71MzWsnUc-U53mhwUWotRksx8ukqyKj20r2p30NzN6rnBvMC9C5TuOsu5WUDpNDlM++sZgPNw2t-PnEKFiPi4ul11XZQr6vDjfp-1Nye5k0zw4hKzz6PEpeKc1X5Nqus70bLMdynZ8CEUC1sWgzFDg-bsv1JJ0-zXAC0z9YCJyDJ823QSC52PB1P0XNJzkUFCVRvQCMPHbNdxDfNIOUW0WLtQjTx7Kwzl-Kt-1rdCx23R89xnZRD1YiT4LPZQuMUZDeNQ-jRy3B9sJEggxL0CTWKkzjSXIhTKPXajBNUlsGJnfDdOJLjDj0CiaxHTd7xA4SLI0w9rLLc1XQcqiBJU1y1PcjAxPfdiu2knz4z84yApcrDzOnDzwsjBduKuStKUHIy0OUhK6LA3CxPNGCYNxCL0uUHzDn7QzHNvGihOC5LQs8yriLOPQzgTbLV1ypTnMwwqcMYryurOLKlT4pygNo0DRss8blG6xQ6r6684vy4aFvUpRlu6w5zlivKhvmtzWoecTtNtA7SMver-O286WvAtrSrK7EKrSzrmLOdbpsU2amrM+jLs05bhSuY7Hq2s7mqSt6rq0m62J+hCyyh44TsGuaEbBpHILgjqMcm0keI2mbGtMoLEdwonxpUWMceBmnEoJ+mLVR60j3Rs8mcUAzKaB6nAvZor81fAi+ZjAX7Nh068dBiWZwPXJuatVKT0i2WZUON1hYG1mxZGvbZxCaXtfSwWziFwGjdFgrdpC9BzRCb6rc6m2VpZx2doupG3fDGXTht65fZMk3ncuvQuY1xnFFJXr7YayOnYD3DhRCJ0E9JKactT+L-dezOQnORnDn+iOi5eun8yz4PPdJ+Noer578ZViCic+rEPaI5vK+xhXcZB2mOcYyDy5J-nB4plOnvh5XFogqeQ8T5R15hw3C-bpezeubPrPXxOVDbxex87pRX15puiWPq454LhelYv5elDEnPp5Oe-Dnk7fn9HuLN+6AG5H1tqRO2T84YvyAWbWOlt+53x6txM+MDTYuzdggjihx16VzkqgwB6DLpCk-mvZBOCCFsyIUjIUfdsG4NJPLf+0DCHRxoSEYmZCSTVUoVHDO+YhScNvt-WUVw-7zxYVQthuEhTmjASSChw9jbpxLvmIO8i5RMIkYrVh-CZxZ1XsInBsZmZKL9rXcellIK4gALoyBADMSoNRQCuAEAAa1WCAHA+BWBZFoGgWQMAmCWHEJIexKBaA0G4LQPgmBqAwAyKCTx6xNgEBAAAYkOFQYUegUCHBAPYgAHp4kgKAMgcFYA6Sg3i0mjGcLCFEGR+COA2AQLAeA0nQCoAUygYBCkIG2KAIgoJXCWBAAAUgAJppHGc4GZFTKA8AEJoAA8uwKgSI2q5EWcsjg+xgQ1CdOQJ0NjphgCiGUgAgjEjIBB7rVIQFQNxABhGAEB6CeOCZUFJrBnB0B0M00YuBQr2O5E87YoSUAPKgLcjAtAIAZAyFIexUYhkIDKRUwgO9z6wJCtUjprAACOEAGTcgYIaAJ4B+mDJAEs1Z6zNlXW2bS3Z+zdDzHOOQQ4pyvGkFhegeFiL7EtP5aAVAAgYBiAkNIZFUg7HHloGAZwaTE6aDSO8jgKASD+I4GkRVyq0gSjSKU8paQXgkrqRsMAXwXg3AALJoOkaaSgSwVhxJSVsZxRiyyXHDvVC1Awyg2vtY6vRBBBVIq-sSX1+d+rmtRK4INtqHW6NUTOJ0ZdlpygetvANibrXJtDWmggGab6IJ7HKSBca81WuDSmqRYbBRZqTg5GtSaQ2prrjOEhzajqtoTbWwtnbLEECFI3ct0akL9ste2+tfDi0YAzYYidPrSQGxTm2gtHaG0LvQBmrWK7RG1WnYGrdc6VFdpLWXDWwosE60nYcR+1aB2zqLZejAB4rA3rkVG1ddkT35rrW+kdH6LY3oPdgv9sbqybqA8Oy+6ADznB7liZdkHRHIYA4O7d8732IbLihzEaH72rrIlh198HgEZrvVVF0G9yNnuAwhjNP6Q5ljo8nAusGh07rwxBkjJiLgMbg7xkD1hDyEY3stOj4iuMvsY5Rs2Wd+O0d8v6+TIncNidjip36dGAZyZnQp0TCGVDu0k3QgTvYeHqaM5pi9YmzOse9YJrRhnT32eLnhrONG9OTWEzxrTCGfPSYvAFnDDnTOCNC4LcL56vOObEr50mvYYq2Y84FyLwD4yH1-SYxQW8N0acywl0z3dCOWdU-g9LgGSsWLK9dbmMX13udqxF0r2WxLjvQ6lgzz67N1Y7sArOpCXOpafTB4r7X6vAPUXl1Lbn+sZem0N-eYkVAVZi9B143GVt7xdt1qzLoh65qm-Fmb+8rLzeO1WybA29uvzgZm67LaavYfO6tg77U2MmL7W9ijJnsvX1C7-OLTHsssZBy1pbbWPv7cugVi2IO+t3eW3Dx7Ls5JvhBxNnbZ3wf70-RZkHi3Uew4J5jyHL35Rg8U5jg8wpJNCMPb2TD-3jNBey2rZaS56Ps88xdzHk8ec9Vp4DwnUFNvzd54V1r72KcI4PKNlnvPZMw-l3TxX5mpc-eULz6HZONfi8x-keU8dpdV354N+HhN8jK567z3HtJdvo9xQj18zmVddTF5ziXZaHf+atw9t3hMru6+-Dmor93XfUPptzi3sWg8x6dZZFjN6RdpdO9HhXhNaEZ9l+rgHvvMdu391Z78avDdF6y2bHBuXw9XAN3j7PmukbHBFBnlHze0c59wmSDsCencqhd73xiWcy9VW-KT7v5PW-01jodyfmUfc15du3z3AeTtR573PyWYliNL8UVnnfxuEfKZF2SFfHXa9JY1hP36S4-vH9n6ftvHuL+V5n0b4vl1H0ScI-buXmulfoLpdGRAPg3seknqPi+CNhfkPvGi3q-n3rHIAYftPs7vjrvrARwhfttpgUgT-kjOAZVg-vdCAZ9mAcoCLmRtAdgQQMhs9rrlxHzs-t-qvr-qgRrLpiliwZxoXhzhwcQa+MhgActCwQXlXoIdfi7OcPutweIaYmwdXjIWAbHKQbwWpsodIaAcQZgooTJBQTbrhE6BDPNiwQgSPvQR+m7Mzj1iwRgcPlgcgfuOoQYfgU4YQUIbhOcDpooafHQS4emvvpJmgb9LJLdl-ioboSYa+BodJLJPwVIQLpQUjE6BmvEXpAVkYRjpdE6HAeYWIjkSHrhLkJPKEf4U3gQSfkQSYUKBiChmEZoWtMUbHvmE6AfuEQ-K0SniWpBDwQkVcI4YgTUd4a4e7P4R4SMS-rUeMQMXpFvnLtEakT4Rmovl0UftvjMWMarNRhrE0YMZfoEbMarEKPMTZKSJIVEToSseMRvlZrZJ-tUdsaoXoR3oUfrD0Y2ohrHJ0ZoVAdoSkcYfuHYQ8eTF8buucK+OcWWLZMMVYUEQwRmqCVVLZFMQiScQwa+OsZoWzoCdbrkW3iFvNj5KwVsewa8T4R-MtKSUkdcUCYSVSTScuMcTsQwQeJkcSKSU8Z4aMZSfuAzpJjCRlHrhCXhlCfXmNqSV3s8RSTEfuP0cyTZvicHm0arIKYRsKdVN7qyfyarGHlKYHiqcnt8ecH8VFGFrqfKarNicyYnsaTAeyRAYaZnuScscCarPkDiRadkVabceqQRmISSUUX6R6ViZKSztFFUbyS8daQwfkF+tzFqdFDKTGXKf6eGd6T2NFJYc4ZiR+oqcGYoPCXmWyYuqXnaeiaWXqSWm7OadmaSJHksTcWGYugmcyZsc2QySUe0QcQ2UcQ6dYXunEQocGU-m6S2Yye0fHrrjVDydMema2XugePcVVDVNGQue6VOTgVmVyX2GKWJowfWXuY+geQhvKO8bOYwmecAshh2VWV4TWR+tQcGXiROd2WqQQBeclhabQYOYiRgHZJeWNt1GSV2QST2TgX2cSKBXSbKVuZBV+bHGbqjKub9KBVcfBZOYhYBVnChTdGhSlqBfORiWWegH-ozoRiiehVoe+RBZ+bhRwhrIRdJKBamZudhQxeRVwUmXdMqXRaqb0YxdBWWKBSWY+XGYBW7B9ChseaJUaQJSabun-g0T3CJRNAEf+fmeRaXhUfNqtJEVhR+UJdxRMfpVcHBWmQhVxbVCKEzndL6VpWRX-nJRpSRdWZJTpdnPZeZX6k5U+aZZyfJS0aGduV+ZgnpbrqtLmRJRmVJUwSBUMTebXixT2KtA+XyZ5bZaYVRXdIsQIcZd8bZffkRfpMlWvmcXlZZRxYVcpUKD+WlZceVb-rIpJq5StFOqFTheReiHlRuaRQFcVXlexQNVlbYW1XlTFZlXFV5ccIRu1YdOJdNUuRRT5VFXnM1W3qlTBeQV1TZa1fNXdH+YpY6fFXNbJZDLbJtX3mOmtWNlDCcNdZLJVfNg9ZhVZZxSZfrN9vdUoSdUOd9UFWTKKXtV9TOb9YYaDUVWrHfpdfxeBYJdDXHKhXDUtbGTNb-HDRlejStVTrrlDJpf9QBeRciZdfaUTdpUdMBSzgTdVaNRjfkEDX9I5RTc5YzWTe5bFStW7FqQTf1R5TNYwQ1cSATSNQLStYIhNa9d0VDXVRwlLfjUlbLXht9e1QTdjYuWFYBZLYddLflckfRV9b1XrYZR9bVSrQeOdT3Gra9v5Vla+DlShtRSlljO9TVYbUVfVZdaDsrWJlTbuZjMAb7eeUrndTTfucHcAv3iVdJFjFNTjVreRSucxd7WjZrd1VTY7T3M7bHRtZHTfmBtzDHT2FDG+QjUpXhsWdTehkzGBQVR7buooOfnlrXXTeLYnU3bgS3T6k9ZZLHMXaHOxr3RBAPTKLXfzVzR3bHMxEXYzLCcPUoPAnPSgvnSXs6YerXWndZSZZ3cLWPZjAvXhHNj9gLE2fXYjY3bYSnd3VcKbe7RfZXW7EDQLG3ZPd1WtEjjfSzeXadXhPkNtfvSGXbTNQfAAxeI3ofVjjPajKPeAyFcA0uVjmAwLPHenVxUg8vcWZA6Wunl-Rrdvd8QfHveA-rfSQ3ZXchcvZ2efRXY5nnjfQOazQFR-a5UzOOT-UOR-cKWw5zctR3RWQwxPXw+-foQw2LW-eg-QyfXrKgwQ43RmpJicFQ1vZ9YQ9Fgw-g6o-I+vTXTKGXTQ7-VA2HboxApA0rrnHXQbQ-Y5hqU7RY6-cI+g6bhY27fTYg8ibgyfevLwwne-bY9nRY0I745IxY+I44zvdJRY7I1o4-RGTXevCo+bY5k-RY5o0k6ZnbrnITRw8TVw1k3fW4x3V6Vkw48Ezvf-Vk64+3e-XjS5mHD42gzvTg+bl4xA6vQjhmvkbPS3SfGE2U4Q-ulk9E+kxDsjajFk4k+Q45s4z08vu04TM001rM6Q0ZVMxk5-a09Q1Y7Q+s9w4nIwzk9pR-c-fs1UxIzvVI3U-sw03I5XfkMQzbJ8fM-TMbZs30402oz9Rvfs8M2s9lu2cs5M9Y+s+pY82k38-vOzbM-o9s4Y4s+My3ZXJY2Q8C-8xXKLs84xPCzdOi0Jpi6nl3SfUizczE9Mxs3U0i0Ex843TM0S5bgg0U0xS0xSyvQy+-RU4izqWy5I4Syy8xJA68yy9kwY5w8U5y+TYc2RQfNw3gqU9S3c9juK2c+E4QwC3S9Vty+U4q+q1S7c45ti9pOi-A0w55QfKC3gr86i-vLUxvXgkCzs6MznbLHguC1a5TiENAzdLAy3Cs2bRC-TnZblZy1syiw6xLjJT3M-YPHK3q6ZuY8G8q-043bacGySyM5C2ZXS085q6q9XQJj6+87G1zoG3Y8G5a2GwG964PPa3C0y0s1m66xWwjpk5yzC6G4Yyk62wU9U+g5Q1GvfMi6s26wjn21wrgpA6gfIpvBO9q0YgO2m-6yO1O7RZK8w5E-2+ApDTm43eo2O6yyayA0hsuz7PiyvOSxOgO424Y17RuxvJadu5Xbu3O+AhKyK7k7S8+3e66au6awI3u9-W+0cwPffBqwe4g8By+7q6S6ZttSB4W9B9li9f++Wx28u1g6e0oJgrDbeyfFe6K7yxe+Ar6-fU27bue-QkR92+cwM41gi3uwc4B1Kx48y4R3e+w4x8wweBB2xwu8O4TFx8u9m2Bx3eDax-s-B+mwG9BT-Ch5w9CYJzW3J3m46D-Hh7k+-jh7tQ+45pBBG59JyffMdT+yAwZ8goO363x-TGYVwkizGwh2tvIki4m-K2JlnHp2VKZycH9cZ0uQvo5yuxx55VnJ50ixJ4u0jAUTZ-uz54naAre0i4p8TePv5-yxhyAl8xR158K7C0OXF1F6+zl7k2JE68Yll3Z5JwjtZ5+3gs50W5dglax3grx6R-TMLvF209pw1jYDrtV1cGF5ZxPGMzi+1z+JAyVwwuh519lrp8TiN2p0c+VihiF42ZA1V412VWl2Ztx9G6t7O+t+x4V0cyVP5z7VN2tuR-egwkJzF91cl+1wCcJ+-S+VF6eWl3dy94l9pe95+5cOZyR4Y+trN1wr9+V+F1Z9rktxoiyWd5jmt5l79814Ywaax791BxV4THEVD1u49+g1LFj7J+pxdyp6IiezD+7kT5+JvApTd7jzo5d6Itl+20p8LVTwV0z4T7uaz6DwN5ZBp8D63Jt8Dre76oj0p9x76mj2D4xHzz9312Y-LT1yjzLWT-x5LpD8L0rSr-TAo8Y-TySE3fL+Lyt5t8x-W7LyG0Oy11i3W3R+b9z1bwS4o+N0erV-Z5W1D6dzjzvQJxr9d4FyAwo9h-zw9zT00wR-D+CSbx60H+b590xzb8N8H-N1KyQrr8TySG25b9ew1xH0Z-7+4x62n5T4JlRyqzS8p8X9Zvb9e-InRq7+j-TEL1wjJmN5m5+3RpLzz2GDn3r-ppA9YrX9F-nyJwr5D-Kg4uUE4jsCAK4h4nEjUr4kwJSrCMElKmEpQBElEgoHEjQIknMGsBsJIKwOklwOcMKMhj0iAMUnEiapilbPij4oQHUg0hsM0lQK0p4gv4QF0pf30gMiUiMmWCsApkMyOZOMgWQsp6UYADZDgC2Q7JNAbKQ5Mch5RlALkGQa5DwH5T3JeUTyV5O8ksCgAvkAgH5IQD+T0BdAlAOAEChBQPJwUa-KFLyhhThoEUSKFFCUnRTlJWA-3awg-zSTEpSUpAZYAiEpR-8aUdKDgGsmgGMoks8AvZGAAOQcouUPKMlPygjTCp3+oqEAOKklToBIUsqOVAYLsRAA)
