### ISSUE TITLE
Faceting should have "cross" semantic

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#741]
Currently faceting a chart by both row and column do not produce cross results between two fields.

**Comment by kanitw** [comment]
I will remove the grid as mentioned in #822, but I think imputing cell for background can be a post-1.0 patch.

**Comment by kanitw** [comment]
Example:
```js
{
  "data": {"url": "data/movies.json"},
  "mark": "point",
  "encoding": {
    "column": {"field": "MPAA_Rating","type": "ordinal"},
    "row": {"field": "Major_Genre","type": "ordinal"},
    "x": {"field": "Worldwide_Gross", "type": "quantitative"},
    "y": {"field": "US_DVD_Sales", "type": "quantitative"}
  },
  "config": {
    "cell": {"fill": "yellow"} // I’m just adding this to demonstrate a minor bug 
  }
}
```

Current do not have background for all cells

![vega-lite_composition_-_google_docs](https://cloud.githubusercontent.com/assets/111269/13062288/4fc081f2-d3f2-11e5-9376-a69ec9901661.png)

**Comment by kanitw** [comment]
Instead of producing just the facet transform.  We might have to: 

1. Produce unique values of column field and row field.  
2. Cross the unique value of both fields.  (and project both fields to the top-level again)
3. Produce faceted table
4. Join the crossed table (2.) with faceted table.  

(Or alternatively, we can extend Vega facet transform) 

In the case of faceting the same field by both row and column.  We can use the same step with minor modification. 
1. Produce unique values of **the field**
2. **Self cross the output from 1. (without projecting the field to the top-level as it is ambiguous)**  
3. Produce facet table
4. Join the crossed table (2.) with faceted table **where `row.<field> == <field> && column.<field> == <field>`**

**Comment by kanitw** [comment]
Here is an example spec that facets by Origin for both row and column.  

```js
{
  "description": "A scatterplot showing horsepower and miles per gallons for various cars.",
  "data": {"url": "data/cars.json"},
  "mark": "point",
  "encoding": {
    "row": {"field": "Origin","type": "ordinal"},
    "column": {"field": "Origin","type": "ordinal"},
    "size": {"aggregate": "count", "field": "*","type": "quantitative"}
  },
  "config": {
    "cell": {"fill": "yellow"}
  }
}
```

Ideally, we should see yellow background in all cells.  

![vega_editor](https://cloud.githubusercontent.com/assets/111269/13062921/9d8f61c8-d3f7-11e5-972b-2b7b797ef82d.png)

**Comment by kanitw** [comment]
Actually, since we separate `repeat` from `facet`, `facet` do not need to support cross semantic anymore.  

For example, self-cross in Tableau only produces plots along the diagonal:

![tableau_-_superstore__read-only_](https://cloud.githubusercontent.com/assets/111269/14470263/56c4ed94-009d-11e6-903e-ce0ce3006be8.png)
