### ISSUE TITLE
domainMin and domainMax not always respected

### ISSUE THREAD

**Issue by rfbowen** [vega/vega-lite#7796]
`domainMin` and `domainMax` are not always respected, despite `domain` behaving correctly.

[Example 1](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9p3ADYBDAJ6YATigDaoALaK1AazwhCygA6YUIAEb6Q3MPLhmUhNaUzdCECPOIvkNw85EEwoSDoSJFQQAA9jUwsrAEdSRSI4QkViNEtueEx5Oit47kowRXlLGLoIPRIAWRJWblr6qAbFeOQWAA5ZbmUE82qQVPTiLJy8kAKiqyHZaQBdVuzFYyhFHVGlVTUOEBC6dcpMQkpjPfVD5G04lC4QIeQ2OVBugEZBlE-3h+QACYfkCAHS9QG9FiAgDsn0BLBhLAAbJ8AJxsCT-boSEEAVlB6NReIRgNhbGRyIkgOxLWeKH6nA+KDxIM+n0JvUxEjRvV6SN5aJYaNpyGRbJYoORaOlEiheMpaIx0tFMLZvVBJLYgLxaM+MKRJM+EmRot6ILJUthLE+0rRMJlaJJNKZALRFphos+TxeEg5yLJBspbFtvQkDqxrq+33pyBNoL6kJhgNlGKFXuBsZtmulgPRctteKkCq9uKzyPBydtyLxvW9ft6pqjvxY+MBoLl1MxNr6Ejxn0ZzOQn1ZsdroLYQpheJDaL97J1XvFseRLC9atjMLYE7RsKdVLxM+1LqHA5BMIrJun1JNdcRnzXzeH7tjEPB6LYDt3yeTg4BgJ9Bk0QTaE4TTJU9V1UU8xBGVQUBCR2F6J0hU-FNHyHMk2UxTk9RROFURHFg8WgssXnZbcpBtHVMVRXc8Qw-9W1jdkYU1acZwvItdR1Einx1NlF345dyOpdjiM-PtEPhRjulhCVt0BGV2QY41P2VaDzRYvpCQDSSbWUuFoJfciFV0+0HXYaUOCpUUpDZVcO1tC9k37BjeUjIc-TZZMpRsp0EQNKRkU9J9qXVDlZwkPsPOnVE-xxMjfmQ9i2AVGForxadhSbLzmPI3l4JJE0WGhRF2DJOzRxeAC2IpPcETYKFGxLMKRJQPNcoBcMLR1CcAzzE0827eE7K0mrEPgxEMrzeEIXZOyTI6lgJE1dy8zna9r1FdgLRJUFeTJObjURbsdpjGqA01SFJ3DRCkWRBLWEzGrfPRCi52itTbR2pKgTrA7pV6BUGOFRs2Fk1h8o6vVwQDXkR37WESR26rJBDOG9QvGVAp+p8URBecDv5fVdwQi8EJ2jdfUtPMsspPM+WFT8dvGyQxMPcNDzS6kEWInalrjFaVhCNRMEoXxcmMcpKmqIcQBIOhMAsKAlaIexYwV1XlbCNXxAGEAABJykYTA9CsMRCDMShkAAelt3IEEUUEEEyRhSGsUE4AgW2TbNxQHcwJ2AFonEITAHclAArCWoCOIA)
[Example 2](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9p3ADYBDAJ6YATigDaoALaK1AazwhCygA6YUIAEb6Q3MPLhmUhNaUzdCECPOIvkNw85EEwoSDoSJFQQAA9jUwsrAEdSRSI4QkViNEtueEx5Oit47kowRXlLGLoIPRItFk4WAA4AXW5a+qgAWQbkJpAuxRIexXiBltluZQTzapBU9OIsnLyQAqKrWdlpDqHsxWMoRR0FpVU1DhAQukPKTEJKYwv1a+RtOJQuEFnkNjkoAmAEYZihgYCvsgAExgmEAOha0JaLGhAHZgdCWGiWAA2YEATjYEkhEwkcIArPDCfiKVjoei2LjcRJoaTWHCppwgSgKXDgcDqS1iRICS0WjixQSWAT2chcfyWPDcQSVRIURTmQSiSq5Wj+S14XS2NCKQTgWicXTgRJcXKWnCGcr0SxgSqCWjVQS6WzuVCCY60XLgT8-hJBbiGZbmWw3S0JJ6SX6QaDfpJcfDWsi0dC1UTpcHYWmBoLNQToYT1W6KVJNcHycW8Yic27cRSWiHwy07cnwYM-nT4erWcTXa0JBTgVyechgXzi+34WxpWiKbGCeGBabgwri7iWMH9cW0Wwl+XPZqJ2uTb6Z1O4WiM7bV6zbR3scCD73ZwHi0jEYSbCeue6LInK0KhigLQEpmqIYvm2rmma4Gpn8qrwtCEjsNBZrsDm+7gUWfydkK5p4hi+JziwFLgQ2xEhkObCuqaxL4uWFJfjOWL8haRqrmuj41mapo0d+pr8tuYm7sRrJ8dRQETlhmKcVC6KKqe0KqgKHE2kBOrgQ6xafoaboQWiSlaRi4G-sRmrUiqlrSkyRJMkmM5SPy+5Dm6j45pOHFim5ULhvyObKhwKp0ti5lMkG36sgagrrhIE6Bau+LTsFdHgtBfFsJq5kTquMo9u5-bgmKGF0raLCoti7AMnKE6OkBS6Rp6WJsCi3Z1vF0koBWpXBUefwMlSTIMjakadsxTWGaNWEYdFrJbkiApNTZA0sBIRoBRWG4vi+crsI6g5ipNyI2tio7HahA2RkayLLgmWE4rimUTKigbQtS5ohhuKW6W6x3ZTCHbwl6LSahxMrdkxx3lTC5qIpGYpzpO6J0sd85hrGKPmo+qpYhRx39cgm4QxKFrlphj6YcdI2SE6FYUo+03ijKQHHfNkiyRSNb8flrJYtRx2beT217CEaiYJQvi5MY5SVNUM4gCQdCYBYUAa0Q9jFmr2ua2EOviNMIAACTlIwmB6FYYiEGYlDIAA9M7uQIIo8IIJkjCkNY8JwBAztWzbihu5gHsALROIQmBu0qABWctQDcQA)
[Example 3](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9p3ADYBDAJ6YATigDaoALaK1AazwhCygA6YUIAEb6Q3MPLhmUhNaUzdCECPOIvkNw85EEwoSDoSJFQQAA9jUwsrAEdSRSI4QkViNEtueEx5Oit47kowRXlLGLoIPRIAWRIUADZuWvqoBsV45ClZbmUE82qQVPTiLJy8kAKiqyHZaQBdduzFYyhFHVGlVTUOEBC6dcpMQkpjPfVD5G04lC4QIeQ2OVBegEZBlE-3h+QACYfkCAHQADkB4JYgIA7J9ASxYSwWp8AJxsCT-XoSEEAVlB6NReMRgLhbBaLQkgOxrBB4NpyDxIM+n0J4MxEjR4PByO5aJYaMZbWevxYoJaaMlEmheMpaIxksZsJZ4NBJLYgLxaM+sORJM+EhajPBILJErhLE+krRsKlaJJNM4HxQaLNsMZnyeLwkbJaZL1lLY1vBEjtWOdANZIKNoJYkN5gOlGIFnuBouQVvVksB6Jl1rxUjlntxGZRENhucpePBXt94ONka+LHxgNBMupmKt8YkeM+DKbv2ZGZroLYAtheODaN9rK1npFLxaLE9KozsLYY7RcIdVLxU81TpdyH7INhLXbLUn1KNtaRnxXg5PbozkIh6LYdu3lcrA+PgO9FBwTROMYXhFMFR1bVGVzEEpVBQEJHYYDtXYStlxg9MXjrdkdRReFUU+PEWDxGDS2wr12zYK0tUxVFt2ImCWwzVlYXVScp3PQttS1Uiny1Fl534xdfmpdiSM-XskIRR9-zXbD2AQqVWWIw1P0VGDTRY+NCX9SSrWU+EYJfbC5V0207XYSUOCpRkpBZZd22tc9Kz7YjuQjY9fRZSsJRsh1ET1KQrzsrDflrMc817DzJ1RP8AQkcjwpAvENzlWFEtS9zGy85jsO5BCSSNFgYSRdgyTs4cXgAtiKR3RE2GhBtiyfI0zWtOz5JQMkCTq3MjVzLsETsrTqqQhCkQy3MEUhVk7JM7qWAkdV3NzGdr2vRl2DNElQW5MkZsNJEuy274MyTNsSQ5dakORFp4t6GF3TbdFWXHRLfSkDqnyWs0IvtcE5WIwUG2ora8u6nUIX9bkiL7OESS2qrJGDaGdXPKVAu+48URjVk9t5XVt0Q89EK2rq+nNXNUspXMeUFT8ttGyQxP3MN9zYQsyRKvicYWvolpWEI1EwShfFyYxykqapjxAEg6EwCwoAVoh7AzOXlcVsIVfEAYQAAEnKRhMD0KwxEIMxKGQAB6a3cgQRRQQQTJGFIaxQTgCBraNk3FDtzAHYAWicQhMDt8UACsxagI4gA)

In Example 1, we can see neither being respected. Modifying them (such as in Example 3) we can see that they are *sometimes* respected. It's not clear under what circumstances they are or are not respected.

However, adding in the `domain` property with the *very same* values immediately addresses the issue (see Example 2) I would not expect `domainMin` and `domainMax` to behave any differently from the use of `domain`. While `domain` is a reasonable hack around the problem, there are times where we need to specify only one or the other side of the range and `domain` requires both a min AND max.

**Comment by domoritz** [comment]
Good catch. If you look at the generated Vega for the first example, you can see that neither of them end up in the generated Vega. If you remove the layer, it works. The problem here is in the scale merging logic.

**Comment by domoritz** [comment]
I think the issue here is nicing. If you set `nice: false`, it looks like your example is correct. [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9p3ADYBDAJ6YATigDaoALaK1AazwhCygA6YUIAEb6Q3MPLhmUhNaUzdCECPOIvkNw85EEwoSDoSJFQQAA9jUwsrAEdSRSI4QkViNEtueEx5Oit47kowRXlLGLoIPRIAWRJWblr6qAbFeOQWAA5uKDgwaphKykxZbmUE82qQVPTiLJy8kAKiq2nZaQBdVuzFYyhFHTmlVTUOEBC6A-HCSmNz9SvkbTiULhBp5DY5UG6AEYpihAf8PsgAEwgqEAOl6kN6LEhAHZAZCWCiWAA2QEATjYEnB3QkMIArLD8biyRjIai2NjsRJIcSWt8UL1WcgyTDAYDKb1CRI8b1eliRXiWHiudjeSxYdi8YqJEiyYy8QTFVyUbzerCaWxIWS8YCUViaYCJNiuf12VDIQrUSxAYq8SilXiaSzOACUHiYaiuYCvj8JPzsXSzYy2C7ehJ3USfRC+TCrbC+oiUZDlQTJUHoXbnfrFZD8SqXWSpGqg6TC9j4VmXdiyb1g2Hetak0CWOSHSrmYTnX0JGTAZyu6CeXaW7C2JKUWSY3iw3yjUHZXbsSwgzq7Si2LO8ajPUyyYvDd7fcgxzCUfWrQvmVbW5jAduJ9f-XaEfD8Wx3UeWZZuOV6QiGHJ4umyJormGomsaXKljCSqwpCEjsL0nqSv+2bvqBBY-G2AomjiaK4oCZIsGSiG1oRwawlIzpGoSuJHpRiE9nafIovqC6LnelbGka1EfkavJrqJG6EcyvFUf+I7oeieEQqicoHpCSp8pRlr-pqiG2oRfSUhG8nOppaKIV+hFqsZbruuwiocEyXJSLyW4MS6d5ZqOlEiomV5hryWYKk5noYmaUjYiiLkEaCrazmWI5+QuuIgRCEi0XFkFkvuaoohlOW+Z2AWcYRIqoTSVosMimLsHSLlTj8YE8Qyx4YmwSIdtWH5WgGLoubuTVGrOEallapaDuiLkGSgaHyuF+WluiCJ8i5VmzSwEj6r5pbLo+j5cuwAY0rCIp0stlqYoOh3Ana2YOjSgp7ehWLYml3TIgGwX4nyc4ZWGUj9R+m0BvFHq9GqlFSh2bDKR9pWzSa8IRiKFGjqiNKHY1kgxsjJp3kq4VA1eOKpnyp1iqaR5oXeaGHYNkh0qhFF3hGY5IgS0XAzNyAZQ9lZ8WwlZ0tVIkk+tvObbsIRqJglC+LkxjlJU1RXiAJB0JgFhQJrRD2Ha6s61rYS6+IkwgAAJOUjCYHoVhiIQZiUMgAD0Lu5AgiiwggmSMKQ1iwnAEAu9btuKO7mCewAtE4hCYO78oAFby1A1xAA)

We could set nice to false if domainMin and/or domainMax are set.

**Comment by maclockard** [comment]
Yeah, setting to `false` when `domainMin` and/or `domainMax` would be dope. I'm assuming that's what happens when you set `domain`?

**Comment by domoritz** [comment]
Yes https://github.com/vega/vega-lite/blob/c84e581ce9e2b7858e5753589417d2b2b684df38/src/compile/scale/properties.ts#L253. 

@kanitw should we disable if domainMin or domainMax are set or only if both are set?

**Comment by maclockard** [comment]
FWIW my personal preference would be if either are set, otherwise there is no way to set _only_ a minimum with proper truncation for an axis.

**Comment by domoritz** [comment]
I think I agree. Can you send a pull request?

**Comment by maclockard** [comment]
sure!
