### ISSUE TITLE
Support missing axis “values” properties 

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#796]
For example `values`. See all properties in https://github.com/vega/vega/wiki/Axes.

**Comment by kanitw** [comment]
I omit `values` back then because I think people can just set `scale.domain` but just realize that `values` is still useful for quantitative axes.   Do you see any case that people need to use `values` for ordinal axes?  If not, let’s only allow it for quantitative axes.  

I think `values` is the only missing property for axis, so I’m renaming this issue.  Please let me know if there are other missing ones.
