### ISSUE TITLE
bar charts with ordinal x-axis cannot use log-scale on y-axis

### ISSUE THREAD

**Issue by pdhorn** [vega/vega-lite#7993]
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "description": "Google's stock price over time.",
  "data": {
    "values": [
      {"y": 2, "x": 1},
      {"y": 7, "x": 3},
      {"y": 4, "x": 4},
      {"y": 1, "x": 6},
      {"y": 8, "x": 8},
      {"y": 3, "x": 9},
      {"y": 5, "x": 10}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "x", "type": "ordinal"},
    "y": {"field": "y", "type": "quantitative", "scale": {"type": "log"}}
  }
}
```

Is trying to use a log scale on the y-axis, with an ordinal x-axis.  This produces a blank chart:

<img width="172" alt="Screen Shot 2022-02-17 at 10 54 59 AM" src="https://user-images.githubusercontent.com/15755132/154531179-c5f9bc00-2645-4e0e-b66f-47483f5e0e67.png">

Note, changing `encoding.x.type` to `quantitative` produces a reasonable chart with very skinny bars.  Alternatively, removing the `encoding.y.scale` (and leaving x as ordinal) produces a bar chart with thicker bars.

I would like to have the ordinal x-axis / thick bars with the y-axis on a log scale.

**Comment by pdhorn** [comment]
This also fails when the x-axis is `temporal`

**Comment by domoritz** [comment]
There is a warning in the editor "Cannot stack non-linear scale (log).". The problem is that stacked data cannot be on a log scale. 

You need to disable stacking: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEzjQATjRyZ289AHE2bMoLgByCAAIImNlADWlnJqhxLbUuss6EcSopUkTBRUUGIkQQY1NABtUABPNAAmJQAPNABGAF8FBLQAdjS0AGYcvNQAFiLKspBE1AzqgDZa+oAOarbWkuqATm7UMWqMgAYsgF0ckGR1ezQQJiR1ALhZKDZlGlkyNFB00JAAMxo4QWV59KVMeJw4ebZ1TdkIkCn60GPT8-REq5u79AARwYSFkOmCOlIAWgEQBoGut3mgmMryUNiQDjQhwiEDgWXxQA). 

I think we should disable automatic stacking when the scale is log.

**Comment by pdhorn** [comment]
Thanks for the tip and the fix @domoritz !
