### ISSUE TITLE
Vega 5.22 update breaks density charts

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#8049]
For example https://vega.github.io/editor/#/examples/vega-lite/area_density_facet

Visible in https://github.com/vega/vega-lite/pull/8047.

<img width="1148" alt="Screen Shot 2022-03-17 at 14 51 17" src="https://user-images.githubusercontent.com/589034/158900613-91e32432-9c11-4b39-83b7-0d4f59ac6049.png">

**Comment by jheer** [comment]
FWIW, the most related Vega examples don't appear to have any issues:

- https://vega.github.io/vega/examples/violin-plot/
- https://vega.github.io/vega/examples/probability-density/

Could these errors be due to inaccurate imputation of zero values? (Just trying to make sense of the jagged patterns in the new VL outputs.)

**Comment by jwoLondon** [comment]
If it helps to diagnose the problem, the correct density plots are generated if `steps` is set explicitly.
