### ISSUE TITLE
Different formatting of `month` transform in encoding, calculate and timeunit 

### ISSUE THREAD

**Issue by joelostblom** [vega/vega-lite#8101]
When I use `"timeUnit": "month"` in an encoding it will show months as their abbreviated name (Jan, Feb ,etc). However, when I use `month()` in a calculate transform, it will show months as numbers (0, 1, etc).  If I instead use `"timeUnit": "month"` in a timeunit transform, it will show the full date:

![image](https://user-images.githubusercontent.com/4560057/163292407-1734ba6c-b585-43c9-9487-2553b663e709.png)
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygK4CcA28QAspQA4Gc4B6IgYzADsA6AK3zAFNUBLAN2SooaiItwFsirBgHMIAWkgx83fAAFWARioAmAJxUADESkQiAMxYjs+cQFYA1rXwB7CiAC+AGhD8IyCxmQNSUEC4YKUhswZgoReFBg1BtkSJB9ZiYwDH4ATwB9fjsoTAzSCFRSfxAoNNwGDFjQikLHFwAPeMTk1MzsilyMqGZ+SpcyiqrkGrrnEDTmpNQUuHBoftLehgBVCmY-OY7cksHKueqwsfGoZAgKfH1Y-ngAbSjC0kRUBdSczAAKKUR+KikGACUJQg+DaWXe+Ue9VALRmGH+u2Waw2b06mGBoK27QhPT6jgAug4gA)

Based on [ the timeUnit docs](https://vega.github.io/vega-lite/docs/timeunit.html), I would expect all three uses of `'month'` to return the abbreviated form of the month name, but maybe I am misunderstanding.

```json
{
  "data": {
    "url": "https://cdn.jsdelivr.net/npm/vega-datasets@v1.29.0/data/flights-5k.json"
  },
  "mark": "rect",
  "encoding": {
    "color": {"field": "my_month_calc", "type": "ordinal"},
    "x": {"field": "my_month_time", "type": "ordinal"},
    "y": {"field": "date", "timeUnit": "month", "type": "ordinal"}
  },
  "transform": [
    {"calculate": "month(datum.date)", "as": "my_month_calc"},
    {"field": "date", "timeUnit": "month", "as": "my_month_time"}
  ]
}
```

**Comment by domoritz** [comment]
The time unit transform actually doesn't return the month but it bins the dates so that dates from the same month have the same date. The month() function actually extracts the month. The difference you see between the transform and the encoding property comes from formatting. Since we don't yet track transforms from outside the encoding, we don't automatically apply the right formatting. You can apply it manually and get the same output. 

Overall, this is expected behavior.
