### ISSUE TITLE
Add a `proportion` aggregation to complement `count`

### ISSUE THREAD

**Issue by joelostblom** [vega/vega-lite#8217]
The `count` aggregation makes it straightforward to show frequencies, but converting these to proportions is a bit inconvenient since it involves an additional transformation and manual definition of the total number of observations. It would be nice if there was a `proportion` aggregation in addition to `count`, similar to how there is both `sum` and `mean` aggregations (and I imagine the implementation would be similar to how `mean` works). An added utility of having this aggregation would be that it is simple to get percentages using the `%` d3 axis formatter with the `proportion` aggregation, instead of a separate transform as in https://vega.github.io/vega-lite/examples/window_percent_of_total.html

An example to illustrate this issue is when creating a empirical cumulative distribution function (ecdf). Doing this using the count of each observation is relatively straightforward with a window transform.

```json
{
  "mark": "line",
  "encoding": {
    "x": {"field": "values", "type": "quantitative"},
    "y": {"field": "cumulative_count", "type": "quantitative"}
  },
  "transform": [
    {
      "window": [{"op": "count", "as": "cumulative_count"}],
      "sort": [{"field": "values"}]
    }
  ],
  "data": {
    "values": [...]
}
}
```

![image](https://user-images.githubusercontent.com/4560057/172921104-b10aa73d-2c5c-4ba2-87cd-807eac33187a.png)

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygHYQLYFN7mhAtANjADMwBjAFgEY0ISBWAdkICYAGADgGYBOMPCAIwocmXJhTZk0FEAF8ANCBQQATgGtMAGwCWiDArSISAezA6A5vFAAPSyEJa0GsJgBuEDQFc0AZxAKoAJ4ADhhwIACOHhCIUFowsS4Y8iABtvaOzmEkHigeGtBaiQD6xh4xfiCBIZiR0bHxhUnJUMrR3oRGyijwANqgAO46YEb9vaBGQZil5QoQvlk5eQXF01CyALoK3p1rcH12Dk6u7l6+MuvnCpAw3mhQ86DXuATE5FQ0DMzs3LwCQiJiCRSMYgNyeHzwHAsAB0tDYYjwHA44jwtAoXFoHFo8lAYNOkJh9A4LFYLBY9HoXDYlNoGJxoJOELgOAo0LEFCYbHhcIoZDITE5ZHpeKZMIomKxXDwTAYeDYFDweH5wsZ81Z9D53G46NpGq4ZHoKvB8yh0JYZFELHFJJJrH11KN+LgrKxVo1TDIWLItFocrYjqZLNhiOpqM5SoYHH9clxqvgTGhFCTRP5ZBY0qVYkNMYZxvgrPReCtXNpcqT3q4AbV0I4Gs4eHocpYHDwSfEVfzbPT0q4VLIeC46KYRI7zNZ6eEvM9bF7tOEo9ZtAr-a5bBYmIHtdHptbqIb+qRwnNiNHMPhInhzblXCt5O3Z-oM9RFEbHKRFO3Lot32HirTCv7U8a3XCh0yHcULQYT1P2hVsOXNVh+wpcl6Aoe8a2EYcuHoJdsNA4ksXQkk-QNQt+VA1F0NA+gmGRVE4U4c02DlGCuRRdcey4LE2DhICmNJUDOHENdaAFIClyxejuEHOFHyFHMRRNMV6wzfthzTGd2wUuM4DPFhe0nVCBX1Sl0NrD00xowd-nXbNYzzZ02WJWhmwlSgMXYOzcydINayVH9pJwuU8HEot6DJThBxo+UF0TTMRHXd8eKlJg+Ig9Eoto3luE9VLtIcsUB3Csg11s7Ckqo4k+Rw5E0xc0QfW3BMX1qsQyRleUNRC-KfJhD0G2MqlaU1UTo3s3rYNQhgk2lSyirG7zRUTTkqRw9zsOsnj0LEDgDRvKNqQYS1uvGpaMVog61xbJUGw4WLbSjdSWytTFH3QtNdqs70Sy5RsmprNTZ3JLjUQdHqltreULsSxVe3hICpTkj0aQbEsTsWpSa3674m1bbk7vBzGLWsoQkXTJdaWxQn4BhFDh3FD19v1MQqdOzHG29Wz4W4OEi3RxSacTBgs3wud5SlBaBcc+ijKqjlGwRWK0QxOUXJfErODytn4wwq9tRpYRlWp5kYW4AVQI626G1442xQQ8VUJXOqkJg4cKWJPcB2LYcEajRFxXhb01sVIDHx4xmrKEeFpXQhhDvRR9RJKsKYN23leTDotQINVmMcFsleyLDdazhfV13k7XdNhJMJZo9SPqEUcOETF9QJJYSX19Cu86rjViI1Sg-e-bupdNdcqUHHiB3ECkbti0QCIkb1MWHTkCcroMOT5a2qXVrlK2NoMxHUj1fQvXbmPelsZXfHsbS5e6iStKrnLfVsYPC1Cv+vcQOQ5Pjk7MwxOIBEfIR46RhFSDMXFEKiCVFtW2ZoGA2mfgOfa4V+YQOhNFakFosqKiRLyWK8scIUmtDhfeXkpasg6qhHihZbqDhgqiSCUoNrCFbCIWOlILxEiXDtSgWse6miJGuREiIbwGgtDHQ+kD+QSmwmSSkA54aIMVLSS0Gi-4ckwQ5HACZ+pYhwn2Oc-IhGj0JJ6YW1IMQ+l9FuWRsF+xQJ2m6DqaFHFrW7A2HxrZizvWcQ2Zs29kS7UIo48Q7ASS9l5A2NsHiN5yObOVVC1tkS5wsbBCmiIfTyLLiSICfJ0wYmpIHGiHsqFYK9NvX0lJJEUkljpVkiJn7SJkuojJWDaLNniZ6fSaYPRAXobyck1sxAGnXFRGi35wyIlSf-RBQhcJ0VnojEs6FbHyijGmDacIxDnBkDIIAA)

However, to show the y-axis as a proportion I need to add a separate calculate transform and input the number of observations (100) manually (I tried `length(datum)` and similar but couldn't figure out how to compute the number of observations; it would be useful if this was possible and maybe it is but I couldn't find it):

```json
{
  "mark": "line",
  "encoding": {
    "x": {"field": "values", "type": "quantitative"},
    "y": {"field": "cumulative_proportion", "type": "quantitative"}
  },
  "transform": [
    {
      "window": [{"op": "count", "as": "cumulative_count"}],
      "sort": [{"field": "values"}]
    },
    {"calculate": "datum.cumulative_count / 100", "as": "cumulative_proportion"}
  ],
  "data": {
    "values": [...]
    }
}
```

![image](https://user-images.githubusercontent.com/4560057/172921728-32cf996b-1d39-4eec-a8e9-ba48c26a99ef.png)

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgtghgTg1iBcIA2BLAdgUxAGhBtAxgPYAm6A5gqAB5UgBmKGSJCIAbhEgK4YDOOEABcAngAcsiAI7cIaISiEQF7LAF9cIuo2atEBbmG5JlKVQH0xUImKJQFRNINES2MuQqUr1G4VDl89HZgCADaoADu6CREEWGgNmzE3PKCEAL6hsamFsmpagC6uHx2QvEMTCxsnDz8IIUaoARcBiZCkiAkyoYAdAZGbWYY5nlCAAQA9GMAjAAMs2kZIP3Z3pbWtvYojvVFncoQdDW8GeEcXCcIsz0AzACcAKwALABM9y8AbDf3N2-TH41zrUMi8etMHjd5jdptCAOx3G5PO4ADhugOOdXgAFprjcHndpi9YajwR94S8XrMHuiLpjrh8nrNEfM7vCyQSXk8acCEDjbrMnrCntC7h8qcjYbCbrDuZd4PTZtNYdMnsK7qqyU9wbK6T1nhCHgzpd8JXjqdhQBiMnyqQ8HtNpsiGbDnkrbTqMtcIY8BbDPh8Pi9ni87h6ENMerMPsjwW8EbNkW8XmH4BGqZKbh98Q8E4zkRKU9dCSing8Ke8YciIYX+fMvsyq+qKcKU3yvlWGYTBbCvnbkSmI9KVbMg5zow9lZnWxHPq9SxOxf7gzXDY7HoToTCUY7W7iqWK7QH68SPjCV43Zgi3jHBWXQxagXK+RDE8iqXd03cP4rp7cnmTiVHf9UWJGUHytXlrk5ENT2RR4UTJfFphrb5BUVOZpnVYk7k5NFwNpa0Z1+aUpUlJFM0NXcelZZkcxZMkxUvGtLyJG4nQnZ5Aw-UUVwJKUHURPE33+GtJQnF4lQdRtWTAy0CKuW5RwlU9viDeZFVkx9MQjZVXhRZ5S0DCcexrGFKTmYk4RjN4qMzKkQ30tixUDft8J5bF6QeJ0pWsrz-gRZC3KfIt02FRUmRRIU33NOT3KxCNwUTJslVPTCnNEp1A0wqK2MFM8gsxPlR1+OYR2VZFXntTSII8notQkrykUyiT5wHPUiXVNcs0TJEdwKwj+U6rMJJwiVDTw2Lgr1HsGVLDCGKlAF+t5NNOT9CctTJe5rJrRlFV7fzJ2VQLJt1XLGQnRF80TX5qvk+UenK0UGTFAlRWA2yvNZBMPnVFFWU+O73ISnsZoqoUUqbWymTmLViSeJ17klJbToGlVIUeDaESa6Eawkl1ZiFfV-1Bz42sNKMEUhENPjtIG5QS9UqzmINDQlEcazfJyIVVAknQ5USHKVOjYTKrN6e0noXrfT44K1f58wljJByRSVRRw+FIUzCatM9SMGpwhGlVU1EX1-Ssq0peFHReRGUd1hT5ie5sKqJQzA1-YUrtVjUtTgmKHdqkcczeQ1-opGFiNM-jpRcmX62rZbarxbqq0ZKVXhjAOaq9RrRSle0E1N7P7ojJtE2JHNpRze17ZzuqmQFCro0JT971RhTPgFQloPuetY9E4yvN+4UHW6ku4qLcd-0vRtXiRvGOKzb4Fx7EciV-NbUNFGNNZU38qSuntAcVRM+o72q4cJcGR3+LU8Soh0E3+X78X5pFTxrX7OR7x4KSZOaVFVTFl+E7E8AZ8oX2uGRCSKoXQxyRMmJOUEExRkZM6LWIYlYKRgQKIMVZm7amQT0fM14-jCnhPaROF8Zy8xVKqaUP0ESc1eCGehl5SxClVFRAM5IYwOj+MJFMoJPiijYvgxU-5SxIJoZGNi0pKSngkiOVyF8bT-i7mVQCPZERCiAYaIUP0i6iIRo-GElZFH2mlAjNiVE8EQkPqWQ230uTELYvmZKIZ3EBlLJzN4UoBRZgoVSJixDTS219F5W2vNVGByKv5HCR5KREg3sQu03YfJlS-AAms6sbZeWhLbMOVFSGIkZBROaMtbKqijFEsR4JYaPz9O8Jk8I4JfkpDrGq8VIzzXtADHxSJXFQJIX6VhENm4Eh3AUNQaggA)

**Comment by PBI-David** [comment]
FYI, you can use _length(data('source_0'))_ instead of your hard coded 100. 

[Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgtghgTg1iBcIA2BLAdgUxAGhBtAxgPYAm6A5gqAB5UgBmKGSJCIAbhEgK4YDOOEABcAngAcsiAI7cIaISiEQF7LAF9cIuo2atEBbmG5JlKVQH0xUImKJQFRNINES2MuQqUr1G4VDl89HZgCADaoADu6CREEWGgNmzE3PKCEAL6hsamFsmpagC6uHx2QvEMTCxsnDz8IIUaoARcBiZCksj45EIAFgAUJMoQfQDkJdxQBBjmAAwjAJTzaRnCREpI9dhNLdntbINChgB0BkZtZtN5QgAEAPTXSF29A0Oj45PTc4vLSVnnFlYbKUUI56kUQAcIHQarwMuEOFxYQgZkcAMwATgArAAWABMGNxADZURjUfiAIyExoI2oZXFHcmY1EzGao8lsgDs6NR2PRAA5UdSYXV4ABaFGozHo8m4jkCxmErm43EzTFCxEilGE7GsnUzdFcxXS3HY9W0hDitEzbEc7Fs9GE1V8jkc1Ecs1I+Bambkjnk7F29EBxXYxkezVHHFMzHat0k52StVbGmey2qzGY8nkvnajk433p8MZFFMrHWjlEwmE3E43HoosIclHGaEvmM-HcmZ8-G4hvwJuql2owlSzFdnV8519lEy-nYzHKgnsvlM6dWlnEnldqV4k2C5PCjKW4kr7Uym0c4kZvl9ptu-0zGsm1uYv3DvuiptEvHz1+Oyu1muMbZliMpsuy-LZh+Eqqo6GZVpucqEuyQErui+pkqibY2gu9YHhqR4llhuJ8qq6Gvui6E+h+d7YoqcpPnRApyu6+HmmKKImnWyF8li-KKlK5JriSNo+uSPpBnK6J7jRRw9m6rouryw4xtBRwGluY4sg6l7aWu+qylhI55nRdb6lSbGeiW0qulmPKSqRlJri6r64r6WZoQarGgIeyJok+zrISSNYsj63kpiKTZ+ni-I4vO1avpea7siq4lypybb4mpw6qnWsVGS2JFqSOOauplmJtoS3JCZZIqWuJr52j6rL8rapFJj5BEWk2jLdkGbmXlm3I5s5ObVuSBrYgKfI2ihtWEXJC5kuJj5+jNNa+mpoZuRVvJjW5v63pGspBiBJUmtKN7zd1VqnSObnSc6Mb7p17GWn+2rzuJlKXq6FmvamA4mhWjU-RimVrnqlKSpSBrsn6NUAxGWEBoOPKTt2ZLhb5XpHGtDrao60oOkx2UVQaXZVXtBpEtjXX9gyv1VjNtq+lTvbXRxVpstavozTmGIuv9EVHj1TVYo13J7Wya4DWOtpRnRv1EkdMYttyzJ1kSGZ0+xPVBiu4k1jGzqPmupFGUyAaXVVMrOXlvpaRyq3GUdhOkUSvGhpSk6656tFeQ60lcsyw4vSLfmPoy0lTb6wUCkyV1I6LDJYSuKpctmJHEsLOMoiy+PKlNeIK1WHPJzddro7ytp0aGvEdRHXOPmO+Ixvy0lucF4d54zbJutWk6Ppuq6c5akolSuOqunibaN73168oqMNdgn8-002-XdnKY5umOma5-TKI6syxetjKg6UbLjrbVxGKbgPzmJRVVPgSV69vTOL50fqaF4oLstXwxiZJKJmj5ZSyWBiJB0bYQ5BVkqqdGl5aY+m7FBMex93IkVEm5M8ko1JZi7JSKqUocxBgdIjJuWoY4yjrAuFUPJMxbW2tyFUMwXRjXgZzFESk3L+jzLZHk0lZZdhbDqXMoc6x+wjLw60NYVwzWQh-KyRxJz4kxv6N0oFR4VwZiaXk-oAxukptyc2u5pSoyDI1AMxUjQkSzGBbM1FOb0iJA6YiFUfR1wXEdVkzEVTITco+JOTc0ymUdKtBil4eS2i2jGW0lNV5uKmgQ9ky4AmZjdFNLCak5FMkQfOGOFNTTcLRBjfqs405VnnObfErprQjjtM7MceFdEogTCRcsFVsF7TUrgyilZqyrQgaUjMF4yqrUorqNcQcs4VTZCRduak1E8hPo0zMHtsqo3Ou4xk4kSm6PqhWAkrIuS8QGayBB30RwTQrNU3kByqGqIrLuVmijpRQQKGoNQQA)

**Comment by joelostblom** [comment]
Thanks @PBI-David , that is helpful! I tried `length(datum)` and `length(datum.cumulative_count)` but couldn't quite figure it out.

For anyone else working this from altair, you can also use f-strings in your transform calculate as a workaround until/if there is a `proportion` aggregation implemented:

```py
).transform_calculate(
    cumulative_proportion=f'datum.cumulative_count / {df.shape[0]}'
)
```

**Comment by joelostblom** [comment]
Closing in favor of https://github.com/vega/vega/issues/3510
