### ISSUE TITLE
Defined param not added as signal in compiled Vega when using a repeat operator

### ISSUE THREAD

**Issue by mattijn** [vega/vega-lite#8452]
The following Vega-Lite spec, [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUATJQAMlAFYQ2AOxAAaEDiQAnJAghoA2qGV64aTTr0B9SepAQ4guFExpQUZzosI2DR35uGnDKUGwAJjTKZAaohiAAHiAAuhrKcDpwEG6omNoMcBoqPn4BpNr2mACeOOboOGxRbgC+GsQ0cADusfHtXbYpzakg2nC1SDnxmIg41shJGjijUDQ4dBPsqhqdUeEpGhC1UO4g4RMoqKAM2oIWWLj4RAzKOADWZJRhCLwU-GeYSEcmAgAAEAIxSCQyAj-JAEToZehwbSfCDEECtEAhMKRaInMKCNgVS4gABmHUEe3QhKgG2KGmqtQsyjYCCiSFumIgNAAXnUPCpIphNicZtU0KSOY5FlYEBYtLoEAM2hyCmhJDIZJjiKq6mItRokiTyU4qacJuYGTQEHAAKrKOglZT0So1OogaYIBq6TkaKonE2Uk6jcY5EZjREYhluiwARwYSGd62FpHsSDIZFGFGmPgyqmamOQ2leFhW2k8lpAphtFj6nQGBaAA):
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.2.0.json",
  "params": [
    {
      "name": "param_2",
      "select": {
        "clear": "mouseout",
        "encodings": ["x"],
        "nearest": true,
        "on": "mouseover",
        "type": "point"
      },
      "views": ["view_2"]
    }
  ],
  "repeat": ["temp_max", "precipitation", "wind"],
  "spec": {
    "data": {"url": "https://unpkg.com/vega-datasets@1.25.0/data/weather.csv"},
    "encoding": {
      "color": {"field": "location", "type": "nominal"},
      "size": {
        "condition": {"empty": false, "param": "param_2", "value": 200},
        "value": 50
      },
      "x": {"field": "date", "timeUnit": "month", "type": "temporal"},
      "y": {"field": {"repeat": "repeat"}, "type": "quantitative", "aggregate":"mean"}
    },
    "mark": "circle",
    "name": "view_2"
  }
}
```
Gives the following error:
> ```cmd
> [Error] Unrecognized signal name: "param_2"
> ```

The signals definition in the Vega spec indeed shows no defined `param_2`:
```json
  "signals": [{"name": "childWidth", "value": 400}],
```

EDIT:
This only happens when the `"views"` attribute in the `params` is utilized.

**Comment by arvind** [comment]
Hi @mattijn, repeated views are named after the values that are enumerated out in order to allow you to address individual views. So, for the above spec, it should look something like this (which produces a [working visualization](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUATJQAMlAFYQ2AOxAAaEDiQAnJAghoA2qGV64aTTr0B9SepAQ4guFExpQUZzosI2DR35uGnDKUGwAJjTKZAaohiAAHiAAuhrKcDpwEG6omNoMcBoqPn4BpNr2mACeOOboOGxRbgC+GsQ0cADusfHtXbawNILh1taYiDjWyEltHZ0DMEMj1jjaLjQ4dEiY7Kqz-ZKDw6OdUeEpzakga7XbRiDjCJPT9qvrm5jbu-anyudXEFqUHcIHC2xQqFADG0ggsWFw+CIDGUOAA1mRKGEELwKPwwZ9HJgIAABACMUgkMgI+KQBE6GXocG0mIgxBArRAITCkWiILCgjYFUhIAAZh1hhYBVAvsUNNVahZlGwEFEkLCORAaAAvOoeFSRHbFYUTapoEVqxwaLS6BAWa02OxtNUFNCSGQyDnEZ11MQejRJYVipzndD48xymgIOAAVWUdBKynolRqdQeE0FavZGiqIKDEuFNwZFkLdw58tTAEcGEhE1sdqR7EgyGQ1hRxj4MqpmhzkNpURYoDRtJ5wyBTFGLH15nZu0A)):

```
"views": ["view_2child__temp_max", "view_2child__precipitation", "view_2child__wind"]
```

(Note, if the repeated view was not named `view_2`, then the resultant names would be simply `["child__temp_max", "child__precipitation", "child__wind"]`).

Hope this helps!

**Comment by mattijn** [comment]
Thanks @arvind, much appreciated for you response. Your suggestion works indeed for this example! That's great and will get us one step closer. For the record, with a bit more complicated chart, like a layered repeated chart it still result in errors, as reported in this comment: https://github.com/vega/vega-lite/issues/8348#issuecomment-1280028001
