### ISSUE TITLE
facet fails on arc

### ISSUE THREAD

**Issue by mattijn** [vega/vega-lite#8754]
Given the following vega-lite spec:
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.6.1.json",
  "data": {
    "values": [
      {"t": 0, "v": 2, "c": "foo"},
      {"t": 1, "v": 2.5, "c": "foo"},
      {"t": 2, "v": 3, "c": "foo"},
      {"t": 3, "v": 4, "c": "foo"},
      {"t": 4, "v": 5, "c": "foo"},
      {"t": 5, "v": 5.5, "c": "foo"},
      {"t": 6, "v": 4, "c": "foo"},
      {"t": 7, "v": 3, "c": "foo"},
      {"t": 0, "v": 2, "c": "bah"},
      {"t": 1, "v": 2.5, "c": "bah"},
      {"t": 2, "v": 3, "c": "bah"},
      {"t": 3, "v": 4, "c": "bah"},
      {"t": 4, "v": 5, "c": "bah"},
      {"t": 5, "v": 5.5, "c": "bah"},
      {"t": 6, "v": 4, "c": "bah"},
      {"t": 7, "v": 3, "c": "bah"}
    ]
  },
  "mark": {"type": "arc"},
  "encoding": {
    "color": {"field": "v", "type": "quantitative"},
    "column": {"field": "c", "type": "nominal"},
    "radius": {"field": "v", "type": "quantitative"},
    "theta": {"field": "t", "type": "nominal"}
  },

}
```
I see:
![image](https://user-images.githubusercontent.com/5186265/222481399-1b26cdfc-9bb8-4bc0-91d0-fae68379af9d.png)

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAbJQCMlAFYQ2AOxAAaEABMkmFKlDEkghnAhoA2qExoADBuJoATBqhoQAMzZsQAXzVW0GXsnSjEXN09vPwDUZxAHVABmcPRI338QayTg1AAWFI8vdJj8+LQwkFdUoujM8pyJCqrCqIysyRzS5rTarIB2HOTKiJq22xy45qYkGGK61CCy2NCC6dnep0HVmbmsoYSutzXdtFKEpqOdjdQK85Xh9GPrjqXDx6ux1AGloamrgF0-CBkAAnADWaCsAE8cHA3EgQa4gXBlFA2JoaMoyJDKmxBGwQTj3DQ4IJNG4HBpMDC4egAI4MJDKTB0HQ0UjpXHGBCqfQeElktyuKk0tzKNgITFGTkgpAYhhmPnE0nk9CUzKi+mM5mslkcoH0OC6IkC1V1EWwsUSqWCXw+HxAA)

It seems it is not possible to facet an arc-mark. 

Removing the `"column": {"field": "c", "type": "nominal"}` gives a single chart:
![image](https://user-images.githubusercontent.com/5186265/222481567-65e98521-4c07-4cc5-bded-7d015482fef2.png)

Altair python code:
```python
import altair as alt
import pandas as pd

base = pd.DataFrame(
    {"t": range(8),
     "v": [2, 2.5, 3, 4, 5, 5.5, 4, 3]}
)
cA = base.copy()
cA.loc[:, 'c'] = 'foo'
cB = base.copy()
cB.loc[:, 'c'] = 'bah'

source = pd.concat((cA, cB))
source.head()

arcs = alt.Chart(source).mark_arc().encode(theta="t:N", radius="v:Q", color="v:Q", column="c:N")
arcs
```

Related: https://github.com/vega/vega-lite/issues/3729

**Comment by ChiaLingWeng** [comment]
for this issue, I added width and height in config and it works,
since I saw they are 0 in dataviewer, not sure if this info helps
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAbJQCMlAFYQ2AOxAAaEABMkmFKlDEkghnAhoA2qExoADBuJoATBqhoQAMzZsQAXzVW0GXsnSjEXN09vPwDUZxAHVABmcPRI338QayTg1AAWFI8vdJj8+LQwkFdUoujM8pyJCqrCqIysyRzS5rTarIB2HOTKiJq22xy45qYkGGK61CCy2NCC6dnep0HVmbmsoYSutzXdtFKEpqOdjdQK85Xh9GPrjqXDx6ux1AGloamrgF0-CBkAAnADWaCsAE8cHA3EgQa4gXBlFA2JoaMoyJDKmxBGwQTj3DQ4IJNG4HBpMDC4egAI4MJDKTB0HQ0UjpXHGBCqfQeElktyuKk0tzKNgITFGTkgpAYhhmPnE0nk9CUzKi+mM5mslkcoH0OC6IkC1V1EWwsUSqWCXw+HxAA)
