### ISSUE TITLE
Why do we set the ticks only for x?

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#951]
https://github.com/vega/vega-lite/blob/master/src/compile/axis.ts#L113

**Comment by kanitw** [comment]
Because Vega's default ticks often lead to a lot of label occlusion on X without 90 degree rotation.
This is not an issue for Y.
Ideally, Vega could be smarter about that and have some mechanism to avoid labelling occlusion, but since it does not have it yet I found that default quite useful for avoiding occlusion. 

Maybe close this, but open an issue in Vega?

Note: You can comment on that line to ask too.

**Comment by domoritz** [comment]
> Note: You can comment on that line to ask too.

How?
