### ISSUE TITLE
Create only one data source

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#997]
At the moment, we compile two data sources, the raw data and an aggregated dataset. We do that so we  support aligned scales in aggregated and not aggregated axis in voyager. We think that we should be able to eliminate this by generating a single aggregated/raw data source where the aggregated data source also computes the min/max values.

**Comment by kanitw** [comment]
Doing so will prevent us from adding this rule:

> This property only works with aggregate functions that produce values ranging in the domain of the source data (`"mean"`, `"average"`, `"stdev"`, `"stdevp"`, `"median"`, `"q1"`, `"q3"`, `"min"`, `"max"`).  Otherwise, this property is ignored.

(Copied from scale docs)

**Comment by domoritz** [comment]
What is "this"?

**Comment by kanitw** [comment]
Oh yeah --- `useRawDomain`

**Comment by kanitw** [comment]
Related Question

`useRawDomain` —> `includeRawDomain` / `includeMinMaxDomain` / `includePreAggregateDomain` / `includeSourceDomain`?

**Comment by kanitw** [comment]
We should not always do this because

(1) this will make ordinal scale sorting incorrect.   For example,  

```json
{
   ...
   encoding: {
      x: {aggregate: 'mean', field: 'a', type:'Q'}, 
      y: {field: 'b', type: 'Q'}
      color: {field: 'b', type: 'Q'}
   }
}
```
If users want to sort `b` by `mean(a)` and we provide the aggregate data that's already grouped by both `b` and `c` , we cannot get `mean(a)` by `b` easily.


(2) do this does not help improving performance as Vega need to materialize new data after aggregation transformation anyway.   (Not sure if this is the exact reason, but I remember Jeff mentioned that don't worry about merging data sources since it doesn't help improve performance.)
